export const brown = [
    {
        rgb: [
            156,
            147,
            148,
        ],
        phonic: 'ài hè',
        type: 'brown',
        name: '艾褐',
        hex: '#9c9394',
    },
    {
        rgb: [
            89,
            38,
            32,
        ],
        phonic: 'àn tuó zōng',
        type: 'brown',
        name: '暗驼棕',
        hex: '#592620',
    },
    {
        rgb: [
            153,
            96,
            53,
        ],
        phonic: 'bīn láng zōng',
        type: 'brown',
        name: '槟榔棕',
        hex: '#996035',
    },
    {
        rgb: [
            47,
            30,
            20,
        ],
        phonic: 'chá hè',
        type: 'brown',
        name: '茶褐',
        hex: '#2f1e14',
    },
    {
        rgb: [
            97,
            74,
            30,
        ],
        phonic: 'chá lǜ hè',
        type: 'brown',
        name: '茶绿褐',
        hex: '#614a1e',
    },
    {
        rgb: [
            149,
            97,
            60,
        ],
        phonic: 'chén xiāng',
        type: 'brown',
        name: '沉香',
        hex: '#95613c',
    },
    {
        rgb: [
            87,
            65,
            61,
        ],
        phonic: 'chén xiāng hè',
        type: 'brown',
        name: '沉香褐',
        hex: '#57413d',
    },
    {
        rgb: [
            206,
            210,
            208,
        ],
        phonic: 'cōng bái hè',
        type: 'brown',
        name: '葱白褐',
        hex: '#ced2d0',
    },
    {
        rgb: [
            135,
            61,
            32,
        ],
        phonic: 'dàn dòu shā',
        type: 'brown',
        name: '淡豆沙',
        hex: '#873d20',
    },
    {
        rgb: [
            148,
            88,
            48,
        ],
        phonic: 'dàn kā fēi',
        type: 'brown',
        name: '淡咖啡',
        hex: '#945830',
    },
    {
        rgb: [
            189,
            126,
            80,
        ],
        phonic: 'dàn zhě',
        type: 'brown',
        name: '淡赭',
        hex: '#bd7e50',
    },
    {
        rgb: [
            164,
            117,
            99,
        ],
        phonic: 'diāo yè zōng',
        type: 'brown',
        name: '凋叶棕',
        hex: '#a47563',
    },
    {
        rgb: [
            113,
            55,
            31,
        ],
        phonic: 'dīng xiāng hè',
        type: 'brown',
        name: '丁香褐',
        hex: '#71371f',
    },
    {
        rgb: [
            113,
            55,
            31,
        ],
        phonic: 'dīng xiāng zōng',
        type: 'brown',
        name: '丁香棕',
        hex: '#71371f',
    },
    {
        rgb: [
            102,
            84,
            63,
        ],
        phonic: 'dòu qīng hè',
        type: 'brown',
        name: '豆青褐',
        hex: '#66543f',
    },
    {
        rgb: [
            72,
            45,
            36,
        ],
        phonic: 'dòu shā',
        type: 'brown',
        name: '豆沙',
        hex: '#482d24',
    },
    {
        rgb: [
            157,
            109,
            107,
        ],
        phonic: 'fěn zōng',
        type: 'brown',
        name: '粉棕',
        hex: '#9d6d6b',
    },
    {
        rgb: [
            80,
            48,
            31,
        ],
        phonic: 'gǔ tóng',
        type: 'brown',
        name: '古铜',
        hex: '#50301f',
    },
    {
        rgb: [
            92,
            55,
            26,
        ],
        phonic: 'gǔ tóng hè',
        type: 'brown',
        name: '古铜褐',
        hex: '#5c371a',
    },
    {
        rgb: [
            167,
            109,
            69,
        ],
        phonic: 'guì pí dàn zōng',
        type: 'brown',
        name: '桂皮淡棕',
        hex: '#a76d45',
    },
    {
        rgb: [
            169,
            105,
            77,
        ],
        phonic: 'guì pí zōng',
        type: 'brown',
        name: '桂皮棕',
        hex: '#a9694d',
    },
    {
        rgb: [
            83,
            22,
            19,
        ],
        phonic: 'hóng dòu shā',
        type: 'brown',
        name: '红豆沙',
        hex: '#531613',
    },
    {
        rgb: [
            95,
            41,
            5,
        ],
        phonic: 'hú shuǐ hè',
        type: 'brown',
        name: '湖水褐',
        hex: '#5f2905',
    },
    {
        rgb: [
            171,
            131,
            96,
        ],
        phonic: 'huáng zōng',
        type: 'brown',
        name: '黄棕',
        hex: '#ab8360',
    },
    {
        rgb: [
            171,
            106,
            76,
        ],
        phonic: 'huǒ ní zōng',
        type: 'brown',
        name: '火泥棕',
        hex: '#ab6a4c',
    },
    {
        rgb: [
            72,
            37,
            35,
        ],
        phonic: 'huǒ shān zōng',
        type: 'brown',
        name: '火山棕',
        hex: '#482523',
    },
    {
        rgb: [
            134,
            48,
            32,
        ],
        phonic: 'huǒ yán zōng',
        type: 'brown',
        name: '火岩棕',
        hex: '#863020',
    },
    {
        rgb: [
            175,
            105,
            70,
        ],
        phonic: 'jǐ zōng',
        type: 'brown',
        name: '麂棕',
        hex: '#af6946',
    },
    {
        rgb: [
            76,
            55,
            47,
        ],
        phonic: 'jiàng chá hè',
        type: 'brown',
        name: '酱茶褐',
        hex: '#4c372f',
    },
    {
        rgb: [
            73,
            51,
            53,
        ],
        phonic: 'jiàng sè',
        type: 'brown',
        name: '酱色',
        hex: '#493335',
    },
    {
        rgb: [
            90,
            31,
            27,
        ],
        phonic: 'jiàng zōng',
        type: 'brown',
        name: '酱棕',
        hex: '#5a1f1b',
    },
    {
        rgb: [
            70,
            44,
            43,
        ],
        phonic: 'jiāo hè',
        type: 'brown',
        name: '椒褐',
        hex: '#462c2b',
    },
    {
        rgb: [
            63,
            48,
            42,
        ],
        phonic: 'jiāo chá',
        type: 'brown',
        name: '燋茶',
        hex: '#3f302a',
    },
    {
        rgb: [
            176,
            147,
            107,
        ],
        phonic: 'jīn chá hè',
        type: 'brown',
        name: '金茶褐',
        hex: '#b0936b',
    },
    {
        rgb: [
            99,
            96,
            83,
        ],
        phonic: 'jīng hè',
        type: 'brown',
        name: '荆褐',
        hex: '#636053',
    },
    {
        rgb: [
            193,
            101,
            26,
        ],
        phonic: 'kā fēi',
        type: 'brown',
        name: '咖啡',
        hex: '#c1651a',
    },
    {
        rgb: [
            92,
            61,
            33,
        ],
        phonic: 'ké sè',
        type: 'brown',
        name: '壳色',
        hex: '#5c3d21',
    },
    {
        rgb: [
            101,
            43,
            28,
        ],
        phonic: 'kě kě zōng',
        type: 'brown',
        name: '可可棕',
        hex: '#652b1c',
    },
    {
        rgb: [
            168,
            149,
            121,
        ],
        phonic: 'kū zhú hè',
        type: 'brown',
        name: '枯竹褐',
        hex: '#a89579',
    },
    {
        rgb: [
            206,
            210,
            211,
        ],
        phonic: 'lì ké',
        type: 'brown',
        name: '栗壳',
        hex: '#ced2d3',
    },
    {
        rgb: [
            92,
            30,
            25,
        ],
        phonic: 'lì zōng',
        type: 'brown',
        name: '栗棕',
        hex: '#5c1e19',
    },
    {
        rgb: [
            148,
            88,
            51,
        ],
        phonic: 'lù jiǎo zōng',
        type: 'brown',
        name: '鹿角棕',
        hex: '#945833',
    },
    {
        rgb: [
            207,
            142,
            93,
        ],
        phonic: 'lù pí hè',
        type: 'brown',
        name: '鹿皮褐',
        hex: '#cf8e5d',
    },
    {
        rgb: [
            214,
            186,
            164,
        ],
        phonic: 'lù hè',
        type: 'brown',
        name: '露褐',
        hex: '#d6baa4',
    },
    {
        rgb: [
            116,
            91,
            71,
        ],
        phonic: 'luó hàn guǒ',
        type: 'brown',
        name: '罗汉果',
        hex: '#745b47',
    },
    {
        rgb: [
            164,
            117,
            99,
        ],
        phonic: 'luò yè zōng',
        type: 'brown',
        name: '落叶棕',
        hex: '#a47563',
    },
    {
        rgb: [
            149,
            68,
            22,
        ],
        phonic: 'máng guǒ zōng',
        type: 'brown',
        name: '芒果棕',
        hex: '#954416',
    },
    {
        rgb: [
            242,
            240,
            212,
        ],
        phonic: 'mǐ sè',
        type: 'brown',
        name: '米色',
        hex: '#f2f0d4',
    },
    {
        rgb: [
            38,
            25,
            25,
        ],
        phonic: 'mò xiāng',
        type: 'brown',
        name: '墨缃',
        hex: '#261919',
    },
    {
        rgb: [
            71,
            30,
            28,
        ],
        phonic: 'nǎi zōng',
        type: 'brown',
        name: '奶棕',
        hex: '#471e1c',
    },
    {
        rgb: [
            157,
            109,
            107,
        ],
        phonic: 'ní jīn',
        type: 'brown',
        name: '泥金',
        hex: '#9d6d6b',
    },
    {
        rgb: [
            87,
            72,
            69,
        ],
        phonic: 'niú róng',
        type: 'brown',
        name: '牛绒',
        hex: '#574845',
    },
    {
        rgb: [
            90,
            66,
            49,
        ],
        phonic: 'ǒu hè',
        type: 'brown',
        name: '藕褐',
        hex: '#5a4231',
    },
    {
        rgb: [
            92,
            55,
            26,
        ],
        phonic: 'ǒu sī hè',
        type: 'brown',
        name: '藕丝褐',
        hex: '#5c371a',
    },
    {
        rgb: [
            148,
            104,
            107,
        ],
        phonic: 'pú táo hè',
        type: 'brown',
        name: '葡萄褐',
        hex: '#94686B',
    },
    {
        rgb: [
            83,
            22,
            19,
        ],
        phonic: 'qiǎn huáng zōng',
        type: 'brown',
        name: '浅黄棕',
        hex: '#531613',
    },
    {
        rgb: [
            95,
            41,
            5,
        ],
        phonic: 'qiǎn jīng hè',
        type: 'brown',
        name: '浅荆褐',
        hex: '#5f2905',
    },
    {
        rgb: [
            171,
            131,
            96,
        ],
        phonic: 'qiǎn tuó',
        type: 'brown',
        name: '浅驼',
        hex: '#ab8360',
    },
    {
        rgb: [
            171,
            106,
            76,
        ],
        phonic: 'qiǎn zōng huī',
        type: 'brown',
        name: '浅棕灰',
        hex: '#ab6a4c',
    },
    {
        rgb: [
            72,
            37,
            35,
        ],
        phonic: 'qiū chá hè',
        type: 'brown',
        name: '秋茶褐',
        hex: '#482523',
    },
    {
        rgb: [
            134,
            48,
            33,
        ],
        phonic: 'qiū sè',
        type: 'brown',
        name: '秋色',
        hex: '#863021',
    },
    {
        rgb: [
            196,
            91,
            8,
        ],
        phonic: 'shā shí sè',
        type: 'brown',
        name: '砂石色',
        hex: '#c45b08',
    },
    {
        rgb: [
            207,
            160,
            122,
        ],
        phonic: 'shān gǔ hè',
        type: 'brown',
        name: '山谷褐',
        hex: '#cfa07a',
    },
    {
        rgb: [
            152,
            106,
            76,
        ],
        phonic: 'shān jī hè',
        type: 'brown',
        name: '山鸡褐',
        hex: '#986a4c',
    },
    {
        rgb: [
            76,
            44,
            31,
        ],
        phonic: 'shēn hè',
        type: 'brown',
        name: '深褐',
        hex: '#4c2c1f',
    },
    {
        rgb: [
            87,
            60,
            55,
        ],
        phonic: 'shí hè',
        type: 'brown',
        name: '石褐',
        hex: '#573c37',
    },
    {
        rgb: [
            168,
            161,
            155,
        ],
        phonic: 'shǔ máo hè',
        type: 'brown',
        name: '鼠毛褐',
        hex: '#a8a19b',
    },
    {
        rgb: [
            82,
            57,
            49,
        ],
        phonic: 'sǔn pí zōng',
        type: 'brown',
        name: '笋皮棕',
        hex: '#523931',
    },
    {
        rgb: [
            86,
            48,
            45,
        ],
        phonic: 'tán hè',
        type: 'brown',
        name: '檀褐',
        hex: '#56302d',
    },
    {
        rgb: [
            155,
            102,
            81,
        ],
        phonic: 'táng lí hè',
        type: 'brown',
        name: '棠梨褐',
        hex: '#9b6651',
    },
    {
        rgb: [
            57,
            34,
            34,
        ],
        phonic: 'tiě zōng',
        type: 'brown',
        name: '铁棕',
        hex: '#392222',
    },
    {
        rgb: [
            120,
            95,
            65,
        ],
        phonic: 'tuó hè',
        type: 'brown',
        name: '驼褐',
        hex: '#785f41',
    },
    {
        rgb: [
            159,
            123,
            97,
        ],
        phonic: 'tuó róng',
        type: 'brown',
        name: '驼绒',
        hex: '#9f7b61',
    },
    {
        rgb: [
            125,
            93,
            70,
        ],
        phonic: 'tuó sè',
        type: 'brown',
        name: '驼色',
        hex: '#7d5d46',
    },
    {
        rgb: [
            159,
            73,
            46,
        ],
        phonic: 'tuó róng',
        type: 'brown',
        name: '酡绒',
        hex: '#9f492e',
    },
    {
        rgb: [
            142,
            71,
            59,
        ],
        phonic: 'xiàng zǐ zōng',
        type: 'brown',
        name: '橡子棕',
        hex: '#8e473b',
    },
    {
        rgb: [
            150,
            77,
            34,
        ],
        phonic: 'yán shí zōng',
        type: 'brown',
        name: '岩石棕',
        hex: '#964d22',
    },
    {
        rgb: [
            128,
            57,
            25,
        ],
        phonic: 'yē ké zōng',
        type: 'brown',
        name: '椰壳棕',
        hex: '#803919',
    },
    {
        rgb: [
            193,
            188,
            166,
        ],
        phonic: 'yín hè',
        type: 'brown',
        name: '银褐',
        hex: '#c1bca6',
    },
    {
        rgb: [
            147,
            128,
            134,
        ],
        phonic: 'yīng bèi hè',
        type: 'brown',
        name: '鹰背褐',
        hex: '#938086',
    },
    {
        rgb: [
            26,
            17,
            10,
        ],
        phonic: 'yíng shuāng hè',
        type: 'brown',
        name: '迎霜褐',
        hex: '#1a110a',
    },
    {
        rgb: [
            82,
            38,
            29,
        ],
        phonic: 'yóu sù hè',
        type: 'brown',
        name: '油粟褐',
        hex: '#52261d',
    },
    {
        rgb: [
            231,
            187,
            138,
        ],
        phonic: 'yuán yǎn',
        type: 'brown',
        name: '圆眼',
        hex: '#e7bb8a',
    },
    {
        rgb: [
            102,
            56,
            57,
        ],
        phonic: 'zǎo hè',
        type: 'brown',
        name: '枣褐',
        hex: '#663839',
    },
    {
        rgb: [
            105,
            42,
            27,
        ],
        phonic: 'zhà yè zōng',
        type: 'brown',
        name: '柞叶棕',
        hex: '#692a1b',
    },
    {
        rgb: [
            195,
            96,
            66,
        ],
        phonic: 'zhě shí',
        type: 'brown',
        name: '赭石',
        hex: '#c36042',
    },
    {
        rgb: [
            150,
            95,
            64,
        ],
        phonic: 'zhǐ zōng',
        type: 'brown',
        name: '纸棕',
        hex: '#965f40',
    },
    {
        rgb: [
            112,
            76,
            64,
        ],
        phonic: 'zhōng huī tuó',
        type: 'brown',
        name: '中灰驼',
        hex: '#704c40',
    },
    {
        rgb: [
            166,
            71,
            67,
        ],
        phonic: 'zhū zǐ hè',
        type: 'brown',
        name: '珠子褐',
        hex: '#a64743',
    },
    {
        rgb: [
            116,
            69,
            59,
        ],
        phonic: 'zhuān hè',
        type: 'brown',
        name: '砖褐',
        hex: '#74453b',
    },
    {
        rgb: [
            79,
            26,
            34,
        ],
        phonic: 'zǐ tán',
        type: 'brown',
        name: '紫檀',
        hex: '#4f1a22',
    },
    {
        rgb: [
            81,
            67,
            54,
        ],
        phonic: 'zōng chá',
        type: 'brown',
        name: '棕茶',
        hex: '#514336',
    },
    {
        rgb: [
            103,
            46,
            61,
        ],
        phonic: 'zōng hóng',
        type: 'brown',
        name: '棕红',
        hex: '#672e3d',
    },
    {
        rgb: [
            119,
            109,
            107,
        ],
        phonic: 'zōng huī',
        type: 'brown',
        name: '棕灰',
        hex: '#776d6b',
    },
    {
        rgb: [
            97,
            64,
            47,
        ],
        phonic: 'zōng sè',
        type: 'brown',
        name: '棕色',
        hex: '#61402f',
    },
]
