export const green = [
    {
        rgb: [
            223,
            237,
            214,
        ],
        phonic: 'ài bèi lǜ',
        type: 'green',
        name: '艾背绿',
        hex: '#dfedd6',
    },
    {
        rgb: [
            165,
            190,
            125,
        ],
        phonic: 'ài lǜ',
        type: 'green',
        name: '艾绿',
        hex: '#a5be7d',
    },
    {
        rgb: [
            58,
            50,
            13,
        ],
        phonic: 'àn gǎn lǎn lǜ',
        type: 'green',
        name: '暗橄榄绿',
        hex: '#3a320d',
    },
    {
        rgb: [
            59,
            78,
            57,
        ],
        phonic: 'bā jiāo lǜ',
        type: 'green',
        name: '芭蕉绿',
        hex: '#3b4e39',
    },
    {
        rgb: [
            81,
            98,
            62,
        ],
        phonic: 'bái pí sōng lǜ',
        type: 'green',
        name: '白皮松绿',
        hex: '#51623e',
    },
    {
        rgb: [
            73,
            91,
            77,
        ],
        phonic: 'bái qū cài lǜ',
        type: 'green',
        name: '白屈菜绿',
        hex: '#495b4d',
    },
    {
        rgb: [
            79,
            101,
            69,
        ],
        phonic: 'bǎi zhī lǜ',
        type: 'green',
        name: '柏枝绿',
        hex: '#4f6545',
    },
    {
        rgb: [
            162,
            187,
            122,
        ],
        phonic: 'bǎi zhī lǜ',
        type: 'green',
        name: '柏枝绿',
        hex: '#a2bb7a',
    },
    {
        rgb: [
            33,
            127,
            77,
        ],
        phonic: 'bò he lǜ',
        type: 'green',
        name: '薄荷绿',
        hex: '#217f4d',
    },
    {
        rgb: [
            72,
            139,
            109,
        ],
        phonic: 'bǎo shí lǜ',
        type: 'green',
        name: '宝石绿',
        hex: '#488b6d',
    },
    {
        rgb: [
            102,
            183,
            0,
        ],
        phonic: 'bì chán lǜ',
        type: 'green',
        name: '碧蝉绿',
        hex: '#66b700',
    },
    {
        rgb: [
            134,
            113,
            24,
        ],
        phonic: 'bì luó chūn lǜ',
        type: 'green',
        name: '碧罗春绿',
        hex: '#867118',
    },
    {
        rgb: [
            149,
            177,
            162,
        ],
        phonic: 'bì sè',
        type: 'green',
        name: '碧色',
        hex: '#95b1a2',
    },
    {
        rgb: [
            97,
            139,
            93,
        ],
        phonic: 'bō lí lǜ',
        type: 'green',
        name: '玻璃绿',
        hex: '#618b5d',
    },
    {
        rgb: [
            34,
            80,
            54,
        ],
        phonic: 'cāng lǜ',
        type: 'green',
        name: '苍绿',
        hex: '#225036',
    },
    {
        rgb: [
            141,
            128,
            75,
        ],
        phonic: 'cǎo huī lǜ',
        type: 'green',
        name: '草灰绿',
        hex: '#8d804b',
    },
    {
        rgb: [
            131,
            190,
            82,
        ],
        phonic: 'cǎo lǜ',
        type: 'green',
        name: '草绿',
        hex: '#83be52',
    },
    {
        rgb: [
            60,
            149,
            103,
        ],
        phonic: 'chán lǜ',
        type: 'green',
        name: '蟾绿',
        hex: '#3c9567',
    },
    {
        rgb: [
            153,
            219,
            5,
        ],
        phonic: 'chūn lǜ',
        type: 'green',
        name: '春绿',
        hex: '#99db05',
    },
    {
        rgb: [
            154,
            181,
            52,
        ],
        phonic: 'cōng lǜ',
        type: 'green',
        name: '葱绿',
        hex: '#9ab534',
    },
    {
        rgb: [
            55,
            56,
            51,
        ],
        phonic: 'cōng yóu lǜ',
        type: 'green',
        name: '葱油绿',
        hex: '#373833',
    },
    {
        rgb: [
            32,
            165,
            94,
        ],
        phonic: 'cuì lǜ',
        type: 'green',
        name: '翠绿',
        hex: '#20a55e',
    },
    {
        rgb: [
            118,
            155,
            122,
        ],
        phonic: 'cuì píng lǜ',
        type: 'green',
        name: '翠屏绿',
        hex: '#769b7a',
    },
    {
        rgb: [
            97,
            172,
            133,
        ],
        phonic: 'dàn lǜ',
        type: 'green',
        name: '淡绿',
        hex: '#61ac85',
    },
    {
        rgb: [
            88,
            149,
            115,
        ],
        phonic: 'dàn bái shí lǜ',
        type: 'green',
        name: '蛋白石绿',
        hex: '#589573',
    },
    {
        rgb: [
            102,
            142,
            19,
        ],
        phonic: 'dōng qīng lǜ',
        type: 'green',
        name: '冬青绿',
        hex: '#668e13',
    },
    {
        rgb: [
            147,
            178,
            134,
        ],
        phonic: 'dòu lǜ',
        type: 'green',
        name: '豆绿',
        hex: '#93b286',
    },
    {
        rgb: [
            99,
            137,
            112,
        ],
        phonic: 'dú shān yù lǜ',
        type: 'green',
        name: '独山玉绿',
        hex: '#638970',
    },
    {
        rgb: [
            109,
            157,
            48,
        ],
        phonic: 'fǎng zhī niáng lǜ',
        type: 'green',
        name: '纺织娘绿',
        hex: '#6d9d30',
    },
    {
        rgb: [
            73,
            117,
            104,
        ],
        phonic: 'fēi quán lǜ',
        type: 'green',
        name: '飞泉绿',
        hex: '#497568',
    },
    {
        rgb: [
            46,
            131,
            48,
        ],
        phonic: 'fěi cuì',
        type: 'green',
        name: '翡翠',
        hex: '#2e8330',
    },
    {
        rgb: [
            137,
            226,
            191,
        ],
        phonic: 'fěn lǜ',
        type: 'green',
        name: '粉绿',
        hex: '#89e2bf',
    },
    {
        rgb: [
            126,
            190,
            104,
        ],
        phonic: 'fú píng lǜ',
        type: 'green',
        name: '浮萍绿',
        hex: '#7ebe68',
    },
    {
        rgb: [
            191,
            201,
            53,
        ],
        phonic: 'gǎn lǎn huáng lǜ',
        type: 'green',
        name: '橄榄黄绿',
        hex: '#bfc935',
    },
    {
        rgb: [
            96,
            89,
            24,
        ],
        phonic: 'gǎn lǎn lǜ',
        type: 'green',
        name: '橄榄绿',
        hex: '#605918',
    },
    {
        rgb: [
            177,
            207,
            135,
        ],
        phonic: 'gǎn lǎn shí lǜ',
        type: 'green',
        name: '橄榄石绿',
        hex: '#b1cf87',
    },
    {
        rgb: [
            32,
            137,
            78,
        ],
        phonic: 'gōng diàn lǜ',
        type: 'green',
        name: '宫殿绿',
        hex: '#20894e',
    },
    {
        rgb: [
            83,
            60,
            28,
        ],
        phonic: 'gǔ tóng lǜ',
        type: 'green',
        name: '古铜绿',
        hex: '#533c1c',
    },
    {
        rgb: [
            106,
            150,
            75,
        ],
        phonic: 'guā lǜ',
        type: 'green',
        name: '瓜绿',
        hex: '#6a964b',
    },
    {
        rgb: [
            91,
            168,
            56,
        ],
        phonic: 'guān lǜ',
        type: 'green',
        name: '官绿',
        hex: '#5ba838',
    },
    {
        rgb: [
            70,
            82,
            80,
        ],
        phonic: 'guī bèi huī lǜ',
        type: 'green',
        name: '龟背灰绿',
        hex: '#465250',
    },
    {
        rgb: [
            48,
            58,
            5,
        ],
        phonic: 'hǎi dài lǜ',
        type: 'green',
        name: '海带绿',
        hex: '#303a05',
    },
    {
        rgb: [
            58,
            116,
            41,
        ],
        phonic: 'hé yè lǜ',
        type: 'green',
        name: '荷叶绿',
        hex: '#3a7429',
    },
    {
        rgb: [
            31,
            68,
            0,
        ],
        phonic: 'hēi lǜ',
        type: 'green',
        name: '黑绿',
        hex: '#1f4400',
    },
    {
        rgb: [
            43,
            49,
            45,
        ],
        phonic: 'hú jì shēng lǜ',
        type: 'green',
        name: '槲寄生绿',
        hex: '#2b312d',
    },
    {
        rgb: [
            207,
            220,
            115,
        ],
        phonic: 'huái huā huáng lǜ',
        type: 'green',
        name: '槐花黄绿',
        hex: '#cfdc73',
    },
    {
        rgb: [
            49,
            74,
            68,
        ],
        phonic: 'huī lǜ',
        type: 'green',
        name: '灰绿',
        hex: '#314a44',
    },
    {
        rgb: [
            129,
            201,
            75,
        ],
        phonic: 'qí cài lǜ',
        type: 'green',
        name: '荠菜绿',
        hex: '#81c94b',
    },
    {
        rgb: [
            64,
            88,
            28,
        ],
        phonic: 'jiàn qiào lǜ',
        type: 'green',
        name: '剑鞘绿',
        hex: '#40581c',
    },
    {
        rgb: [
            67,
            145,
            9,
        ],
        phonic: 'jīng lǜ',
        type: 'green',
        name: '京绿',
        hex: '#439109',
    },
    {
        rgb: [
            220,
            245,
            162,
        ],
        phonic: 'jú lǜ',
        type: 'green',
        name: '菊绿',
        hex: '#dcf5a2',
    },
    {
        rgb: [
            73,
            186,
            124,
        ],
        phonic: 'kōng qīng',
        type: 'green',
        name: '空青',
        hex: '#49ba7c',
    },
    {
        rgb: [
            40,
            151,
            95,
        ],
        phonic: 'kǒng què lǜ',
        type: 'green',
        name: '孔雀绿',
        hex: '#28975f',
    },
    {
        rgb: [
            150,
            199,
            120,
        ],
        phonic: 'kòu shāo lǜ',
        type: 'green',
        name: '蔻梢绿',
        hex: '#96c778',
    },
    {
        rgb: [
            185,
            179,
            121,
        ],
        phonic: 'kū lǜ',
        type: 'green',
        name: '枯绿',
        hex: '#b9b379',
    },
    {
        rgb: [
            45,
            81,
            77,
        ],
        phonic: 'lǎo jù lǜ',
        type: 'green',
        name: '老醵绿',
        hex: '#2d514d',
    },
    {
        rgb: [
            41,
            82,
            52,
        ],
        phonic: 'lǎo kuí lǜ',
        type: 'green',
        name: '老葵绿',
        hex: '#295234',
    },
    {
        rgb: [
            58,
            94,
            80,
        ],
        phonic: 'lǎo lán huā lǜ',
        type: 'green',
        name: '老蓝花绿',
        hex: '#3a5e50',
    },
    {
        rgb: [
            62,
            74,
            62,
        ],
        phonic: 'lǎo lǜ',
        type: 'green',
        name: '老绿',
        hex: '#3e4a3e',
    },
    {
        rgb: [
            78,
            134,
            86,
        ],
        phonic: 'liú lí lǜ',
        type: 'green',
        name: '琉璃绿',
        hex: '#4e8656',
    },
    {
        rgb: [
            185,
            211,
            28,
        ],
        phonic: 'liǔ fāng lǜ',
        type: 'green',
        name: '柳芳绿',
        hex: '#b9d31c',
    },
    {
        rgb: [
            175,
            221,
            35,
        ],
        phonic: 'liǔ lǜ',
        type: 'green',
        name: '柳绿',
        hex: '#afdd23',
    },
    {
        rgb: [
            184,
            208,
            122,
        ],
        phonic: 'lú wěi lǜ',
        type: 'green',
        name: '芦苇绿',
        hex: '#b8d07a',
    },
    {
        rgb: [
            55,
            87,
            50,
        ],
        phonic: 'lǜ shěn',
        type: 'green',
        name: '绿沈',
        hex: '#375732',
    },
    {
        rgb: [
            110,
            139,
            11,
        ],
        phonic: 'mǎ tí lián lǜ',
        type: 'green',
        name: '马蹄莲绿',
        hex: '#6e8b0b',
    },
    {
        rgb: [
            85,
            187,
            139,
        ],
        phonic: 'mài lǜ',
        type: 'green',
        name: '麦绿',
        hex: '#55bb8b',
    },
    {
        rgb: [
            91,
            192,
            132,
        ],
        phonic: 'mài miáo lǜ',
        type: 'green',
        name: '麦苗绿',
        hex: '#5bc084',
    },
    {
        rgb: [
            20,
            31,
            27,
        ],
        phonic: 'mǎng cóng lǜ',
        type: 'green',
        name: '莽丛绿',
        hex: '#141f1b',
    },
    {
        rgb: [
            68,
            122,
            20,
        ],
        phonic: 'máo lǜ',
        type: 'green',
        name: '毛绿',
        hex: '#447a14',
    },
    {
        rgb: [
            18,
            170,
            157,
        ],
        phonic: 'měi dié lǜ',
        type: 'green',
        name: '美蝶绿',
        hex: '#12aa9d',
    },
    {
        rgb: [
            133,
            175,
            101,
        ],
        phonic: 'míng lǜ',
        type: 'green',
        name: '明绿',
        hex: '#85af65',
    },
    {
        rgb: [
            34,
            51,
            35,
        ],
        phonic: 'mò lǜ',
        type: 'green',
        name: '墨绿',
        hex: '#223323',
    },
    {
        rgb: [
            147,
            153,
            117,
        ],
        phonic: 'mǔ lì lǜ',
        type: 'green',
        name: '牡蛎绿',
        hex: '#939975',
    },
    {
        rgb: [
            167,
            176,
            121,
        ],
        phonic: 'nǎi lǜ',
        type: 'green',
        name: '奶绿',
        hex: '#a7b079',
    },
    {
        rgb: [
            68,
            177,
            68,
        ],
        phonic: 'nèn lǜ',
        type: 'green',
        name: '嫩绿',
        hex: '#44b144',
    },
    {
        rgb: [
            106,
            188,
            152,
        ],
        phonic: 'piǎo sè',
        type: 'green',
        name: '缥色',
        hex: '#6abc98',
    },
    {
        rgb: [
            190,
            208,
            135,
        ],
        phonic: 'píng guǒ lǜ',
        type: 'green',
        name: '苹果绿',
        hex: '#bed087',
    },
    {
        rgb: [
            10,
            58,
            39,
        ],
        phonic: 'qī lǜ',
        type: 'green',
        name: '漆绿',
        hex: '#0a3a27',
    },
    {
        rgb: [
            63,
            102,
            71,
        ],
        phonic: 'qīng cài lǜ',
        type: 'green',
        name: '青菜绿',
        hex: '#3f6647',
    },
    {
        rgb: [
            43,
            150,
            120,
        ],
        phonic: 'qīng fán lǜ',
        type: 'green',
        name: '青矾绿',
        hex: '#2b9678',
    },
    {
        rgb: [
            90,
            135,
            126,
        ],
        phonic: 'qīng lǜ',
        type: 'green',
        name: '青绿',
        hex: '#5a877e',
    },
    {
        rgb: [
            149,
            190,
            150,
        ],
        phonic: 'qīng méi lǜ',
        type: 'green',
        name: '青梅绿',
        hex: '#95be96',
    },
    {
        rgb: [
            173,
            200,
            131,
        ],
        phonic: 'qiū guī',
        type: 'green',
        name: '秋瑰',
        hex: '#adc883',
    },
    {
        rgb: [
            186,
            206,
            102,
        ],
        phonic: 'qiū kuí lǜ',
        type: 'green',
        name: '秋葵绿',
        hex: '#bace66',
    },
    {
        rgb: [
            128,
            128,
            64,
        ],
        phonic: 'qiū xiāng lǜ',
        type: 'green',
        name: '秋香绿',
        hex: '#808040',
    },
    {
        rgb: [
            143,
            138,
            108,
        ],
        phonic: 'sāng pí lǜ',
        type: 'green',
        name: '桑皮绿',
        hex: '#8f8a6c',
    },
    {
        rgb: [
            199,
            238,
            207,
        ],
        phonic: 'shā lǜ',
        type: 'green',
        name: '沙绿',
        hex: '#c7eecf',
    },
    {
        rgb: [
            51,
            49,
            24,
        ],
        phonic: 'shé dǎn lǜ',
        type: 'green',
        name: '蛇胆绿',
        hex: '#333118',
    },
    {
        rgb: [
            26,
            59,
            50,
        ],
        phonic: 'shēn hǎi lǜ',
        type: 'green',
        name: '深海绿',
        hex: '#1a3b32',
    },
    {
        rgb: [
            104,
            126,
            87,
        ],
        phonic: 'shí hú lǜ',
        type: 'green',
        name: '石斛绿',
        hex: '#687e57',
    },
    {
        rgb: [
            34,
            134,
            96,
        ],
        phonic: 'shí lǜ',
        type: 'green',
        name: '石绿',
        hex: '#228660',
    },
    {
        rgb: [
            161,
            212,
            155,
        ],
        phonic: 'shuǐ lǜ',
        type: 'green',
        name: '水绿',
        hex: '#a1d49b',
    },
    {
        rgb: [
            20,
            151,
            133,
        ],
        phonic: 'sōng lǜ',
        type: 'green',
        name: '松绿',
        hex: '#149785',
    },
    {
        rgb: [
            131,
            160,
            140,
        ],
        phonic: 'sōng shuāng lǜ',
        type: 'green',
        name: '松霜绿',
        hex: '#83a08c',
    },
    {
        rgb: [
            136,
            115,
            34,
        ],
        phonic: 'tái lǜ',
        type: 'green',
        name: '苔绿',
        hex: '#887322',
    },
    {
        rgb: [
            99,
            88,
            34,
        ],
        phonic: 'tán shuǐ lǜ',
        type: 'green',
        name: '潭水绿',
        hex: '#635822',
    },
    {
        rgb: [
            70,
            121,
            55,
        ],
        phonic: 'táng láng lǜ',
        type: 'green',
        name: '螳螂绿',
        hex: '#467937',
    },
    {
        rgb: [
            150,
            210,
            198,
        ],
        phonic: 'tiān shuǐ bì',
        type: 'green',
        name: '天水碧',
        hex: '#96d2c6',
    },
    {
        rgb: [
            94,
            102,
            91,
        ],
        phonic: 'tián luó lǜ',
        type: 'green',
        name: '田螺绿',
        hex: '#5e665b',
    },
    {
        rgb: [
            46,
            174,
            144,
        ],
        phonic: 'tóng lǜ',
        type: 'green',
        name: '铜绿',
        hex: '#2eae90',
    },
    {
        rgb: [
            149,
            179,
            50,
        ],
        phonic: 'wā lǜ',
        type: 'green',
        name: '蛙绿',
        hex: '#95b332',
    },
    {
        rgb: [
            118,
            131,
            110,
        ],
        phonic: 'wǎ sōng lǜ',
        type: 'green',
        name: '瓦松绿',
        hex: '#76836e',
    },
    {
        rgb: [
            116,
            208,
            73,
        ],
        phonic: 'wō jù lǜ',
        type: 'green',
        name: '莴苣绿',
        hex: '#74d049',
    },
    {
        rgb: [
            105,
            161,
            150,
        ],
        phonic: 'wú zhī lǜ',
        type: 'green',
        name: '梧枝绿',
        hex: '#69a196',
    },
    {
        rgb: [
            132,
            94,
            29,
        ],
        phonic: 'xī yì lǜ',
        type: 'green',
        name: '蜥蜴绿',
        hex: '#845e1d',
    },
    {
        rgb: [
            65,
            78,
            50,
        ],
        phonic: 'xián cài lǜ',
        type: 'green',
        name: '咸菜绿',
        hex: '#414e32',
    },
    {
        rgb: [
            208,
            210,
            21,
        ],
        phonic: 'xīn hé lǜ',
        type: 'green',
        name: '新禾绿',
        hex: '#d0d215',
    },
    {
        rgb: [
            179,
            224,
            1,
        ],
        phonic: 'xiù qiú lǜ',
        type: 'green',
        name: '绣球绿',
        hex: '#b3e001',
    },
    {
        rgb: [
            66,
            112,
            86,
        ],
        phonic: 'xiù lǜ',
        type: 'green',
        name: '锈绿',
        hex: '#427056',
    },
    {
        rgb: [
            100,
            140,
            87,
        ],
        phonic: 'yā lǜ',
        type: 'green',
        name: '鸭绿',
        hex: '#648c57',
    },
    {
        rgb: [
            150,
            195,
            78,
        ],
        phonic: 'yá lǜ',
        type: 'green',
        name: '芽绿',
        hex: '#96c34e',
    },
    {
        rgb: [
            116,
            176,
            52,
        ],
        phonic: 'yāng sè',
        type: 'green',
        name: '秧色',
        hex: '#74b034',
    },
    {
        rgb: [
            152,
            196,
            47,
        ],
        phonic: 'yīn lǜ',
        type: 'green',
        name: '茵绿',
        hex: '#98c42f',
    },
    {
        rgb: [
            83,
            155,
            107,
        ],
        phonic: 'yīng gē lǜ',
        type: 'green',
        name: '鹦哥绿',
        hex: '#539b6b',
    },
    {
        rgb: [
            97,
            153,
            66,
        ],
        phonic: 'yīng wǔ lǜ',
        type: 'green',
        name: '鹦鹉绿',
        hex: '#619942',
    },
    {
        rgb: [
            15,
            83,
            56,
        ],
        phonic: 'yóu lǜ',
        type: 'green',
        name: '油绿',
        hex: '#0f5338',
    },
    {
        rgb: [
            52,
            80,
            65,
        ],
        phonic: 'yǒu lǜ',
        type: 'green',
        name: '黝绿',
        hex: '#345041',
    },
    {
        rgb: [
            213,
            224,
            215,
        ],
        phonic: 'yù sè',
        type: 'green',
        name: '玉色',
        hex: '#d5e0d7',
    },
    {
        rgb: [
            66,
            179,
            73,
        ],
        phonic: 'yù suǐ lǜ',
        type: 'green',
        name: '玉髓绿',
        hex: '#42b349',
    },
    {
        rgb: [
            187,
            198,
            181,
        ],
        phonic: 'yù zān lǜ',
        type: 'green',
        name: '玉簪绿',
        hex: '#bbc6b5',
    },
    {
        rgb: [
            26,
            30,
            24,
        ],
        phonic: 'yún shān lǜ',
        type: 'green',
        name: '云杉绿',
        hex: '#1a1e18',
    },
    {
        rgb: [
            126,
            186,
            88,
        ],
        phonic: 'zǎo lǜ',
        type: 'green',
        name: '藻绿',
        hex: '#7eba58',
    },
    {
        rgb: [
            156,
            192,
            26,
        ],
        phonic: 'zuò cán lǜ',
        type: 'green',
        name: '柞蚕绿',
        hex: '#9cc01a',
    },
    {
        rgb: [
            113,
            159,
            1,
        ],
        phonic: 'zhī tiáo lǜ',
        type: 'green',
        name: '枝条绿',
        hex: '#719f01',
    },
    {
        rgb: [
            186,
            213,
            180,
        ],
        phonic: 'zhú huáng lǜ',
        type: 'green',
        name: '竹篁绿',
        hex: '#bad5b4',
    },
    {
        rgb: [
            129,
            192,
            77,
        ],
        phonic: 'zhú lǜ',
        type: 'green',
        name: '竹绿',
        hex: '#81c04d',
    },
    {
        rgb: [
            128,
            179,
            111,
        ],
        phonic: 'zhú qīng',
        type: 'green',
        name: '竹青',
        hex: '#80b36f',
    },
    {
        rgb: [
            90,
            141,
            72,
        ],
        phonic: 'zhú yè qīng',
        type: 'green',
        name: '竹叶青',
        hex: '#5a8d48',
    },
    {
        rgb: [
            143,
            170,
            117,
        ],
        phonic: 'zǐ shān lǜ',
        type: 'green',
        name: '紫杉绿',
        hex: '#8faa75',
    },
    {
        rgb: [
            90,
            73,
            19,
        ],
        phonic: 'zōng lǘ lǜ',
        type: 'green',
        name: '棕榈绿',
        hex: '#5a4913',
    },
    {
        rgb: [
            135,
            104,
            24,
        ],
        phonic: 'zōng yè lǜ',
        type: 'green',
        name: '棕叶绿',
        hex: '#876818',
    },
]
