export const purple = [
    {
        rgb: [
            36,
            32,
            67,
        ],
        phonic: 'àn lán zǐ',
        type: 'purple',
        name: '暗蓝紫',
        hex: '#242043',
    },
    {
        rgb: [
            53,
            49,
            72,
        ],
        phonic: 'àn lóng dǎn zǐ',
        type: 'purple',
        name: '暗龙胆紫',
        hex: '#353148',
    },
    {
        rgb: [
            93,
            34,
            36,
        ],
        phonic: 'àn yù zǐ',
        type: 'purple',
        name: '暗玉紫',
        hex: '#5d2224',
    },
    {
        rgb: [
            80,
            49,
            64,
        ],
        phonic: 'bí qí zǐ',
        type: 'purple',
        name: '荸荠紫',
        hex: '#503140',
    },
    {
        rgb: [
            152,
            92,
            143,
        ],
        phonic: 'biǎn dòu zǐ',
        type: 'purple',
        name: '扁豆紫',
        hex: '#985c8f',
    },
    {
        rgb: [
            126,
            84,
            120,
        ],
        phonic: 'bìng zǐ',
        type: 'purple',
        name: '并紫',
        hex: '#7e5478',
    },
    {
        rgb: [
            142,
            57,
            114,
        ],
        phonic: 'cài tóu zǐ',
        type: 'purple',
        name: '菜头紫',
        hex: '#8e3972',
    },
    {
        rgb: [
            189,
            178,
            195,
        ],
        phonic: 'cǎn zǐ',
        type: 'purple',
        name: '黪紫',
        hex: '#bdb2c3',
    },
    {
        rgb: [
            73,
            62,
            84,
        ],
        phonic: 'dài zǐ',
        type: 'purple',
        name: '黛紫',
        hex: '#493e54',
    },
    {
        rgb: [
            208,
            194,
            211,
        ],
        phonic: 'dàn qiān niú zǐ',
        type: 'purple',
        name: '淡牵牛紫',
        hex: '#d0c2d3',
    },
    {
        rgb: [
            175,
            153,
            191,
        ],
        phonic: 'dàn qīng lián',
        type: 'purple',
        name: '淡青莲',
        hex: '#af99bf',
    },
    {
        rgb: [
            223,
            200,
            210,
        ],
        phonic: 'dàn qīng zǐ',
        type: 'purple',
        name: '淡青紫',
        hex: '#dfc8d2',
    },
    {
        rgb: [
            175,
            161,
            222,
        ],
        phonic: 'dàn téng luó zǐ',
        type: 'purple',
        name: '淡藤萝紫',
        hex: '#afa1de',
    },
    {
        rgb: [
            70,
            68,
            79,
        ],
        phonic: 'diāo zǐ',
        type: 'purple',
        name: '貂紫',
        hex: '#46444f',
    },
    {
        rgb: [
            232,
            215,
            223,
        ],
        phonic: 'dīng xiāng dàn zǐ',
        type: 'purple',
        name: '丁香淡紫',
        hex: '#e8d7df',
    },
    {
        rgb: [
            99,
            82,
            130,
        ],
        phonic: 'dīng xiāng zǐ',
        type: 'purple',
        name: '丁香紫',
        hex: '#635282',
    },
    {
        rgb: [
            223,
            162,
            203,
        ],
        phonic: 'dòu kòu zǐ',
        type: 'purple',
        name: '豆蔻紫',
        hex: '#dfa2cb',
    },
    {
        rgb: [
            187,
            117,
            167,
        ],
        phonic: 'dòu zǐ',
        type: 'purple',
        name: '豆紫',
        hex: '#bb75a7',
    },
    {
        rgb: [
            163,
            133,
            186,
        ],
        phonic: 'fěn zǐ',
        type: 'purple',
        name: '粉紫',
        hex: '#a385ba',
    },
    {
        rgb: [
            201,
            173,
            196,
        ],
        phonic: 'fēng xìn zǐ',
        type: 'purple',
        name: '风信紫',
        hex: '#c9adc4',
    },
    {
        rgb: [
            73,
            39,
            53,
        ],
        phonic: 'gān zhè zǐ',
        type: 'purple',
        name: '甘蔗紫',
        hex: '#492735',
    },
    {
        rgb: [
            89,
            19,
            55,
        ],
        phonic: 'gàn zǐ',
        type: 'purple',
        name: '绀紫',
        hex: '#591337',
    },
    {
        rgb: [
            209,
            127,
            209,
        ],
        phonic: 'gě jīn zǐ',
        type: 'purple',
        name: '葛巾紫',
        hex: '#d17fd1',
    },
    {
        rgb: [
            116,
            93,
            103,
        ],
        phonic: 'gǔ tóng zǐ',
        type: 'purple',
        name: '古铜紫',
        hex: '#745d67',
    },
    {
        rgb: [
            49,
            16,
            27,
        ],
        phonic: 'hēi zǐ',
        type: 'purple',
        name: '黑紫',
        hex: '#31101b',
    },
    {
        rgb: [
            115,
            107,
            146,
        ],
        phonic: 'huī zǐ',
        type: 'purple',
        name: '灰紫',
        hex: '#736b92',
    },
    {
        rgb: [
            128,
            24,
            71,
        ],
        phonic: 'jī guān zǐ',
        type: 'purple',
        name: '鸡冠紫',
        hex: '#801847',
    },
    {
        rgb: [
            89,
            19,
            55,
        ],
        phonic: 'jī zǐ',
        type: 'purple',
        name: '缉紫',
        hex: '#591337',
    },
    {
        rgb: [
            164,
            88,
            210,
        ],
        phonic: 'qié huā',
        type: 'purple',
        name: '茄花',
        hex: '#a458d2',
    },
    {
        rgb: [
            47,
            12,
            44,
        ],
        phonic: 'qié pí zǐ',
        type: 'purple',
        name: '茄皮紫',
        hex: '#2f0c2c',
    },
    {
        rgb: [
            105,
            48,
            119,
        ],
        phonic: 'qié sè',
        type: 'purple',
        name: '茄色',
        hex: '#693077',
    },
    {
        rgb: [
            87,
            79,
            90,
        ],
        phonic: 'jiàn fēng zǐ',
        type: 'purple',
        name: '剑锋紫',
        hex: '#574f5a',
    },
    {
        rgb: [
            99,
            35,
            62,
        ],
        phonic: 'jiàng zǐ',
        type: 'purple',
        name: '绛紫',
        hex: '#63233e',
    },
    {
        rgb: [
            150,
            127,
            244,
        ],
        phonic: 'jiè huā zǐ',
        type: 'purple',
        name: '芥花紫',
        hex: '#967ff4',
    },
    {
        rgb: [
            80,
            10,
            21,
        ],
        phonic: 'jīn yú zǐ',
        type: 'purple',
        name: '金鱼紫',
        hex: '#500a15',
    },
    {
        rgb: [
            128,
            109,
            155,
        ],
        phonic: 'jǐn zǐ',
        type: 'purple',
        name: '槿紫',
        hex: '#806d9b',
    },
    {
        rgb: [
            250,
            122,
            197,
        ],
        phonic: 'jīng zǐ',
        type: 'purple',
        name: '荆紫',
        hex: '#fa7ac5',
    },
    {
        rgb: [
            40,
            41,
            85,
        ],
        phonic: 'jīng shí zǐ',
        type: 'purple',
        name: '晶石紫',
        hex: '#282955',
    },
    {
        rgb: [
            135,
            116,
            245,
        ],
        phonic: 'jié gěng zǐ',
        type: 'purple',
        name: '桔梗紫',
        hex: '#8774f5',
    },
    {
        rgb: [
            69,
            46,
            88,
        ],
        phonic: 'lǐ zǐ',
        type: 'purple',
        name: '李紫',
        hex: '#452e58',
    },
    {
        rgb: [
            90,
            26,
            27,
        ],
        phonic: 'lì zǐ',
        type: 'purple',
        name: '栗紫',
        hex: '#5a1a1b',
    },
    {
        rgb: [
            97,
            62,
            84,
        ],
        phonic: 'lóng jīng yú zǐ',
        type: 'purple',
        name: '龙睛鱼紫',
        hex: '#613e54',
    },
    {
        rgb: [
            49,
            47,
            50,
        ],
        phonic: 'lóng kuí zǐ',
        type: 'purple',
        name: '龙葵紫',
        hex: '#312f32',
    },
    {
        rgb: [
            49,
            22,
            29,
        ],
        phonic: 'luǎn shí zǐ',
        type: 'purple',
        name: '卵石紫',
        hex: '#31161d',
    },
    {
        rgb: [
            200,
            138,
            224,
        ],
        phonic: 'luó lán zǐ',
        type: 'purple',
        name: '罗兰紫',
        hex: '#c88ae0',
    },
    {
        rgb: [
            115,
            117,
            155,
        ],
        phonic: 'luó diàn zǐ',
        type: 'purple',
        name: '螺甸紫',
        hex: '#73759b',
    },
    {
        rgb: [
            206,
            134,
            227,
        ],
        phonic: 'mǎ biān cǎo zǐ',
        type: 'purple',
        name: '马鞭草紫',
        hex: '#ce86e3',
    },
    {
        rgb: [
            46,
            50,
            124,
        ],
        phonic: 'mǎn tiān xīng zǐ',
        type: 'purple',
        name: '满天星紫',
        hex: '#2e327c',
    },
    {
        rgb: [
            148,
            115,
            176,
        ],
        phonic: 'méi guī zǐ',
        type: 'purple',
        name: '玫瑰紫',
        hex: '#9473b0',
    },
    {
        rgb: [
            86,
            63,
            71,
        ],
        phonic: 'mó shí zǐ',
        type: 'purple',
        name: '磨石紫',
        hex: '#563f47',
    },
    {
        rgb: [
            33,
            7,
            42,
        ],
        phonic: 'mò zǐ',
        type: 'purple',
        name: '墨紫',
        hex: '#21072a',
    },
    {
        rgb: [
            142,
            149,
            214,
        ],
        phonic: 'mù shān zǐ',
        type: 'purple',
        name: '暮山紫',
        hex: '#8e95d6',
    },
    {
        rgb: [
            170,
            140,
            138,
        ],
        phonic: 'ǒu hé',
        type: 'purple',
        name: '藕合',
        hex: '#aa8c8a',
    },
    {
        rgb: [
            64,
            27,
            61,
        ],
        phonic: 'pú táo jiàng zǐ',
        type: 'purple',
        name: '葡萄酱紫',
        hex: '#401b3d',
    },
    {
        rgb: [
            102,
            75,
            93,
        ],
        phonic: 'pú táo qīng',
        type: 'purple',
        name: '葡萄青',
        hex: '#664b5d',
    },
    {
        rgb: [
            88,
            29,
            73,
        ],
        phonic: 'pú táo zǐ',
        type: 'purple',
        name: '葡萄紫',
        hex: '#581d49',
    },
    {
        rgb: [
            127,
            4,
            128,
        ],
        phonic: 'qiān niú zǐ',
        type: 'purple',
        name: '牵牛紫',
        hex: '#7f0480',
    },
    {
        rgb: [
            220,
            200,
            253,
        ],
        phonic: 'qiǎn téng zǐ',
        type: 'purple',
        name: '浅藤紫',
        hex: '#dcc8fd',
    },
    {
        rgb: [
            208,
            152,
            189,
        ],
        phonic: 'qīng há ké zǐ',
        type: 'purple',
        name: '青蛤壳紫',
        hex: '#d098bd',
    },
    {
        rgb: [
            149,
            131,
            205,
        ],
        phonic: 'qīng lián',
        type: 'purple',
        name: '青莲',
        hex: '#9583cd',
    },
    {
        rgb: [
            149,
            131,
            205,
        ],
        phonic: 'qīng lián sè',
        type: 'purple',
        name: '青莲色',
        hex: '#9583cd',
    },
    {
        rgb: [
            147,
            46,
            122,
        ],
        phonic: 'qīng lián zǐ',
        type: 'purple',
        name: '青莲紫',
        hex: '#932e7a',
    },
    {
        rgb: [
            96,
            81,
            192,
        ],
        phonic: 'shān gěng zǐ',
        type: 'purple',
        name: '山梗紫',
        hex: '#6051c0',
    },
    {
        rgb: [
            162,
            90,
            164,
        ],
        phonic: 'shān qié zǐ',
        type: 'purple',
        name: '山茄紫',
        hex: '#a25aa4',
    },
    {
        rgb: [
            47,
            22,
            44,
        ],
        phonic: 'shēn qiān niú zǐ',
        type: 'purple',
        name: '深牵牛紫',
        hex: '#2f162c',
    },
    {
        rgb: [
            66,
            16,
            41,
        ],
        phonic: 'shèn zhī zǐ',
        type: 'purple',
        name: '椹汁紫',
        hex: '#421029',
    },
    {
        rgb: [
            200,
            157,
            213,
        ],
        phonic: 'shí zhú zǐ',
        type: 'purple',
        name: '石竹紫',
        hex: '#c89dd5',
    },
    {
        rgb: [
            104,
            83,
            114,
        ],
        phonic: 'sū mù zǐ',
        type: 'purple',
        name: '苏木紫',
        hex: '#685372',
    },
    {
        rgb: [
            92,
            72,
            81,
        ],
        phonic: 'tán zǐ',
        type: 'purple',
        name: '檀紫',
        hex: '#5c4851',
    },
    {
        rgb: [
            126,
            122,
            188,
        ],
        phonic: 'téng luó zǐ',
        type: 'purple',
        name: '藤萝紫',
        hex: '#7e7abc',
    },
    {
        rgb: [
            125,
            22,
            111,
        ],
        phonic: 'wèi zǐ',
        type: 'purple',
        name: '魏紫',
        hex: '#7d166f',
    },
    {
        rgb: [
            39,
            21,
            43,
        ],
        phonic: 'wū méi zǐ',
        type: 'purple',
        name: '乌梅紫',
        hex: '#27152b',
    },
    {
        rgb: [
            214,
            193,
            198,
        ],
        phonic: 'xiā sè',
        type: 'purple',
        name: '虾色',
        hex: '#d6c1c6',
    },
    {
        rgb: [
            150,
            38,
            110,
        ],
        phonic: 'xiàn cài zǐ',
        type: 'purple',
        name: '苋菜紫',
        hex: '#96266e',
    },
    {
        rgb: [
            134,
            101,
            132,
        ],
        phonic: 'xuě zǐ',
        type: 'purple',
        name: '雪紫',
        hex: '#866584',
    },
    {
        rgb: [
            134,
            96,
            155,
        ],
        phonic: 'xùn zǐ',
        type: 'purple',
        name: '蕈紫',
        hex: '#86609b',
    },
    {
        rgb: [
            135,
            13,
            95,
        ],
        phonic: 'yān lóng zǐ',
        type: 'purple',
        name: '烟笼紫',
        hex: '#870d5f',
    },
    {
        rgb: [
            196,
            98,
            137,
        ],
        phonic: 'yáng cōng zǐ',
        type: 'purple',
        name: '洋葱紫',
        hex: '#c46289',
    },
    {
        rgb: [
            205,
            177,
            192,
        ],
        phonic: 'yě huā',
        type: 'purple',
        name: '野花',
        hex: '#cdb1c0',
    },
    {
        rgb: [
            127,
            104,
            195,
        ],
        phonic: 'yě jú zǐ',
        type: 'purple',
        name: '野菊紫',
        hex: '#7f68c3',
    },
    {
        rgb: [
            58,
            58,
            86,
        ],
        phonic: 'yě pú táo zǐ',
        type: 'purple',
        name: '野葡萄紫',
        hex: '#3a3a56',
    },
    {
        rgb: [
            164,
            103,
            196,
        ],
        phonic: 'yīng cǎo zǐ',
        type: 'purple',
        name: '樱草紫',
        hex: '#a467c4',
    },
    {
        rgb: [
            120,
            95,
            116,
        ],
        phonic: 'yóu zǐ',
        type: 'purple',
        name: '油紫',
        hex: '#785f74',
    },
    {
        rgb: [
            108,
            76,
            123,
        ],
        phonic: 'yù zǐ',
        type: 'purple',
        name: '芋紫',
        hex: '#6c4c7b',
    },
    {
        rgb: [
            154,
            115,
            144,
        ],
        phonic: 'yuān yāng zǐ',
        type: 'purple',
        name: '鸳鸯紫',
        hex: '#9a7390',
    },
    {
        rgb: [
            200,
            185,
            250,
        ],
        phonic: 'yuǎn shān zǐ',
        type: 'purple',
        name: '远山紫',
        hex: '#c8b9fa',
    },
    {
        rgb: [
            202,
            175,
            192,
        ],
        phonic: 'zhī lán zǐ',
        type: 'purple',
        name: '芝兰紫',
        hex: '#caafc0',
    },
    {
        rgb: [
            84,
            41,
            48,
        ],
        phonic: 'zhū gān zǐ',
        type: 'purple',
        name: '猪肝紫',
        hex: '#542930',
    },
    {
        rgb: [
            207,
            172,
            194,
        ],
        phonic: 'zǐ fěn',
        type: 'purple',
        name: '紫粉',
        hex: '#cfacc2',
    },
    {
        rgb: [
            72,
            50,
            58,
        ],
        phonic: 'zǐ jiàng',
        type: 'purple',
        name: '紫绛',
        hex: '#48323a',
    },
    {
        rgb: [
            32,
            10,
            46,
        ],
        phonic: 'zǐ mò',
        type: 'purple',
        name: '紫墨',
        hex: '#200a2e',
    },
    {
        rgb: [
            168,
            107,
            141,
        ],
        phonic: 'zǐ shàn bèi',
        type: 'purple',
        name: '紫扇贝',
        hex: '#a86b8d',
    },
    {
        rgb: [
            149,
            106,
            186,
        ],
        phonic: 'zǐ shuǐ jīng',
        type: 'purple',
        name: '紫水晶',
        hex: '#956aba',
    },
    {
        rgb: [
            159,
            154,
            208,
        ],
        phonic: 'zǐ téng huī',
        type: 'purple',
        name: '紫藤灰',
        hex: '#9f9ad0',
    },
    {
        rgb: [
            181,
            143,
            218,
        ],
        phonic: 'zǐ wēi huā',
        type: 'purple',
        name: '紫薇花',
        hex: '#b58fda',
    },
]
