export const blue = [
    {
        rgb: [
            49,
            112,
            166,
        ],
        phonic: 'ananlan',
        type: 'blue',
        name: '安安蓝',
        hex: '#3170a6',
    },
    {
        rgb: [
            16,
            32,
            48,
        ],
        phonic: 'anlan',
        type: 'blue',
        name: '暗蓝',
        hex: '#102030',
    },
    {
        rgb: [
            57,
            70,
            175,
        ],
        phonic: 'baolan',
        type: 'blue',
        name: '宝蓝',
        hex: '#3946af',
    },
    {
        rgb: [
            147,
            183,
            177,
        ],
        phonic: 'biqinglan',
        type: 'blue',
        name: '碧青',
        hex: '#93b7b1',
    },
    {
        rgb: [
            173,
            216,
            251,
        ],
        phonic: 'bingshanlan',
        type: 'blue',
        name: '冰山蓝',
        hex: '#add8fb',
    },
    {
        rgb: [
            32,
            41,
            84,
        ],
        phonic: 'binglan',
        type: 'blue',
        name: '并蓝',
        hex: '#202954',
    },
    {
        rgb: [
            19,
            71,
            93,
        ],
        phonic: 'canglan',
        type: 'blue',
        name: '苍蓝',
        hex: '#13475d',
    },
    {
        rgb: [
            37,
            40,
            49,
        ],
        phonic: 'zangheilan',
        type: 'blue',
        name: '藏黑蓝',
        hex: '#252831',
    },
    {
        rgb: [
            12,
            5,
            47,
        ],
        phonic: 'zanglan',
        type: 'blue',
        name: '藏蓝',
        hex: '#0c052f',
    },
    {
        rgb: [
            45,
            49,
            61,
        ],
        phonic: 'zangqinglan',
        type: 'blue',
        name: '藏青',
        hex: '#2d313d',
    },
    {
        rgb: [
            5,
            80,
            231,
        ],
        phonic: 'caohualan',
        type: 'blue',
        name: '草花蓝',
        hex: '#0550e7',
    },
    {
        rgb: [
            16,
            28,
            52,
        ],
        phonic: 'zengqinglan',
        type: 'blue',
        name: '曾青',
        hex: '#101c34',
    },
    {
        rgb: [
            158,
            178,
            189,
        ],
        phonic: 'chunlan',
        type: 'blue',
        name: '春蓝',
        hex: '#9eb2bd',
    },
    {
        rgb: [
            61,
            206,
            253,
        ],
        phonic: 'cuilan',
        type: 'blue',
        name: '翠蓝',
        hex: '#3dcefd',
    },
    {
        rgb: [
            48,
            71,
            87,
        ],
        phonic: 'dailan',
        type: 'blue',
        name: '黛蓝',
        hex: '#304757',
    },
    {
        rgb: [
            27,
            31,
            60,
        ],
        phonic: 'daiqinglan',
        type: 'blue',
        name: '黛青',
        hex: '#1b1f3c',
    },
    {
        rgb: [
            41,
            125,
            212,
        ],
        phonic: 'danfanlan',
        type: 'blue',
        name: '胆矾蓝',
        hex: '#297dd4',
    },
    {
        rgb: [
            195,
            214,
            212,
        ],
        phonic: 'danqinglan',
        type: 'blue',
        name: '蛋青',
        hex: '#c3d6d4',
    },
    {
        rgb: [
            15,
            174,
            195,
        ],
        phonic: 'dianzilan',
        type: 'blue',
        name: '甸子蓝',
        hex: '#0faec3',
    },
    {
        rgb: [
            19,
            23,
            34,
        ],
        phonic: 'dianqinglan',
        type: 'blue',
        name: '靛青',
        hex: '#131722',
    },
    {
        rgb: [
            79,
            125,
            161,
        ],
        phonic: 'diechilan',
        type: 'blue',
        name: '蝶翅蓝',
        hex: '#4f7da1',
    },
    {
        rgb: [
            17,
            94,
            172,
        ],
        phonic: 'feiyancaolan',
        type: 'blue',
        name: '飞燕草蓝',
        hex: '#115eac',
    },
    {
        rgb: [
            178,
            208,
            219,
        ],
        phonic: 'fenqinglan',
        type: 'blue',
        name: '粉青',
        hex: '#b2d0db',
    },
    {
        rgb: [
            16,
            22,
            54,
        ],
        phonic: 'foqinglan',
        type: 'blue',
        name: '佛青',
        hex: '#101636',
    },
    {
        rgb: [
            14,
            20,
            34,
        ],
        phonic: 'ganglan',
        type: 'blue',
        name: '钢蓝',
        hex: '#0e1422',
    },
    {
        rgb: [
            20,
            36,
            52,
        ],
        phonic: 'gangqinglan',
        type: 'blue',
        name: '钢青',
        hex: '#142434',
    },
    {
        rgb: [
            28,
            41,
            57,
        ],
        phonic: 'gelan',
        type: 'blue',
        name: '鸽蓝',
        hex: '#1c2939',
    },
    {
        rgb: [
            40,
            67,
            122,
        ],
        phonic: 'haichanglan',
        type: 'blue',
        name: '海昌蓝',
        hex: '#28437a',
    },
    {
        rgb: [
            23,
            79,
            126,
        ],
        phonic: 'hailan',
        type: 'blue',
        name: '海蓝',
        hex: '#174f7e',
    },
    {
        rgb: [
            4,
            57,
            72,
        ],
        phonic: 'haiqinglan',
        type: 'blue',
        name: '海青',
        hex: '#043948',
    },
    {
        rgb: [
            21,
            86,
            154,
        ],
        phonic: 'haitaolan',
        type: 'blue',
        name: '海涛蓝',
        hex: '#15569a',
    },
    {
        rgb: [
            199,
            230,
            232,
        ],
        phonic: 'haitianlan',
        type: 'blue',
        name: '海天蓝',
        hex: '#c7e6e8',
    },
    {
        rgb: [
            34,
            119,
            184,
        ],
        phonic: 'honglan',
        type: 'blue',
        name: '虹蓝',
        hex: '#2277b8',
    },
    {
        rgb: [
            22,
            163,
            209,
        ],
        phonic: 'hulan',
        type: 'blue',
        name: '湖蓝',
        hex: '#16a3d1',
    },
    {
        rgb: [
            4,
            18,
            53,
        ],
        phonic: 'huaqinglan',
        type: 'blue',
        name: '花青',
        hex: '#041235',
    },
    {
        rgb: [
            62,
            94,
            134,
        ],
        phonic: 'huilan',
        type: 'blue',
        name: '灰蓝',
        hex: '#3e5e86',
    },
    {
        rgb: [
            26,
            35,
            74,
        ],
        phonic: 'jiqinglan',
        type: 'blue',
        name: '霁青',
        hex: '#1a234a',
    },
    {
        rgb: [
            20,
            144,
            168,
        ],
        phonic: 'jianniaolan',
        type: 'blue',
        name: '樫鸟蓝',
        hex: '#1490a8',
    },
    {
        rgb: [
            103,
            169,
            201,
        ],
        phonic: 'jianshilan',
        type: 'blue',
        name: '涧石蓝',
        hex: '#67a9c9',
    },
    {
        rgb: [
            140,
            155,
            184,
        ],
        phonic: 'jiaoqinglan',
        type: 'blue',
        name: '鲛青',
        hex: '#8c9bb8',
    },
    {
        rgb: [
            47,
            52,
            107,
        ],
        phonic: 'jinglan',
        type: 'blue',
        name: '京蓝',
        hex: '#2f346b',
    },
    {
        rgb: [
            41,
            65,
            103,
        ],
        phonic: 'jingqinglan',
        type: 'blue',
        name: '京青',
        hex: '#294167',
    },
    {
        rgb: [
            187,
            214,
            225,
        ],
        phonic: 'jingtianlan',
        type: 'blue',
        name: '井天蓝',
        hex: '#bbd6e1',
    },
    {
        rgb: [
            97,
            178,
            221,
        ],
        phonic: 'jingtailan',
        type: 'blue',
        name: '景泰蓝',
        hex: '#61b2dd',
    },
    {
        rgb: [
            59,
            99,
            101,
        ],
        phonic: 'juqinglan',
        type: 'blue',
        name: '醵青',
        hex: '#3b6365',
    },
    {
        rgb: [
            14,
            176,
            201,
        ],
        phonic: 'kongquelan',
        type: 'blue',
        name: '孔雀蓝',
        hex: '#0eb0c9',
    },
    {
        rgb: [
            41,
            66,
            150,
        ],
        phonic: 'kuquelan',
        type: 'blue',
        name: '苦鹊蓝',
        hex: '#294296',
    },
    {
        rgb: [
            19,
            59,
            94,
        ],
        phonic: 'maolan',
        type: 'blue',
        name: '毛蓝',
        hex: '#133b5e',
    },
    {
        rgb: [
            5,
            21,
            53,
        ],
        phonic: 'maoqinglan',
        type: 'blue',
        name: '毛青',
        hex: '#051535',
    },
    {
        rgb: [
            47,
            122,
            161,
        ],
        phonic: 'maoyuelan',
        type: 'blue',
        name: '毛月',
        hex: '#2f7aa1',
    },
    {
        rgb: [
            29,
            51,
            75,
        ],
        phonic: 'menqinglan',
        type: 'blue',
        name: '扪青',
        hex: '#1d334b',
    },
    {
        rgb: [
            47,
            64,
            71,
        ],
        phonic: 'moqinglan',
        type: 'blue',
        name: '墨青',
        hex: '#2f4047',
    },
    {
        rgb: [
            43,
            113,
            173,
        ],
        phonic: 'pinlan',
        type: 'blue',
        name: '品蓝',
        hex: '#2b71ad',
    },
    {
        rgb: [
            122,
            171,
            229,
        ],
        phonic: 'pinyuelan',
        type: 'blue',
        name: '品月',
        hex: '#7aabe5',
    },
    {
        rgb: [
            1,
            73,
            121,
        ],
        phonic: 'pulan',
        type: 'blue',
        name: '蒲蓝',
        hex: '#014979',
    },
    {
        rgb: [
            0,
            49,
            82,
        ],
        phonic: 'puqinglan',
        type: 'blue',
        name: '蒲青',
        hex: '#003152',
    },
    {
        rgb: [
            80,
            196,
            211,
        ],
        phonic: 'pubulan',
        type: 'blue',
        name: '瀑布蓝',
        hex: '#50c4d3',
    },
    {
        rgb: [
            55,
            109,
            181,
        ],
        phonic: 'qianniuhualan',
        type: 'blue',
        name: '牵牛花蓝',
        hex: '#376db5',
    },
    {
        rgb: [
            146,
            174,
            214,
        ],
        phonic: 'qielan',
        type: 'blue',
        name: '窃蓝',
        hex: '#92aed6',
    },
    {
        rgb: [
            31,
            39,
            124,
        ],
        phonic: 'qingjinlan',
        type: 'blue',
        name: '青金',
        hex: '#1f277c',
    },
    {
        rgb: [
            176,
            213,
            222,
        ],
        phonic: 'qingshuilan',
        type: 'blue',
        name: '清水蓝',
        hex: '#b0d5de',
    },
    {
        rgb: [
            16,
            167,
            232,
        ],
        phonic: 'qingtinglan',
        type: 'blue',
        name: '蜻蜓蓝',
        hex: '#10a7e8',
    },
    {
        rgb: [
            87,
            151,
            195,
        ],
        phonic: 'qinglan',
        type: 'blue',
        name: '晴蓝',
        hex: '#5797c3',
    },
    {
        rgb: [
            76,
            135,
            177,
        ],
        phonic: 'qingshanlan',
        type: 'blue',
        name: '晴山蓝',
        hex: '#4c87b1',
    },
    {
        rgb: [
            138,
            189,
            210,
        ],
        phonic: 'qiubolan',
        type: 'blue',
        name: '秋波蓝',
        hex: '#8abdd2',
    },
    {
        rgb: [
            4,
            35,
            53,
        ],
        phonic: 'quetoulan',
        type: 'blue',
        name: '雀头蓝',
        hex: '#042335',
    },
    {
        rgb: [
            41,
            76,
            231,
        ],
        phonic: 'quetouqinglan',
        type: 'blue',
        name: '雀头青',
        hex: '#294ce7',
    },
    {
        rgb: [
            64,
            78,
            143,
        ],
        phonic: 'quelan',
        type: 'blue',
        name: '鹊蓝',
        hex: '#404e8f',
    },
    {
        rgb: [
            47,
            94,
            146,
        ],
        phonic: 'ronglan',
        type: 'blue',
        name: '绒蓝',
        hex: '#2f5e92',
    },
    {
        rgb: [
            60,
            65,
            123,
        ],
        phonic: 'shaqinglan',
        type: 'blue',
        name: '沙青',
        hex: '#3c417b',
    },
    {
        rgb: [
            123,
            170,
            176,
        ],
        phonic: 'shanlan',
        type: 'blue',
        name: '闪蓝',
        hex: '#7baab0',
    },
    {
        rgb: [
            27,
            37,
            90,
        ],
        phonic: 'shiqinglan',
        type: 'blue',
        name: '石青',
        hex: '#1b255a',
    },
    {
        rgb: [
            4,
            163,
            218,
        ],
        phonic: 'shiruilan',
        type: 'blue',
        name: '石蕊蓝',
        hex: '#04a3da',
    },
    {
        rgb: [
            3,
            34,
            88,
        ],
        phonic: 'shuanglan',
        type: 'blue',
        name: '双蓝',
        hex: '#032258',
    },
    {
        rgb: [
            23,
            184,
            253,
        ],
        phonic: 'tianlan',
        type: 'blue',
        name: '天蓝',
        hex: '#17b8fd',
    },
    {
        rgb: [
            148,
            176,
            198,
        ],
        phonic: 'tianqinglan',
        type: 'blue',
        name: '天青',
        hex: '#94b0c6',
    },
    {
        rgb: [
            92,
            119,
            166,
        ],
        phonic: 'tulan',
        type: 'blue',
        name: '土蓝',
        hex: '#5c77a6',
    },
    {
        rgb: [
            101,
            142,
            148,
        ],
        phonic: 'wanbolan',
        type: 'blue',
        name: '晚波蓝',
        hex: '#658e94',
    },
    {
        rgb: [
            42,
            104,
            188,
        ],
        phonic: 'weilan',
        type: 'blue',
        name: '蔚蓝',
        hex: '#2a68bc',
    },
    {
        rgb: [
            124,
            144,
            159,
        ],
        phonic: 'xiaqinglan',
        type: 'blue',
        name: '虾青',
        hex: '#7c909f',
    },
    {
        rgb: [
            62,
            95,
            148,
        ],
        phonic: 'xiaolan',
        type: 'blue',
        name: '霄蓝',
        hex: '#3e5f94',
    },
    {
        rgb: [
            147,
            180,
            247,
        ],
        phonic: 'xinglan',
        type: 'blue',
        name: '星蓝',
        hex: '#93b4f7',
    },
    {
        rgb: [
            44,
            48,
            73,
        ],
        phonic: 'xuanqinglan',
        type: 'blue',
        name: '玄青',
        hex: '#2c3049',
    },
    {
        rgb: [
            164,
            188,
            174,
        ],
        phonic: 'yadanqinglan',
        type: 'blue',
        name: '鸭蛋青',
        hex: '#a4bcae',
    },
    {
        rgb: [
            70,
            103,
            231,
        ],
        phonic: 'yazhicaolan',
        type: 'blue',
        name: '鸭跖草蓝',
        hex: '#4667e7',
    },
    {
        rgb: [
            4,
            85,
            203,
        ],
        phonic: 'yanlan',
        type: 'blue',
        name: '焰蓝',
        hex: '#0455cb',
    },
    {
        rgb: [
            20,
            24,
            36,
        ],
        phonic: 'yanhanlan',
        type: 'blue',
        name: '燕颔蓝',
        hex: '#141824',
    },
    {
        rgb: [
            30,
            34,
            51,
        ],
        phonic: 'yanweiqinglan',
        type: 'blue',
        name: '燕尾青',
        hex: '#1e2233',
    },
    {
        rgb: [
            47,
            130,
            174,
        ],
        phonic: 'yanlan',
        type: 'blue',
        name: '鷃蓝',
        hex: '#2f82ae',
    },
    {
        rgb: [
            3,
            165,
            248,
        ],
        phonic: 'yingguanglan',
        type: 'blue',
        name: '荧光蓝',
        hex: '#03a5f8',
    },
    {
        rgb: [
            161,
            183,
            194,
        ],
        phonic: 'yingqinglan',
        type: 'blue',
        name: '影青',
        hex: '#a1b7c2',
    },
    {
        rgb: [
            23,
            129,
            181,
        ],
        phonic: 'youlan',
        type: 'blue',
        name: '釉蓝',
        hex: '#1781b5',
    },
    {
        rgb: [
            97,
            155,
            195,
        ],
        phonic: 'yushandoulan',
        type: 'blue',
        name: '羽扇豆蓝',
        hex: '#619bc3',
    },
    {
        rgb: [
            145,
            198,
            202,
        ],
        phonic: 'yuguotianqinglan',
        type: 'blue',
        name: '雨过天青',
        hex: '#91c6ca',
    },
    {
        rgb: [
            18,
            110,
            131,
        ],
        phonic: 'yuchailan',
        type: 'blue',
        name: '玉钗蓝',
        hex: '#126e83',
    },
    {
        rgb: [
            56,
            77,
            244,
        ],
        phonic: 'yushilan',
        type: 'blue',
        name: '玉石蓝',
        hex: '#384df4',
    },
    {
        rgb: [
            156,
            183,
            252,
        ],
        phonic: 'yuanweilan',
        type: 'blue',
        name: '鸢尾蓝',
        hex: '#9cb7fc',
    },
    {
        rgb: [
            207,
            223,
            238,
        ],
        phonic: 'yuantianlan',
        type: 'blue',
        name: '远天蓝',
        hex: '#cfdfee',
    },
    {
        rgb: [
            201,
            215,
            227,
        ],
        phonic: 'yuebailan',
        type: 'blue',
        name: '月白',
        hex: '#c9d7e3',
    },
    {
        rgb: [
            124,
            195,
            251,
        ],
        phonic: 'yuelan',
        type: 'blue',
        name: '月蓝',
        hex: '#7cc3fb',
    },
    {
        rgb: [
            47,
            144,
            186,
        ],
        phonic: 'yunshanlan',
        type: 'blue',
        name: '云山蓝',
        hex: '#2f90ba',
    },
    {
        rgb: [
            157,
            188,
            209,
        ],
        phonic: 'yunshuilan',
        type: 'blue',
        name: '云水蓝',
        hex: '#9dbcd1',
    },
    {
        rgb: [
            41,
            59,
            81,
        ],
        phonic: 'zhenqinglan',
        type: 'blue',
        name: '真青',
        hex: '#293b51',
    },
    {
        rgb: [
            89,
            172,
            207,
        ],
        phonic: 'zhuyuelan',
        type: 'blue',
        name: '竹月',
        hex: '#59accf',
    },
]
