export const bwg = [
    {
        rgb: [
            127,
            126,
            132,
        ],
        phonic: 'anzhuanhui',
        type: 'bwg',
        name: '暗砖灰',
        hex: '#7f7e84',
    },
    {
        rgb: [
            86,
            86,
            86,
        ],
        phonic: 'baicaoshuang',
        type: 'bwg',
        name: '百草霜',
        hex: '#565656',
    },
    {
        rgb: [
            168,
            167,
            162,
        ],
        phonic: 'banjiuhui',
        type: 'bwg',
        name: '斑鸠灰',
        hex: '#a8a7a2',
    },
    {
        rgb: [
            215,
            207,
            194,
        ],
        phonic: 'bangroubai',
        type: 'bwg',
        name: '蚌肉白',
        hex: '#d7cfc2',
    },
    {
        rgb: [
            113,
            113,
            123,
        ],
        phonic: 'binghui',
        type: 'bwg',
        name: '并灰',
        hex: '#71717b',
    },
    {
        rgb: [
            196,
            199,
            204,
        ],
        phonic: 'caihui',
        type: 'bwg',
        name: '菜灰',
        hex: '#c4c7cc',
    },
    {
        rgb: [
            220,
            220,
            210,
        ],
        phonic: 'caobai',
        type: 'bwg',
        name: '草白',
        hex: '#dcdcd2',
    },
    {
        rgb: [
            182,
            164,
            118,
        ],
        phonic: 'chenhui',
        type: 'bwg',
        name: '尘灰',
        hex: '#b6a476',
    },
    {
        rgb: [
            132,
            125,
            132,
        ],
        phonic: 'chunhui',
        type: 'bwg',
        name: '鹑灰',
        hex: '#847d84',
    },
    {
        rgb: [
            195,
            203,
            206,
        ],
        phonic: 'dalishi',
        type: 'bwg',
        name: '大理石',
        hex: '#c3cbce',
    },
    {
        rgb: [
            157,
            174,
            182,
        ],
        phonic: 'danlanhui',
        type: 'bwg',
        name: '淡蓝灰',
        hex: '#9daeb6',
    },
    {
        rgb: [
            189,
            194,
            188,
        ],
        phonic: 'danlvhui',
        type: 'bwg',
        name: '淡绿灰',
        hex: '#bdc2bc',
    },
    {
        rgb: [
            184,
            148,
            132,
        ],
        phonic: 'danmeiguihui',
        type: 'bwg',
        name: '淡玫瑰灰',
        hex: '#b89484',
    },
    {
        rgb: [
            77,
            64,
            48,
        ],
        phonic: 'dansongyan',
        type: 'bwg',
        name: '淡松烟',
        hex: '#4d4030',
    },
    {
        rgb: [
            158,
            156,
            157,
        ],
        phonic: 'dantiehui',
        type: 'bwg',
        name: '淡铁灰',
        hex: '#9e9c9d',
    },
    {
        rgb: [
            194,
            178,
            163,
        ],
        phonic: 'danyinhui',
        type: 'bwg',
        name: '淡银灰',
        hex: '#c2b2a3',
    },
    {
        rgb: [
            38,
            45,
            50,
        ],
        phonic: 'dengcaohui',
        type: 'bwg',
        name: '灯草灰',
        hex: '#262d32',
    },
    {
        rgb: [
            233,
            240,
            246,
        ],
        phonic: 'dongfangliang',
        type: 'bwg',
        name: '东方亮',
        hex: '#e9f0f6',
    },
    {
        rgb: [
            186,
            188,
            185,
        ],
        phonic: 'ehui',
        type: 'bwg',
        name: '垩灰',
        hex: '#babcb9',
    },
    {
        rgb: [
            251,
            242,
            227,
        ],
        phonic: 'fenbai',
        type: 'bwg',
        name: '粉白',
        hex: '#fbf2e3',
    },
    {
        rgb: [
            80,
            62,
            42,
        ],
        phonic: 'ganlanhui',
        type: 'bwg',
        name: '橄榄灰',
        hex: '#503e2a',
    },
    {
        rgb: [
            138,
            140,
            165,
        ],
        phonic: 'ganlanshihui',
        type: 'bwg',
        name: '橄榄石灰',
        hex: '#8a8ca5',
    },
    {
        rgb: [
            249,
            249,
            241,
        ],
        phonic: 'gaosu',
        type: 'bwg',
        name: '缟素',
        hex: '#f9f9f1',
    },
    {
        rgb: [
            170,
            170,
            170,
        ],
        phonic: 'gezihui',
        type: 'bwg',
        name: '鸽子灰',
        hex: '#aaaaaa',
    },
    {
        rgb: [
            146,
            155,
            162,
        ],
        phonic: 'gudinghui',
        type: 'bwg',
        name: '古鼎灰',
        hex: '#929ba2',
    },
    {
        rgb: [
            143,
            143,
            131,
        ],
        phonic: 'guibeihui',
        type: 'bwg',
        name: '龟背灰',
        hex: '#8f8f83',
    },
    {
        rgb: [
            72,
            51,
            50,
        ],
        phonic: 'haibaohui',
        type: 'bwg',
        name: '海豹灰',
        hex: '#483332',
    },
    {
        rgb: [
            167,
            153,
            126,
        ],
        phonic: 'haishenhui',
        type: 'bwg',
        name: '海参灰',
        hex: '#a7997e',
    },
    {
        rgb: [
            248,
            243,
            237,
        ],
        phonic: 'hanbaiyu',
        type: 'bwg',
        name: '汉白玉',
        hex: '#f8f3ed',
    },
    {
        rgb: [
            58,
            53,
            57,
        ],
        phonic: 'hetunhui',
        type: 'bwg',
        name: '河豚灰',
        hex: '#3a3539',
    },
    {
        rgb: [
            252,
            236,
            223,
        ],
        phonic: 'hehuabai',
        type: 'bwg',
        name: '荷花白',
        hex: '#fcecdf',
    },
    {
        rgb: [
            147,
            157,
            167,
        ],
        phonic: 'hehui',
        type: 'bwg',
        name: '鹤灰',
        hex: '#939da7',
    },
    {
        rgb: [
            77,
            74,
            81,
        ],
        phonic: 'heimen',
        type: 'bwg',
        name: '黑扪',
        hex: '#4d4a51',
    },
    {
        rgb: [
            95,
            88,
            95,
        ],
        phonic: 'hongmen',
        type: 'bwg',
        name: '红扪',
        hex: '#5f585f',
    },
    {
        rgb: [
            31,
            7,
            23,
        ],
        phonic: 'hongqing',
        type: 'bwg',
        name: '红青',
        hex: '#1f0717',
    },
    {
        rgb: [
            70,
            66,
            67,
        ],
        phonic: 'hongzao',
        type: 'bwg',
        name: '红皂',
        hex: '#464243',
    },
    {
        rgb: [
            152,
            132,
            108,
        ],
        phonic: 'houmaohui',
        type: 'bwg',
        name: '猴毛灰',
        hex: '#98846c',
    },
    {
        rgb: [
            248,
            242,
            230,
        ],
        phonic: 'hufen',
        type: 'bwg',
        name: '胡粉',
        hex: '#f8f2e6',
    },
    {
        rgb: [
            133,
            124,
            117,
        ],
        phonic: 'huanghunhui',
        type: 'bwg',
        name: '黄昏灰',
        hex: '#857c75',
    },
    {
        rgb: [
            226,
            225,
            230,
        ],
        phonic: 'huibai',
        type: 'bwg',
        name: '灰白',
        hex: '#e2e1e6',
    },
    {
        rgb: [
            73,
            73,
            73,
        ],
        phonic: 'huihei',
        type: 'bwg',
        name: '灰黑',
        hex: '#494949',
    },
    {
        rgb: [
            168,
            175,
            185,
        ],
        phonic: 'huimi',
        type: 'bwg',
        name: '灰米',
        hex: '#a8afb9',
    },
    {
        rgb: [
            90,
            88,
            93,
        ],
        phonic: 'huishu',
        type: 'bwg',
        name: '灰鼠',
        hex: '#5a585d',
    },
    {
        rgb: [
            230,
            237,
            243,
        ],
        phonic: 'jianbai',
        type: 'bwg',
        name: '茧白',
        hex: '#e6edf3',
    },
    {
        rgb: [
            86,
            98,
            94,
        ],
        phonic: 'jiaoqing',
        type: 'bwg',
        name: '胶青',
        hex: '#56625e',
    },
    {
        rgb: [
            252,
            252,
            252,
        ],
        phonic: 'jiebai',
        type: 'bwg',
        name: '洁白',
        hex: '#fcfcfc',
    },
    {
        rgb: [
            215,
            213,
            218,
        ],
        phonic: 'jinhui',
        type: 'bwg',
        name: '烬灰',
        hex: '#d7d5da',
    },
    {
        rgb: [
            73,
            80,
            99,
        ],
        phonic: 'jingyuhui',
        type: 'bwg',
        name: '鲸鱼灰',
        hex: '#495063',
    },
    {
        rgb: [
            255,
            246,
            207,
        ],
        phonic: 'juleibai',
        type: 'bwg',
        name: '菊蕾白',
        hex: '#fff6cf',
    },
    {
        rgb: [
            187,
            198,
            204,
        ],
        phonic: 'kaohui',
        type: 'bwg',
        name: '靠灰',
        hex: '#bbc6cc',
    },
    {
        rgb: [
            222,
            227,
            230,
        ],
        phonic: 'labai',
        type: 'bwg',
        name: '蜡白',
        hex: '#dee3e6',
    },
    {
        rgb: [
            94,
            122,
            136,
        ],
        phonic: 'lanhui',
        type: 'bwg',
        name: '蓝灰',
        hex: '#5e7a88',
    },
    {
        rgb: [
            130,
            134,
            135,
        ],
        phonic: 'langyanhui',
        type: 'bwg',
        name: '狼烟灰',
        hex: '#828687',
    },
    {
        rgb: [
            98,
            97,
            102,
        ],
        phonic: 'laohui',
        type: 'bwg',
        name: '老灰',
        hex: '#626166',
    },
    {
        rgb: [
            242,
            230,
            206,
        ],
        phonic: 'liroubai',
        type: 'bwg',
        name: '荔肉白',
        hex: '#f2e6ce',
    },
    {
        rgb: [
            239,
            244,
            247,
        ],
        phonic: 'lianbanbai',
        type: 'bwg',
        name: '莲瓣白',
        hex: '#eff4f7',
    },
    {
        rgb: [
            255,
            244,
            204,
        ],
        phonic: 'lianzibai',
        type: 'bwg',
        name: '莲子白',
        hex: '#fff4cc',
    },
    {
        rgb: [
            189,
            173,
            173,
        ],
        phonic: 'lusuihui',
        type: 'bwg',
        name: '芦穗灰',
        hex: '#bdadad',
    },
    {
        rgb: [
            162,
            137,
            143,
        ],
        phonic: 'luhui',
        type: 'bwg',
        name: '芦灰',
        hex: '#a2898f',
    },
    {
        rgb: [
            170,
            178,
            165,
        ],
        phonic: 'lvhui',
        type: 'bwg',
        name: '绿灰',
        hex: '#aab2a5',
    },
    {
        rgb: [
            208,
            204,
            201,
        ],
        phonic: 'manaohui',
        type: 'bwg',
        name: '玛瑙灰',
        hex: '#d0ccc9',
    },
    {
        rgb: [
            87,
            56,
            64,
        ],
        phonic: 'meiguihui',
        type: 'bwg',
        name: '玫瑰灰',
        hex: '#573840',
    },
    {
        rgb: [
            241,
            237,
            228,
        ],
        phonic: 'mibai',
        type: 'bwg',
        name: '米白',
        hex: '#f1ede4',
    },
    {
        rgb: [
            190,
            194,
            193,
        ],
        phonic: 'mihui',
        type: 'bwg',
        name: '米灰',
        hex: '#bec2c1',
    },
    {
        rgb: [
            103,
            102,
            108,
        ],
        phonic: 'mohui',
        type: 'bwg',
        name: '墨灰',
        hex: '#67666c',
    },
    {
        rgb: [
            139,
            152,
            142,
        ],
        phonic: 'minghui',
        type: 'bwg',
        name: '明灰',
        hex: '#8b988e',
    },
    {
        rgb: [
            155,
            138,
            138,
        ],
        phonic: 'muyunhui',
        type: 'bwg',
        name: '暮云灰',
        hex: '#9b8a8a',
    },
    {
        rgb: [
            110,
            120,
            122,
        ],
        phonic: 'nenhui',
        type: 'bwg',
        name: '嫩灰',
        hex: '#6e787a',
    },
    {
        rgb: [
            156,
            155,
            160,
        ],
        phonic: 'niehui',
        type: 'bwg',
        name: '镍灰',
        hex: '#9c9ba0',
    },
    {
        rgb: [
            46,
            46,
            54,
        ],
        phonic: 'niujiaohui',
        type: 'bwg',
        name: '牛角灰',
        hex: '#2e2e36',
    },
    {
        rgb: [
            154,
            137,
            121,
        ],
        phonic: 'ouhui',
        type: 'bwg',
        name: '鸥灰',
        hex: '#9a8979',
    },
    {
        rgb: [
            192,
            192,
            202,
        ],
        phonic: 'qianzhanghui',
        type: 'bwg',
        name: '仟张灰',
        hex: '#c0c0ca',
    },
    {
        rgb: [
            188,
            181,
            173,
        ],
        phonic: 'qianhui',
        type: 'bwg',
        name: '铅灰',
        hex: '#bcb5ad',
    },
    {
        rgb: [
            219,
            212,
            204,
        ],
        phonic: 'qianhui',
        type: 'bwg',
        name: '浅灰',
        hex: '#dbd4cc',
    },
    {
        rgb: [
            196,
            188,
            186,
        ],
        phonic: 'qianzonghui',
        type: 'bwg',
        name: '浅棕灰',
        hex: '#c4bcba',
    },
    {
        rgb: [
            228,
            228,
            226,
        ],
        phonic: 'qianshibai',
        type: 'bwg',
        name: '芡实白',
        hex: '#e4e4e2',
    },
    {
        rgb: [
            43,
            51,
            62,
        ],
        phonic: 'qinghui',
        type: 'bwg',
        name: '青灰',
        hex: '#2b333e',
    },
    {
        rgb: [
            196,
            214,
            214,
        ],
        phonic: 'qionghui',
        type: 'bwg',
        name: '穹灰',
        hex: '#c4d6d6',
    },
    {
        rgb: [
            154,
            166,
            182,
        ],
        phonic: 'quehui',
        type: 'bwg',
        name: '鹊灰',
        hex: '#9aa6b6',
    },
    {
        rgb: [
            250,
            244,
            220,
        ],
        phonic: 'rubai',
        type: 'bwg',
        name: '乳白',
        hex: '#faf4dc',
    },
    {
        rgb: [
            53,
            52,
            60,
        ],
        phonic: 'shayuhui',
        type: 'bwg',
        name: '沙鱼灰',
        hex: '#35343c',
    },
    {
        rgb: [
            129,
            119,
            110,
        ],
        phonic: 'shenhui',
        type: 'bwg',
        name: '深灰',
        hex: '#81776e',
    },
    {
        rgb: [
            123,
            93,
            101,
        ],
        phonic: 'shenluhui',
        type: 'bwg',
        name: '深芦灰',
        hex: '#7b5d65',
    },
    {
        rgb: [
            98,
            73,
            66,
        ],
        phonic: 'shibanhui',
        type: 'bwg',
        name: '石板灰',
        hex: '#624942',
    },
    {
        rgb: [
            147,
            141,
            143,
        ],
        phonic: 'shubeihui',
        type: 'bwg',
        name: '鼠背灰',
        hex: '#938d8f',
    },
    {
        rgb: [
            80,
            75,
            79,
        ],
        phonic: 'shumao',
        type: 'bwg',
        name: '鼠毛',
        hex: '#504b4f',
    },
    {
        rgb: [
            153,
            149,
            140,
        ],
        phonic: 'shuidiaohui',
        type: 'bwg',
        name: '水貂灰',
        hex: '#99958c',
    },
    {
        rgb: [
            165,
            174,
            179,
        ],
        phonic: 'shuihui',
        type: 'bwg',
        name: '水灰',
        hex: '#a5aeb3',
    },
    {
        rgb: [
            48,
            47,
            53,
        ],
        phonic: 'shuiniuhui',
        type: 'bwg',
        name: '水牛灰',
        hex: '#302f35',
    },
    {
        rgb: [
            80,
            64,
            51,
        ],
        phonic: 'songshuhui',
        type: 'bwg',
        name: '松鼠灰',
        hex: '#504033',
    },
    {
        rgb: [
            135,
            135,
            135,
        ],
        phonic: 'songyanhui',
        type: 'bwg',
        name: '松烟灰',
        hex: '#878787',
    },
    {
        rgb: [
            162,
            131,
            163,
        ],
        phonic: 'taohui',
        type: 'bwg',
        name: '桃灰',
        hex: '#a283a3',
    },
    {
        rgb: [
            148,
            138,
            129,
        ],
        phonic: 'tianshuhui',
        type: 'bwg',
        name: '田鼠灰',
        hex: '#948a81',
    },
    {
        rgb: [
            105,
            109,
            112,
        ],
        phonic: 'tiehui',
        type: 'bwg',
        name: '铁灰',
        hex: '#696d70',
    },
    {
        rgb: [
            90,
            89,
            97,
        ],
        phonic: 'tiese',
        type: 'bwg',
        name: '铁色',
        hex: '#5a5961',
    },
    {
        rgb: [
            71,
            72,
            76,
        ],
        phonic: 'waguanhui',
        type: 'bwg',
        name: '瓦罐灰',
        hex: '#47484c',
    },
    {
        rgb: [
            135,
            126,
            119,
        ],
        phonic: 'wahui',
        type: 'bwg',
        name: '瓦灰',
        hex: '#877e77',
    },
    {
        rgb: [
            158,
            149,
            140,
        ],
        phonic: 'weihui',
        type: 'bwg',
        name: '猬灰',
        hex: '#9e958c',
    },
    {
        rgb: [
            143,
            143,
            145,
        ],
        phonic: 'wuzeihui',
        type: 'bwg',
        name: '乌贼灰',
        hex: '#8f8f91',
    },
    {
        rgb: [
            132,
            137,
            131,
        ],
        phonic: 'xijiaohui',
        type: 'bwg',
        name: '犀角灰',
        hex: '#848983',
    },
    {
        rgb: [
            158,
            172,
            175,
        ],
        phonic: 'xiayunhui',
        type: 'bwg',
        name: '夏云灰',
        hex: '#9eacaf',
    },
    {
        rgb: [
            120,
            132,
            158,
        ],
        phonic: 'xiangsihui',
        type: 'bwg',
        name: '相思灰',
        hex: '#78849e',
    },
    {
        rgb: [
            144,
            140,
            128,
        ],
        phonic: 'xianghui',
        type: 'bwg',
        name: '象灰',
        hex: '#908c80',
    },
    {
        rgb: [
            239,
            238,
            218,
        ],
        phonic: 'xiangyabai',
        type: 'bwg',
        name: '象牙白',
        hex: '#efeeda',
    },
    {
        rgb: [
            212,
            196,
            183,
        ],
        phonic: 'xiaohui',
        type: 'bwg',
        name: '晓灰',
        hex: '#d4c4b7',
    },
    {
        rgb: [
            106,
            94,
            70,
        ],
        phonic: 'xiekehui',
        type: 'bwg',
        name: '蟹壳灰',
        hex: '#6a5e46',
    },
    {
        rgb: [
            178,
            188,
            190,
        ],
        phonic: 'xinghui',
        type: 'bwg',
        name: '星灰',
        hex: '#b2bcbe',
    },
    {
        rgb: [
            54,
            53,
            59,
        ],
        phonic: 'xuanse',
        type: 'bwg',
        name: '玄色',
        hex: '#36353b',
    },
    {
        rgb: [
            136,
            149,
            165,
        ],
        phonic: 'yanhui',
        type: 'bwg',
        name: '砚灰',
        hex: '#8895a5',
    },
    {
        rgb: [
            128,
            118,
            109,
        ],
        phonic: 'yanhui',
        type: 'bwg',
        name: '雁灰',
        hex: '#80766d',
    },
    {
        rgb: [
            92,
            81,
            61,
        ],
        phonic: 'yanyuhui',
        type: 'bwg',
        name: '燕羽灰',
        hex: '#5c513d',
    },
    {
        rgb: [
            181,
            181,
            181,
        ],
        phonic: 'yangrong',
        type: 'bwg',
        name: '羊绒',
        hex: '#b5b5b5',
    },
    {
        rgb: [
            241,
            240,
            236,
        ],
        phonic: 'yinbai',
        type: 'bwg',
        name: '银白',
        hex: '#f1f0ec',
    },
    {
        rgb: [
            255,
            254,
            249,
        ],
        phonic: 'xuebai',
        type: 'bwg',
        name: '雪白',
        hex: '#fffef9',
    },
    {
        rgb: [
            175,
            172,
            167,
        ],
        phonic: 'yinhui',
        type: 'bwg',
        name: '银灰',
        hex: '#afaca7',
    },
    {
        rgb: [
            181,
            169,
            143,
        ],
        phonic: 'yinshuhui',
        type: 'bwg',
        name: '银鼠灰',
        hex: '#b5a98f',
    },
    {
        rgb: [
            203,
            209,
            214,
        ],
        phonic: 'yinyubai',
        type: 'bwg',
        name: '银鱼白',
        hex: '#cbd1d6',
    },
    {
        rgb: [
            75,
            73,
            84,
        ],
        phonic: 'yingbei',
        type: 'bwg',
        name: '鹰背',
        hex: '#4b4954',
    },
    {
        rgb: [
            247,
            244,
            237,
        ],
        phonic: 'yudubai',
        type: 'bwg',
        name: '鱼肚白',
        hex: '#f7f4ed',
    },
    {
        rgb: [
            95,
            97,
            110,
        ],
        phonic: 'yuweihui',
        type: 'bwg',
        name: '鱼尾灰',
        hex: '#5f616e',
    },
    {
        rgb: [
            81,
            82,
            87,
        ],
        phonic: 'yuanqing',
        type: 'bwg',
        name: '元青',
        hex: '#515257',
    },
    {
        rgb: [
            183,
            174,
            143,
        ],
        phonic: 'yuehui',
        type: 'bwg',
        name: '月灰',
        hex: '#b7ae8f',
    },
    {
        rgb: [
            192,
            189,
            195,
        ],
        phonic: 'yueyingbai',
        type: 'bwg',
        name: '月影白',
        hex: '#c0bdc3',
    },
    {
        rgb: [
            216,
            227,
            231,
        ],
        phonic: 'yunfengbai',
        type: 'bwg',
        name: '云峰白',
        hex: '#d8e3e7',
    },
    {
        rgb: [
            67,
            68,
            70,
        ],
        phonic: 'zaose',
        type: 'bwg',
        name: '皂色',
        hex: '#434446',
    },
    {
        rgb: [
            54,
            53,
            51,
        ],
        phonic: 'changshihui',
        type: 'bwg',
        name: '长石灰',
        hex: '#363533',
    },
    {
        rgb: [
            228,
            224,
            215,
        ],
        phonic: 'zhenzhuhui',
        type: 'bwg',
        name: '珍珠灰',
        hex: '#e4e0d7',
    },
    {
        rgb: [
            72,
            69,
            78,
        ],
        phonic: 'zhenzhumo',
        type: 'bwg',
        name: '真朱墨',
        hex: '#48454e',
    },
    {
        rgb: [
            126,
            132,
            148,
        ],
        phonic: 'zhenghui',
        type: 'bwg',
        name: '正灰',
        hex: '#7e8494',
    },
    {
        rgb: [
            117,
            136,
            140,
        ],
        phonic: 'zhijinhui',
        type: 'bwg',
        name: '织锦灰',
        hex: '#75888c',
    },
    {
        rgb: [
            188,
            181,
            173,
        ],
        phonic: 'zhonghui',
        type: 'bwg',
        name: '中灰',
        hex: '#bcb5ad',
    },
    {
        rgb: [
            161,
            151,
            150,
        ],
        phonic: 'zonghui',
        type: 'bwg',
        name: '棕灰',
        hex: '#a19796',
    },
    {
        rgb: [
            178,
            180,
            179,
        ],
        phonic: 'zhongruhui',
        type: 'bwg',
        name: '钟乳灰',
        hex: '#b2b4b3',
    },
    {
        rgb: [
            49,
            45,
            46,
        ],
        phonic: 'zhumo',
        type: 'bwg',
        name: '朱墨',
        hex: '#312d2e',
    },
    {
        rgb: [
            223,
            206,
            196,
        ],
        phonic: 'zhumuhui',
        type: 'bwg',
        name: '珠母灰',
        hex: '#dfcec4',
    },
    {
        rgb: [
            183,
            159,
            147,
        ],
        phonic: 'zhuwanghui',
        type: 'bwg',
        name: '蛛网灰',
        hex: '#b79f93',
    },
    {
        rgb: [
            39,
            43,
            55,
        ],
        phonic: 'zise',
        type: 'bwg',
        name: '缁色',
        hex: '#272b37',
    },
    {
        rgb: [
            94,
            63,
            81,
        ],
        phonic: 'zihui',
        type: 'bwg',
        name: '紫灰',
        hex: '#5e3f51',
    },
]
