export const green = [
    {
        rgb: [
            223,
            237,
            214,
        ],
        phonic: 'aibeilv',
        type: 'green',
        name: '艾背绿',
        hex: '#dfedd6',
    },
    {
        rgb: [
            165,
            190,
            125,
        ],
        phonic: 'ailv',
        type: 'green',
        name: '艾绿',
        hex: '#a5be7d',
    },
    {
        rgb: [
            59,
            78,
            57,
        ],
        phonic: 'bajiaolv',
        type: 'green',
        name: '芭蕉绿',
        hex: '#3b4e39',
    },
    {
        rgb: [
            162,
            187,
            122,
        ],
        phonic: 'baizhilvlv',
        type: 'green',
        name: '柏枝緑',
        hex: '#a2bb7a',
    },
    {
        rgb: [
            149,
            177,
            162,
        ],
        phonic: 'biselv',
        type: 'green',
        name: '碧色',
        hex: '#95b1a2',
    },
    {
        rgb: [
            97,
            139,
            93,
        ],
        phonic: 'bolilv',
        type: 'green',
        name: '玻璃绿',
        hex: '#618b5d',
    },
    {
        rgb: [
            34,
            80,
            54,
        ],
        phonic: 'canglv',
        type: 'green',
        name: '苍绿',
        hex: '#225036',
    },
    {
        rgb: [
            134,
            113,
            24,
        ],
        phonic: 'biluochunlv',
        type: 'green',
        name: '碧罗春绿',
        hex: '#867118',
    },
    {
        rgb: [
            102,
            183,
            0,
        ],
        phonic: 'bichanlv',
        type: 'green',
        name: '碧蝉绿',
        hex: '#66b700',
    },
    {
        rgb: [
            65,
            174,
            59,
        ],
        phonic: 'baoshilv',
        type: 'green',
        name: '宝石绿',
        hex: '#41ae3b',
    },
    {
        rgb: [
            33,
            127,
            77,
        ],
        phonic: 'bohelv',
        type: 'green',
        name: '薄荷绿',
        hex: '#217f4d',
    },
    {
        rgb: [
            73,
            91,
            77,
        ],
        phonic: 'baiqucailv',
        type: 'green',
        name: '白屈菜绿',
        hex: '#495b4d',
    },
    {
        rgb: [
            81,
            98,
            62,
        ],
        phonic: 'baipisonglv',
        type: 'green',
        name: '白皮松绿',
        hex: '#51623e',
    },
    {
        rgb: [
            58,
            50,
            13,
        ],
        phonic: 'anganlanlv',
        type: 'green',
        name: '暗橄榄绿',
        hex: '#3a320d',
    },
    {
        rgb: [
            132,
            203,
            173,
        ],
        phonic: 'fenlv',
        type: 'green',
        name: '粉绿',
        hex: '#84cbad',
    },
    {
        rgb: [
            126,
            190,
            104,
        ],
        phonic: 'fupinglv',
        type: 'green',
        name: '浮萍绿',
        hex: '#7ebe68',
    },
    {
        rgb: [
            191,
            201,
            53,
        ],
        phonic: 'ganlanhuanglv',
        type: 'green',
        name: '橄榄黄绿',
        hex: '#bfc935',
    },
    {
        rgb: [
            177,
            207,
            135,
        ],
        phonic: 'ganlanshilv',
        type: 'green',
        name: '橄榄石绿',
        hex: '#b1cf87',
    },
    {
        rgb: [
            106,
            150,
            75,
        ],
        phonic: 'gualv',
        type: 'green',
        name: '瓜绿',
        hex: '#6a964b',
    },
    {
        rgb: [
            91,
            168,
            56,
        ],
        phonic: 'guanlv',
        type: 'green',
        name: '官绿',
        hex: '#5ba838',
    },
    {
        rgb: [
            26,
            104,
            64,
        ],
        phonic: 'heyelv',
        type: 'green',
        name: '荷叶绿',
        hex: '#1a6840',
    },
    {
        rgb: [
            48,
            58,
            5,
        ],
        phonic: 'haidailv',
        type: 'green',
        name: '海带绿',
        hex: '#303a05',
    },
    {
        rgb: [
            70,
            82,
            80,
        ],
        phonic: 'guibeihuilv',
        type: 'green',
        name: '龟背灰绿',
        hex: '#465250',
    },
    {
        rgb: [
            83,
            60,
            28,
        ],
        phonic: 'gutonglv',
        type: 'green',
        name: '古铜绿',
        hex: '#533c1c',
    },
    {
        rgb: [
            32,
            137,
            78,
        ],
        phonic: 'gongdianlv',
        type: 'green',
        name: '宫殿绿',
        hex: '#20894e',
    },
    {
        rgb: [
            96,
            89,
            24,
        ],
        phonic: 'ganlanlv',
        type: 'green',
        name: '橄榄绿',
        hex: '#605918',
    },
    {
        rgb: [
            46,
            131,
            48,
        ],
        phonic: 'feicuilv',
        type: 'green',
        name: '翡翠',
        hex: '#2e8330',
    },
    {
        rgb: [
            73,
            117,
            104,
        ],
        phonic: 'feiquanlv',
        type: 'green',
        name: '飞泉绿',
        hex: '#497568',
    },
    {
        rgb: [
            141,
            128,
            75,
        ],
        phonic: 'caohuilv',
        type: 'green',
        name: '草灰绿',
        hex: '#8d804b',
    },
    {
        rgb: [
            156,
            176,
            63,
        ],
        phonic: 'caolv',
        type: 'green',
        name: '草绿',
        hex: '#9cb03f',
    },
    {
        rgb: [
            153,
            219,
            5,
        ],
        phonic: 'chunlv',
        type: 'green',
        name: '春绿',
        hex: '#99db05',
    },
    {
        rgb: [
            154,
            181,
            52,
        ],
        phonic: 'conglv',
        type: 'green',
        name: '葱绿',
        hex: '#9ab534',
    },
    {
        rgb: [
            118,
            155,
            122,
        ],
        phonic: 'cuipinglv',
        type: 'green',
        name: '翠屏绿',
        hex: '#769b7a',
    },
    {
        rgb: [
            97,
            172,
            133,
        ],
        phonic: 'danlv',
        type: 'green',
        name: '淡绿',
        hex: '#61ac85',
    },
    {
        rgb: [
            88,
            149,
            115,
        ],
        phonic: 'danbaishilv',
        type: 'green',
        name: '蛋白石绿',
        hex: '#589573',
    },
    {
        rgb: [
            147,
            178,
            134,
        ],
        phonic: 'doulv',
        type: 'green',
        name: '豆绿',
        hex: '#93b286',
    },
    {
        rgb: [
            109,
            157,
            48,
        ],
        phonic: 'fangzhinianglv',
        type: 'green',
        name: '纺织娘绿',
        hex: '#6d9d30',
    },
    {
        rgb: [
            99,
            137,
            112,
        ],
        phonic: 'dushanyulv',
        type: 'green',
        name: '独山玉绿',
        hex: '#638970',
    },
    {
        rgb: [
            102,
            142,
            19,
        ],
        phonic: 'dongqinglv',
        type: 'green',
        name: '冬青绿',
        hex: '#668e13',
    },
    {
        rgb: [
            32,
            165,
            94,
        ],
        phonic: 'cuilv',
        type: 'green',
        name: '翠绿',
        hex: '#20a55e',
    },
    {
        rgb: [
            55,
            56,
            51,
        ],
        phonic: 'congyoulv',
        type: 'green',
        name: '葱油绿',
        hex: '#373833',
    },
    {
        rgb: [
            60,
            149,
            103,
        ],
        phonic: 'chanlv',
        type: 'green',
        name: '蟾绿',
        hex: '#3c9567',
    },
    {
        rgb: [
            207,
            220,
            115,
        ],
        phonic: 'huaihuahuanglv',
        type: 'green',
        name: '槐花黄绿',
        hex: '#cfdc73',
    },
    {
        rgb: [
            64,
            88,
            28,
        ],
        phonic: 'jianqiaolv',
        type: 'green',
        name: '剑鞘绿',
        hex: '#40581c',
    },
    {
        rgb: [
            67,
            145,
            9,
        ],
        phonic: 'jinglv',
        type: 'green',
        name: '京绿',
        hex: '#439109',
    },
    {
        rgb: [
            220,
            245,
            162,
        ],
        phonic: 'julv',
        type: 'green',
        name: '菊绿',
        hex: '#dcf5a2',
    },
    {
        rgb: [
            34,
            149,
            84,
        ],
        phonic: 'kongquelv',
        type: 'green',
        name: '孔雀绿',
        hex: '#229554',
    },
    {
        rgb: [
            150,
            199,
            120,
        ],
        phonic: 'koushaolv',
        type: 'green',
        name: '蔻梢绿',
        hex: '#96c778',
    },
    {
        rgb: [
            185,
            179,
            121,
        ],
        phonic: 'kulv',
        type: 'green',
        name: '枯绿',
        hex: '#b9b379',
    },
    {
        rgb: [
            62,
            74,
            62,
        ],
        phonic: 'laolv',
        type: 'green',
        name: '老绿',
        hex: '#3e4a3e',
    },
    {
        rgb: [
            58,
            94,
            80,
        ],
        phonic: 'laolanhualv',
        type: 'green',
        name: '老蓝花绿',
        hex: '#3a5e50',
    },
    {
        rgb: [
            41,
            82,
            52,
        ],
        phonic: 'laokuilv',
        type: 'green',
        name: '老葵绿',
        hex: '#295234',
    },
    {
        rgb: [
            45,
            81,
            77,
        ],
        phonic: 'laojulv',
        type: 'green',
        name: '老醵绿',
        hex: '#2d514d',
    },
    {
        rgb: [
            55,
            87,
            50,
        ],
        phonic: 'lvshen',
        type: 'green',
        name: '绿沈',
        hex: '#375732',
    },
    {
        rgb: [
            49,
            74,
            68,
        ],
        phonic: 'huilv',
        type: 'green',
        name: '灰绿',
        hex: '#314a44',
    },
    {
        rgb: [
            43,
            49,
            45,
        ],
        phonic: 'hujishenglv',
        type: 'green',
        name: '槲寄生绿',
        hex: '#2b312d',
    },
    {
        rgb: [
            21,
            31,
            4,
        ],
        phonic: 'heilvlv',
        type: 'green',
        name: '黒緑',
        hex: '#151f04',
    },
    {
        rgb: [
            190,
            208,
            135,
        ],
        phonic: 'pingguolv',
        type: 'green',
        name: '苹果绿',
        hex: '#bed087',
    },
    {
        rgb: [
            106,
            188,
            152,
        ],
        phonic: 'piaoselv',
        type: 'green',
        name: '缥色',
        hex: '#6abc98',
    },
    {
        rgb: [
            68,
            177,
            68,
        ],
        phonic: 'nenlv',
        type: 'green',
        name: '嫩绿',
        hex: '#44b144',
    },
    {
        rgb: [
            129,
            201,
            75,
        ],
        phonic: 'qicailv',
        type: 'green',
        name: '荠菜绿',
        hex: '#81c94b',
    },
    {
        rgb: [
            43,
            150,
            120,
        ],
        phonic: 'qingfanlv',
        type: 'green',
        name: '青矾绿',
        hex: '#2b9678',
    },
    {
        rgb: [
            63,
            102,
            71,
        ],
        phonic: 'qingcailv',
        type: 'green',
        name: '青菜绿',
        hex: '#3f6647',
    },
    {
        rgb: [
            17,
            122,
            117,
        ],
        phonic: 'qinglv',
        type: 'green',
        name: '青绿',
        hex: '#117a75',
    },
    {
        rgb: [
            149,
            190,
            150,
        ],
        phonic: 'qingmeilv',
        type: 'green',
        name: '青梅绿',
        hex: '#95be96',
    },
    {
        rgb: [
            173,
            200,
            131,
        ],
        phonic: 'qiuguilv',
        type: 'green',
        name: '秋瑰',
        hex: '#adc883',
    },
    {
        rgb: [
            128,
            128,
            64,
        ],
        phonic: 'qiuxianglv',
        type: 'green',
        name: '秋香绿',
        hex: '#808040',
    },
    {
        rgb: [
            199,
            238,
            207,
        ],
        phonic: 'shalv',
        type: 'green',
        name: '沙绿',
        hex: '#c7eecf',
    },
    {
        rgb: [
            51,
            49,
            24,
        ],
        phonic: 'shedanlv',
        type: 'green',
        name: '蛇胆绿',
        hex: '#333118',
    },
    {
        rgb: [
            143,
            138,
            108,
        ],
        phonic: 'sangpilv',
        type: 'green',
        name: '桑皮绿',
        hex: '#8f8a6c',
    },
    {
        rgb: [
            24,
            27,
            16,
        ],
        phonic: 'qilvlv',
        type: 'green',
        name: '漆緑',
        hex: '#181b10',
    },
    {
        rgb: [
            185,
            211,
            28,
        ],
        phonic: 'liufanglv',
        type: 'green',
        name: '柳芳绿',
        hex: '#b9d31c',
    },
    {
        rgb: [
            175,
            221,
            35,
        ],
        phonic: 'liulv',
        type: 'green',
        name: '柳绿',
        hex: '#afdd23',
    },
    {
        rgb: [
            184,
            208,
            122,
        ],
        phonic: 'luweilv',
        type: 'green',
        name: '芦苇绿',
        hex: '#b8d07a',
    },
    {
        rgb: [
            85,
            187,
            139,
        ],
        phonic: 'mailv',
        type: 'green',
        name: '麦绿',
        hex: '#55bb8b',
    },
    {
        rgb: [
            91,
            192,
            132,
        ],
        phonic: 'maimiaolv',
        type: 'green',
        name: '麦苗绿',
        hex: '#5bc084',
    },
    {
        rgb: [
            68,
            122,
            20,
        ],
        phonic: 'maolv',
        type: 'green',
        name: '毛绿',
        hex: '#447a14',
    },
    {
        rgb: [
            18,
            170,
            157,
        ],
        phonic: 'meidielv',
        type: 'green',
        name: '美蝶绿',
        hex: '#12aa9d',
    },
    {
        rgb: [
            126,
            166,
            96,
        ],
        phonic: 'minglv',
        type: 'green',
        name: '明绿',
        hex: '#7ea660',
    },
    {
        rgb: [
            147,
            153,
            117,
        ],
        phonic: 'mulilv',
        type: 'green',
        name: '牡蛎绿',
        hex: '#939975',
    },
    {
        rgb: [
            167,
            176,
            121,
        ],
        phonic: 'nailv',
        type: 'green',
        name: '奶绿',
        hex: '#a7b079',
    },
    {
        rgb: [
            34,
            51,
            35,
        ],
        phonic: 'molv',
        type: 'green',
        name: '墨绿',
        hex: '#223323',
    },
    {
        rgb: [
            20,
            31,
            27,
        ],
        phonic: 'mangconglv',
        type: 'green',
        name: '莽丛绿',
        hex: '#141f1b',
    },
    {
        rgb: [
            110,
            139,
            11,
        ],
        phonic: 'matilianlv',
        type: 'green',
        name: '马蹄莲绿',
        hex: '#6e8b0b',
    },
    {
        rgb: [
            28,
            87,
            83,
        ],
        phonic: 'liulilv',
        type: 'green',
        name: '琉璃绿',
        hex: '#1c5753',
    },
    {
        rgb: [
            186,
            206,
            102,
        ],
        phonic: 'qiukuilv',
        type: 'green',
        name: '秋葵绿',
        hex: '#bace66',
    },
    {
        rgb: [
            104,
            126,
            87,
        ],
        phonic: 'shihulv',
        type: 'green',
        name: '石斛绿',
        hex: '#687e57',
    },
    {
        rgb: [
            161,
            212,
            155,
        ],
        phonic: 'shuilv',
        type: 'green',
        name: '水绿',
        hex: '#a1d49b',
    },
    {
        rgb: [
            131,
            160,
            140,
        ],
        phonic: 'songshuanglv',
        type: 'green',
        name: '松霜绿',
        hex: '#83a08c',
    },
    {
        rgb: [
            150,
            210,
            198,
        ],
        phonic: 'tianshuibilv',
        type: 'green',
        name: '天水碧',
        hex: '#96d2c6',
    },
    {
        rgb: [
            70,
            121,
            55,
        ],
        phonic: 'tanglanglv',
        type: 'green',
        name: '螳螂绿',
        hex: '#467937',
    },
    {
        rgb: [
            116,
            208,
            73,
        ],
        phonic: 'wojulv',
        type: 'green',
        name: '莴苣绿',
        hex: '#74d049',
    },
    {
        rgb: [
            70,
            184,
            135,
        ],
        phonic: 'walv',
        type: 'green',
        name: '蛙绿',
        hex: '#46b887',
    },
    {
        rgb: [
            46,
            174,
            144,
        ],
        phonic: 'tonglv',
        type: 'green',
        name: '铜绿',
        hex: '#2eae90',
    },
    {
        rgb: [
            105,
            161,
            150,
        ],
        phonic: 'wuzhilv',
        type: 'green',
        name: '梧枝绿',
        hex: '#69a196',
    },
    {
        rgb: [
            94,
            102,
            91,
        ],
        phonic: 'tianluolv',
        type: 'green',
        name: '田螺绿',
        hex: '#5e665b',
    },
    {
        rgb: [
            136,
            115,
            34,
        ],
        phonic: 'tailv',
        type: 'green',
        name: '苔绿',
        hex: '#887322',
    },
    {
        rgb: [
            99,
            88,
            34,
        ],
        phonic: 'tanshuilv',
        type: 'green',
        name: '潭水绿',
        hex: '#635822',
    },
    {
        rgb: [
            53,
            91,
            54,
        ],
        phonic: 'songlv',
        type: 'green',
        name: '松绿',
        hex: '#355b36',
    },
    {
        rgb: [
            26,
            59,
            50,
        ],
        phonic: 'shenhailv',
        type: 'green',
        name: '深海绿',
        hex: '#1a3b32',
    },
    {
        rgb: [
            187,
            243,
            198,
        ],
        phonic: 'yuselv',
        type: 'green',
        name: '玉色',
        hex: '#bbf3c6',
    },
    {
        rgb: [
            66,
            179,
            73,
        ],
        phonic: 'yusuilv',
        type: 'green',
        name: '玉髓绿',
        hex: '#42b349',
    },
    {
        rgb: [
            164,
            202,
            181,
        ],
        phonic: 'yuzanlv',
        type: 'green',
        name: '玉簪绿',
        hex: '#a4cab5',
    },
    {
        rgb: [
            186,
            213,
            180,
        ],
        phonic: 'zhuhuanglv',
        type: 'green',
        name: '竹篁绿',
        hex: '#bad5b4',
    },
    {
        rgb: [
            129,
            192,
            77,
        ],
        phonic: 'zhulv',
        type: 'green',
        name: '竹绿',
        hex: '#81c04d',
    },
    {
        rgb: [
            143,
            170,
            117,
        ],
        phonic: 'zishanlv',
        type: 'green',
        name: '紫杉绿',
        hex: '#8faa75',
    },
    {
        rgb: [
            113,
            159,
            1,
        ],
        phonic: 'zhitiaolvlv',
        type: 'green',
        name: '枝条緑',
        hex: '#719f01',
    },
    {
        rgb: [
            51,
            49,
            24,
        ],
        phonic: 'shedanlv',
        type: 'green',
        name: '蛇胆',
        hex: '#333118',
    },
    {
        rgb: [
            34,
            134,
            96,
        ],
        phonic: 'shilv',
        type: 'green',
        name: '石绿',
        hex: '#228660',
    },
    {
        rgb: [
            135,
            104,
            24,
        ],
        phonic: 'zongyelv',
        type: 'green',
        name: '棕叶绿',
        hex: '#876818',
    },
    {
        rgb: [
            90,
            73,
            19,
        ],
        phonic: 'zonglvlv',
        type: 'green',
        name: '棕榈绿',
        hex: '#5a4913',
    },
    {
        rgb: [
            26,
            30,
            24,
        ],
        phonic: 'yunshanlv',
        type: 'green',
        name: '云杉绿',
        hex: '#1a1e18',
    },
    {
        rgb: [
            0,
            84,
            50,
        ],
        phonic: 'youlv',
        type: 'green',
        name: '油绿',
        hex: '#005432',
    },
    {
        rgb: [
            52,
            80,
            65,
        ],
        phonic: 'youlv',
        type: 'green',
        name: '黝绿',
        hex: '#345041',
    },
    {
        rgb: [
            208,
            210,
            21,
        ],
        phonic: 'xinhelv',
        type: 'green',
        name: '新禾绿',
        hex: '#d0d215',
    },
    {
        rgb: [
            179,
            224,
            1,
        ],
        phonic: 'xiuqiulv',
        type: 'green',
        name: '绣球绿',
        hex: '#b3e001',
    },
    {
        rgb: [
            150,
            195,
            78,
        ],
        phonic: 'yalv',
        type: 'green',
        name: '芽绿',
        hex: '#96c34e',
    },
    {
        rgb: [
            116,
            176,
            52,
        ],
        phonic: 'yangselv',
        type: 'green',
        name: '秧色',
        hex: '#74b034',
    },
    {
        rgb: [
            152,
            196,
            47,
        ],
        phonic: 'yinlv',
        type: 'green',
        name: '茵绿',
        hex: '#98c42f',
    },
    {
        rgb: [
            91,
            173,
            36,
        ],
        phonic: 'yingwulv',
        type: 'green',
        name: '鹦鹉绿',
        hex: '#5bad24',
    },
    {
        rgb: [
            83,
            155,
            107,
        ],
        phonic: 'yinggelv',
        type: 'green',
        name: '鹦哥绿',
        hex: '#539b6b',
    },
    {
        rgb: [
            91,
            110,
            78,
        ],
        phonic: 'zaolv',
        type: 'green',
        name: '藻绿',
        hex: '#5b6e4e',
    },
    {
        rgb: [
            156,
            192,
            26,
        ],
        phonic: 'zuocanlv',
        type: 'green',
        name: '柞蚕绿',
        hex: '#9cc01a',
    },
    {
        rgb: [
            90,
            141,
            72,
        ],
        phonic: 'zhuyeqinglv',
        type: 'green',
        name: '竹叶青',
        hex: '#5a8d48',
    },
    {
        rgb: [
            100,
            140,
            87,
        ],
        phonic: 'yalv',
        type: 'green',
        name: '鸭绿',
        hex: '#648c57',
    },
    {
        rgb: [
            66,
            112,
            86,
        ],
        phonic: 'xiulv',
        type: 'green',
        name: '锈绿',
        hex: '#427056',
    },
    {
        rgb: [
            132,
            94,
            29,
        ],
        phonic: 'xiyilv',
        type: 'green',
        name: '蜥蜴绿',
        hex: '#845e1d',
    },
    {
        rgb: [
            65,
            78,
            50,
        ],
        phonic: 'xiancailv',
        type: 'green',
        name: '咸菜绿',
        hex: '#414e32',
    },
]
