export const purple = [
    {
        rgb: [
            189,
            178,
            195,
        ],
        phonic: 'canzi',
        type: 'purple',
        name: '黪紫',
        hex: '#bdb2c3',
    },
    {
        rgb: [
            208,
            194,
            211,
        ],
        phonic: 'danqianniuzi',
        type: 'purple',
        name: '淡牵牛紫',
        hex: '#d0c2d3',
    },
    {
        rgb: [
            80,
            49,
            64,
        ],
        phonic: 'biqizi',
        type: 'purple',
        name: '荸荠紫',
        hex: '#503140',
    },
    {
        rgb: [
            126,
            84,
            120,
        ],
        phonic: 'bingzi',
        type: 'purple',
        name: '并紫',
        hex: '#7e5478',
    },
    {
        rgb: [
            152,
            92,
            143,
        ],
        phonic: 'biandouzi',
        type: 'purple',
        name: '扁豆紫',
        hex: '#985c8f',
    },
    {
        rgb: [
            175,
            153,
            191,
        ],
        phonic: 'danqinglianzi',
        type: 'purple',
        name: '淡青莲',
        hex: '#af99bf',
    },
    {
        rgb: [
            223,
            200,
            210,
        ],
        phonic: 'danqingzi',
        type: 'purple',
        name: '淡青紫',
        hex: '#dfc8d2',
    },
    {
        rgb: [
            175,
            161,
            222,
        ],
        phonic: 'dantengluozi',
        type: 'purple',
        name: '淡藤萝紫',
        hex: '#afa1de',
    },
    {
        rgb: [
            232,
            215,
            223,
        ],
        phonic: 'dingxiangdanzi',
        type: 'purple',
        name: '丁香淡紫',
        hex: '#e8d7df',
    },
    {
        rgb: [
            99,
            82,
            130,
        ],
        phonic: 'dingxiangzi',
        type: 'purple',
        name: '丁香紫',
        hex: '#635282',
    },
    {
        rgb: [
            187,
            117,
            167,
        ],
        phonic: 'douzi',
        type: 'purple',
        name: '豆紫',
        hex: '#bb75a7',
    },
    {
        rgb: [
            223,
            162,
            203,
        ],
        phonic: 'doukouzi',
        type: 'purple',
        name: '豆蔻紫',
        hex: '#dfa2cb',
    },
    {
        rgb: [
            201,
            173,
            196,
        ],
        phonic: 'fengxinzi',
        type: 'purple',
        name: '风信紫',
        hex: '#c9adc4',
    },
    {
        rgb: [
            73,
            39,
            59,
        ],
        phonic: 'ganzhezi',
        type: 'purple',
        name: '甘蔗紫',
        hex: '#49273b',
    },
    {
        rgb: [
            209,
            127,
            209,
        ],
        phonic: 'gejinzi',
        type: 'purple',
        name: '葛巾紫',
        hex: '#d17fd1',
    },
    {
        rgb: [
            68,
            14,
            37,
        ],
        phonic: 'gutongzi',
        type: 'purple',
        name: '古铜紫',
        hex: '#440e25',
    },
    {
        rgb: [
            49,
            16,
            27,
        ],
        phonic: 'heizi',
        type: 'purple',
        name: '黑紫',
        hex: '#31101b',
    },
    {
        rgb: [
            89,
            19,
            55,
        ],
        phonic: 'ganzi',
        type: 'purple',
        name: '绀紫',
        hex: '#591337',
    },
    {
        rgb: [
            70,
            68,
            79,
        ],
        phonic: 'diaozi',
        type: 'purple',
        name: '貂紫',
        hex: '#46444f',
    },
    {
        rgb: [
            142,
            57,
            114,
        ],
        phonic: 'caitouzi',
        type: 'purple',
        name: '菜头紫',
        hex: '#8e3972',
    },
    {
        rgb: [
            93,
            34,
            36,
        ],
        phonic: 'anyuzi',
        type: 'purple',
        name: '暗玉紫',
        hex: '#5d2224',
    },
    {
        rgb: [
            66,
            28,
            53,
        ],
        phonic: 'biqizi',
        type: 'purple',
        name: '荸荠紫',
        hex: '#421c35',
    },
    {
        rgb: [
            53,
            49,
            72,
        ],
        phonic: 'anlongdanzi',
        type: 'purple',
        name: '暗龙胆紫',
        hex: '#353148',
    },
    {
        rgb: [
            36,
            32,
            67,
        ],
        phonic: 'anlanzi',
        type: 'purple',
        name: '暗蓝紫',
        hex: '#242043',
    },
    {
        rgb: [
            128,
            24,
            71,
        ],
        phonic: 'jiguanzi',
        type: 'purple',
        name: '鸡冠紫',
        hex: '#801847',
    },
    {
        rgb: [
            150,
            127,
            244,
        ],
        phonic: 'jiehuazi',
        type: 'purple',
        name: '芥花紫',
        hex: '#967ff4',
    },
    {
        rgb: [
            250,
            122,
            197,
        ],
        phonic: 'jingzi',
        type: 'purple',
        name: '荆紫',
        hex: '#fa7ac5',
    },
    {
        rgb: [
            128,
            108,
            157,
        ],
        phonic: 'jinzi',
        type: 'purple',
        name: '槿紫',
        hex: '#806c9d',
    },
    {
        rgb: [
            135,
            116,
            244,
        ],
        phonic: 'jiegengzi',
        type: 'purple',
        name: '桔梗紫',
        hex: '#8774f4',
    },
    {
        rgb: [
            212,
            163,
            195,
        ],
        phonic: 'luolanzi',
        type: 'purple',
        name: '罗兰紫',
        hex: '#d4a3c3',
    },
    {
        rgb: [
            97,
            62,
            84,
        ],
        phonic: 'longjingyuzi',
        type: 'purple',
        name: '龙睛鱼紫',
        hex: '#613e54',
    },
    {
        rgb: [
            206,
            134,
            227,
        ],
        phonic: 'mabiancaozi',
        type: 'purple',
        name: '马鞭草紫',
        hex: '#ce86e3',
    },
    {
        rgb: [
            154,
            128,
            189,
        ],
        phonic: 'meiguizi',
        type: 'purple',
        name: '玫瑰紫',
        hex: '#9a80bd',
    },
    {
        rgb: [
            115,
            117,
            155,
        ],
        phonic: 'luodianzi',
        type: 'purple',
        name: '螺甸紫',
        hex: '#73759b',
    },
    {
        rgb: [
            170,
            140,
            138,
        ],
        phonic: 'ouhezi',
        type: 'purple',
        name: '藕合',
        hex: '#aa8c8a',
    },
    {
        rgb: [
            163,
            133,
            186,
        ],
        phonic: 'fenzi',
        type: 'purple',
        name: '粉紫',
        hex: '#a385ba',
    },
    {
        rgb: [
            73,
            62,
            84,
        ],
        phonic: 'daizi',
        type: 'purple',
        name: '黛紫',
        hex: '#493e54',
    },
    {
        rgb: [
            142,
            124,
            214,
        ],
        phonic: 'mushanzi',
        type: 'purple',
        name: '暮山紫',
        hex: '#8e7cd6',
    },
    {
        rgb: [
            86,
            63,
            71,
        ],
        phonic: 'moshizi',
        type: 'purple',
        name: '磨石紫',
        hex: '#563f47',
    },
    {
        rgb: [
            33,
            7,
            42,
        ],
        phonic: 'mozi',
        type: 'purple',
        name: '墨紫',
        hex: '#21072a',
    },
    {
        rgb: [
            46,
            50,
            124,
        ],
        phonic: 'mantianxingzi',
        type: 'purple',
        name: '满天星紫',
        hex: '#2e327c',
    },
    {
        rgb: [
            85,
            81,
            98,
        ],
        phonic: 'longkuizi',
        type: 'purple',
        name: '龙葵紫',
        hex: '#555162',
    },
    {
        rgb: [
            49,
            22,
            29,
        ],
        phonic: 'luanshizi',
        type: 'purple',
        name: '卵石紫',
        hex: '#31161d',
    },
    {
        rgb: [
            90,
            26,
            27,
        ],
        phonic: 'lizi',
        type: 'purple',
        name: '栗紫',
        hex: '#5a1a1b',
    },
    {
        rgb: [
            40,
            41,
            85,
        ],
        phonic: 'jingshizi',
        type: 'purple',
        name: '晶石紫',
        hex: '#282955',
    },
    {
        rgb: [
            69,
            46,
            88,
        ],
        phonic: 'lizi',
        type: 'purple',
        name: '李紫',
        hex: '#452e58',
    },
    {
        rgb: [
            80,
            10,
            21,
        ],
        phonic: 'jinyuzi',
        type: 'purple',
        name: '金鱼紫',
        hex: '#500a15',
    },
    {
        rgb: [
            115,
            107,
            146,
        ],
        phonic: 'huizi',
        type: 'purple',
        name: '灰紫',
        hex: '#736b92',
    },
    {
        rgb: [
            72,
            22,
            60,
        ],
        phonic: 'jiangzi',
        type: 'purple',
        name: '绛紫',
        hex: '#48163c',
    },
    {
        rgb: [
            87,
            79,
            90,
        ],
        phonic: 'jianfengzi',
        type: 'purple',
        name: '剑锋紫',
        hex: '#574f5a',
    },
    {
        rgb: [
            220,
            200,
            253,
        ],
        phonic: 'qiantengzi',
        type: 'purple',
        name: '浅藤紫',
        hex: '#dcc8fd',
    },
    {
        rgb: [
            219,
            119,
            231,
        ],
        phonic: 'qiehuazi',
        type: 'purple',
        name: '茄花',
        hex: '#db77e7',
    },
    {
        rgb: [
            105,
            48,
            119,
        ],
        phonic: 'qiesezi',
        type: 'purple',
        name: '茄色',
        hex: '#693077',
    },
    {
        rgb: [
            208,
            152,
            189,
        ],
        phonic: 'qinghakezi',
        type: 'purple',
        name: '青蛤壳紫',
        hex: '#d098bd',
    },
    {
        rgb: [
            149,
            131,
            205,
        ],
        phonic: 'qinglianzi',
        type: 'purple',
        name: '青莲',
        hex: '#9583cd',
    },
    {
        rgb: [
            147,
            46,
            122,
        ],
        phonic: 'qinglianzi',
        type: 'purple',
        name: '青莲紫',
        hex: '#932e7a',
    },
    {
        rgb: [
            98,
            100,
            159,
        ],
        phonic: 'shangengzi',
        type: 'purple',
        name: '山梗紫',
        hex: '#62649f',
    },
    {
        rgb: [
            162,
            90,
            164,
        ],
        phonic: 'shanqiezi',
        type: 'purple',
        name: '山茄紫',
        hex: '#a25aa4',
    },
    {
        rgb: [
            104,
            83,
            114,
        ],
        phonic: 'sumuzi',
        type: 'purple',
        name: '苏木紫',
        hex: '#685372',
    },
    {
        rgb: [
            200,
            157,
            213,
        ],
        phonic: 'shizhuzi',
        type: 'purple',
        name: '石竹紫',
        hex: '#c89dd5',
    },
    {
        rgb: [
            75,
            58,
            100,
        ],
        phonic: 'shenzhizi',
        type: 'purple',
        name: '椹汁紫',
        hex: '#4b3a64',
    },
    {
        rgb: [
            126,
            122,
            188,
        ],
        phonic: 'tengluozi',
        type: 'purple',
        name: '藤萝紫',
        hex: '#7E7ABC',
    },
    {
        rgb: [
            126,
            12,
            113,
        ],
        phonic: 'weizi',
        type: 'purple',
        name: '魏紫',
        hex: '#7e0c71',
    },
    {
        rgb: [
            162,
            38,
            108,
        ],
        phonic: 'xiancaizi',
        type: 'purple',
        name: '苋菜紫',
        hex: '#a2266c',
    },
    {
        rgb: [
            132,
            99,
            130,
        ],
        phonic: 'xuezi',
        type: 'purple',
        name: '雪紫',
        hex: '#846382',
    },
    {
        rgb: [
            134,
            96,
            155,
        ],
        phonic: 'xunzi',
        type: 'purple',
        name: '蕈紫',
        hex: '#86609b',
    },
    {
        rgb: [
            39,
            21,
            43,
        ],
        phonic: 'wumeizi',
        type: 'purple',
        name: '乌梅紫',
        hex: '#27152b',
    },
    {
        rgb: [
            77,
            45,
            56,
        ],
        phonic: 'tanzi',
        type: 'purple',
        name: '檀紫',
        hex: '#4d2d38',
    },
    {
        rgb: [
            47,
            22,
            44,
        ],
        phonic: 'shenqianniuzi',
        type: 'purple',
        name: '深牵牛紫',
        hex: '#2f162c',
    },
    {
        rgb: [
            47,
            12,
            44,
        ],
        phonic: 'qiepizi',
        type: 'purple',
        name: '茄皮紫',
        hex: '#2f0c2c',
    },
    {
        rgb: [
            127,
            4,
            128,
        ],
        phonic: 'qianniuzi',
        type: 'purple',
        name: '牵牛紫',
        hex: '#7f0480',
    },
    {
        rgb: [
            88,
            29,
            73,
        ],
        phonic: 'putaozi',
        type: 'purple',
        name: '葡萄紫',
        hex: '#581d49',
    },
    {
        rgb: [
            64,
            27,
            61,
        ],
        phonic: 'putaojiangzi',
        type: 'purple',
        name: '葡萄酱紫',
        hex: '#401b3d',
    },
    {
        rgb: [
            214,
            193,
            198,
        ],
        phonic: 'xiasezi',
        type: 'purple',
        name: '虾色',
        hex: '#d6c1c6',
    },
    {
        rgb: [
            205,
            177,
            192,
        ],
        phonic: 'yehuazi',
        type: 'purple',
        name: '野花',
        hex: '#cdb1c0',
    },
    {
        rgb: [
            196,
            98,
            137,
        ],
        phonic: 'yangcongzi',
        type: 'purple',
        name: '洋葱紫',
        hex: '#c46289',
    },
    {
        rgb: [
            127,
            104,
            195,
        ],
        phonic: 'yejuzi',
        type: 'purple',
        name: '野菊紫',
        hex: '#7f68c3',
    },
    {
        rgb: [
            181,
            87,
            159,
        ],
        phonic: 'yingcaozi',
        type: 'purple',
        name: '樱草紫',
        hex: '#b5579f',
    },
    {
        rgb: [
            108,
            76,
            123,
        ],
        phonic: 'yuzi',
        type: 'purple',
        name: '芋紫',
        hex: '#6c4c7b',
    },
    {
        rgb: [
            154,
            115,
            144,
        ],
        phonic: 'yuanyangzi',
        type: 'purple',
        name: '鸳鸯紫',
        hex: '#9a7390',
    },
    {
        rgb: [
            200,
            185,
            250,
        ],
        phonic: 'yuanshanzi',
        type: 'purple',
        name: '远山紫',
        hex: '#c8b9fa',
    },
    {
        rgb: [
            202,
            175,
            192,
        ],
        phonic: 'zhilanzi',
        type: 'purple',
        name: '芝兰紫',
        hex: '#caafc0',
    },
    {
        rgb: [
            207,
            172,
            194,
        ],
        phonic: 'zifen',
        type: 'purple',
        name: '紫粉',
        hex: '#cfacc2',
    },
    {
        rgb: [
            214,
            193,
            198,
        ],
        phonic: 'zihua',
        type: 'purple',
        name: '紫花',
        hex: '#d6c1c6',
    },
    {
        rgb: [
            181,
            134,
            206,
        ],
        phonic: 'ziweihua',
        type: 'purple',
        name: '紫薇花',
        hex: '#b586ce',
    },
    {
        rgb: [
            168,
            107,
            141,
        ],
        phonic: 'zishanbei',
        type: 'purple',
        name: '紫扇贝',
        hex: '#a86b8d',
    },
    {
        rgb: [
            149,
            106,
            186,
        ],
        phonic: 'zishuijing',
        type: 'purple',
        name: '紫水晶',
        hex: '#956aba',
    },
    {
        rgb: [
            159,
            154,
            208,
        ],
        phonic: 'zitenghui',
        type: 'purple',
        name: '紫藤灰',
        hex: '#9f9ad0',
    },
    {
        rgb: [
            135,
            13,
            95,
        ],
        phonic: 'yanlongzi',
        type: 'purple',
        name: '烟笼紫',
        hex: '#870d5f',
    },
    {
        rgb: [
            77,
            40,
            83,
        ],
        phonic: 'zijiang',
        type: 'purple',
        name: '紫绛',
        hex: '#4d2853',
    },
    {
        rgb: [
            32,
            10,
            46,
        ],
        phonic: 'zimo',
        type: 'purple',
        name: '紫墨',
        hex: '#200a2e',
    },
    {
        rgb: [
            85,
            30,
            36,
        ],
        phonic: 'zhuganzi',
        type: 'purple',
        name: '猪肝紫',
        hex: '#551e24',
    },
    {
        rgb: [
            58,
            58,
            86,
        ],
        phonic: 'yeputaozi',
        type: 'purple',
        name: '野葡萄紫',
        hex: '#3a3a56',
    },
]
