export const red = [
    {
        rgb: [
            125,
            1,
            1,
        ],
        phonic: 'anhong',
        type: 'red',
        name: '暗红',
        hex: '#7d0101',
    },
    {
        rgb: [
            165,
            35,
            9,
        ],
        phonic: 'biyuhong',
        type: 'red',
        name: '碧玉红',
        hex: '#a52309',
    },
    {
        rgb: [
            239,
            73,
            139,
        ],
        phonic: 'biandouhuahong',
        type: 'red',
        name: '扁豆花红',
        hex: '#ef498b',
    },
    {
        rgb: [
            115,
            21,
            22,
        ],
        phonic: 'binghong',
        type: 'red',
        name: '并红',
        hex: '#731516',
    },
    {
        rgb: [
            209,
            60,
            116,
        ],
        phonic: 'bogenhong',
        type: 'red',
        name: '菠根红',
        hex: '#d13c74',
    },
    {
        rgb: [
            236,
            45,
            122,
        ],
        phonic: 'zanghuahong',
        type: 'red',
        name: '藏花红',
        hex: '#ec2d7a',
    },
    {
        rgb: [
            213,
            20,
            25,
        ],
        phonic: 'caomeihong',
        type: 'red',
        name: '草莓红',
        hex: '#d51419',
    },
    {
        rgb: [
            233,
            60,
            75,
        ],
        phonic: 'chahuahong',
        type: 'red',
        name: '茶花红',
        hex: '#e93c4b',
    },
    {
        rgb: [
            134,
            22,
            11,
        ],
        phonic: 'chenshahong',
        type: 'red',
        name: '辰沙',
        hex: '#86160b',
    },
    {
        rgb: [
            239,
            130,
            161,
        ],
        phonic: 'chenxihong',
        type: 'red',
        name: '晨曦红',
        hex: '#ef82a1',
    },
    {
        rgb: [
            231,
            153,
            177,
        ],
        phonic: 'chuhehong',
        type: 'red',
        name: '初荷红',
        hex: '#e799b1',
    },
    {
        rgb: [
            255,
            95,
            145,
        ],
        phonic: 'chuisihaitanghong',
        type: 'red',
        name: '垂丝海棠红',
        hex: '#ff5f91',
    },
    {
        rgb: [
            240,
            147,
            157,
        ],
        phonic: 'chunmeihong',
        type: 'red',
        name: '春梅红',
        hex: '#f0939d',
    },
    {
        rgb: [
            197,
            113,
            139,
        ],
        phonic: 'cujiangcaohong',
        type: 'red',
        name: '酢酱草红',
        hex: '#c5718b',
    },
    {
        rgb: [
            217,
            2,
            35,
        ],
        phonic: 'dahong',
        type: 'red',
        name: '大红',
        hex: '#d90223',
    },
    {
        rgb: [
            222,
            85,
            75,
        ],
        phonic: 'daimaohong',
        type: 'red',
        name: '玳瑁红',
        hex: '#de554b',
    },
    {
        rgb: [
            185,
            42,
            10,
        ],
        phonic: 'danfanhong',
        type: 'red',
        name: '丹矾红',
        hex: '#b92a0a',
    },
    {
        rgb: [
            231,
            124,
            142,
        ],
        phonic: 'danqianhong',
        type: 'red',
        name: '淡茜红',
        hex: '#e77c8e',
    },
    {
        rgb: [
            164,
            47,
            53,
        ],
        phonic: 'danshuhong',
        type: 'red',
        name: '淡菽红',
        hex: '#a42f35',
    },
    {
        rgb: [
            206,
            95,
            138,
        ],
        phonic: 'diaozhonghuahong',
        type: 'red',
        name: '吊钟花红',
        hex: '#ce5f8a',
    },
    {
        rgb: [
            197,
            40,
            33,
        ],
        phonic: 'fanqiehong',
        type: 'red',
        name: '番茄',
        hex: '#c52821',
    },
    {
        rgb: [
            167,
            65,
            17,
        ],
        phonic: 'fanhong',
        type: 'red',
        name: '矾红',
        hex: '#a74111',
    },
    {
        rgb: [
            217,
            177,
            178,
        ],
        phonic: 'fenhong',
        type: 'red',
        name: '粉红',
        hex: '#d9b1b2',
    },
    {
        rgb: [
            236,
            155,
            172,
        ],
        phonic: 'fentuanhuahong',
        type: 'red',
        name: '粉团花红',
        hex: '#ec9bac',
    },
    {
        rgb: [
            232,
            66,
            55,
        ],
        phonic: 'fengyehong',
        type: 'red',
        name: '枫叶红',
        hex: '#e84237',
    },
    {
        rgb: [
            229,
            178,
            211,
        ],
        phonic: 'fengxianhuahong',
        type: 'red',
        name: '凤仙花红',
        hex: '#e5b2d3',
    },
    {
        rgb: [
            223,
            179,
            206,
        ],
        phonic: 'furonghong',
        type: 'red',
        name: '芙蓉红',
        hex: '#dfb3ce',
    },
    {
        rgb: [
            211,
            44,
            62,
        ],
        phonic: 'fupenzihong',
        type: 'red',
        name: '覆盆子红',
        hex: '#d32c3e',
    },
    {
        rgb: [
            164,
            87,
            121,
        ],
        phonic: 'ganhong',
        type: 'red',
        name: '绀红',
        hex: '#a45779',
    },
    {
        rgb: [
            192,
            44,
            56,
        ],
        phonic: 'gaolianghong',
        type: 'red',
        name: '高梁红',
        hex: '#c02c38',
    },
    {
        rgb: [
            157,
            41,
            50,
        ],
        phonic: 'gaolianghong',
        type: 'red',
        name: '高粱红',
        hex: '#9d2932',
    },
    {
        rgb: [
            168,
            27,
            43,
        ],
        phonic: 'gongjinhong',
        type: 'red',
        name: '宫锦红',
        hex: '#a81b2b',
    },
    {
        rgb: [
            190,
            54,
            58,
        ],
        phonic: 'gouqihong',
        type: 'red',
        name: '枸杞红',
        hex: '#be363a',
    },
    {
        rgb: [
            231,
            9,
            66,
        ],
        phonic: 'guaranghong',
        type: 'red',
        name: '瓜瓤红',
        hex: '#e70942',
    },
    {
        rgb: [
            226,
            138,
            124,
        ],
        phonic: 'guihong',
        type: 'red',
        name: '桂红',
        hex: '#e28a7c',
    },
    {
        rgb: [
            242,
            85,
            115,
        ],
        phonic: 'haitanghong',
        type: 'red',
        name: '海棠红',
        hex: '#f25573',
    },
    {
        rgb: [
            245,
            153,
            216,
        ],
        phonic: 'handansehong',
        type: 'red',
        name: '菡萏色',
        hex: '#f599d8',
    },
    {
        rgb: [
            240,
            161,
            167,
        ],
        phonic: 'hehuanhong',
        type: 'red',
        name: '合欢红',
        hex: '#f0a1a7',
    },
    {
        rgb: [
            218,
            29,
            59,
        ],
        phonic: 'hedinghong',
        type: 'red',
        name: '鹤顶红',
        hex: '#da1d3b',
    },
    {
        rgb: [
            189,
            173,
            176,
        ],
        phonic: 'honghui',
        type: 'red',
        name: '红灰',
        hex: '#bdadb0',
    },
    {
        rgb: [
            191,
            78,
            108,
        ],
        phonic: 'hongshanbei',
        type: 'red',
        name: '红扇贝',
        hex: '#bf4e6c',
    },
    {
        rgb: [
            209,
            26,
            46,
        ],
        phonic: 'jiguanhong',
        type: 'red',
        name: '鸡冠红',
        hex: '#d11a2e',
    },
    {
        rgb: [
            206,
            24,
            62,
        ],
        phonic: 'jixueshihong',
        type: 'red',
        name: '鸡血石红',
        hex: '#ce183e',
    },
    {
        rgb: [
            120,
            30,
            32,
        ],
        phonic: 'jihong',
        type: 'red',
        name: '霁红',
        hex: '#781e20',
    },
    {
        rgb: [
            226,
            141,
            158,
        ],
        phonic: 'jiangdouhong',
        type: 'red',
        name: '豇豆红',
        hex: '#e28d9e',
    },
    {
        rgb: [
            142,
            20,
            3,
        ],
        phonic: 'jianghong',
        type: 'red',
        name: '绛红',
        hex: '#8e1403',
    },
    {
        rgb: [
            246,
            88,
            136,
        ],
        phonic: 'jiaohong',
        type: 'red',
        name: '蕉红',
        hex: '#f65888',
    },
    {
        rgb: [
            180,
            28,
            15,
        ],
        phonic: 'jinhong',
        type: 'red',
        name: '矜红',
        hex: '#b41c0f',
    },
    {
        rgb: [
            192,
            53,
            84,
        ],
        phonic: 'jinkuihong',
        type: 'red',
        name: '锦葵红',
        hex: '#c03554',
    },
    {
        rgb: [
            153,
            73,
            74,
        ],
        phonic: 'jinghong',
        type: 'red',
        name: '京红',
        hex: '#99494a',
    },
    {
        rgb: [
            252,
            110,
            2,
        ],
        phonic: 'juhong',
        type: 'red',
        name: '橘红',
        hex: '#fc6e02',
    },
    {
        rgb: [
            236,
            38,
            27,
        ],
        phonic: 'lichunhong',
        type: 'red',
        name: '丽春红',
        hex: '#ec261b',
    },
    {
        rgb: [
            146,
            41,
            48,
        ],
        phonic: 'lisehong',
        type: 'red',
        name: '荔色',
        hex: '#922930',
    },
    {
        rgb: [
            216,
            139,
            121,
        ],
        phonic: 'lianghong',
        type: 'red',
        name: '亮红',
        hex: '#d88b79',
    },
    {
        rgb: [
            187,
            25,
            101,
        ],
        phonic: 'liaosuihong',
        type: 'red',
        name: '蓼穗红',
        hex: '#bb1965',
    },
    {
        rgb: [
            180,
            28,
            53,
        ],
        phonic: 'linghong',
        type: 'red',
        name: '菱红',
        hex: '#b41c35',
    },
    {
        rgb: [
            244,
            8,
            8,
        ],
        phonic: 'liuhuahong',
        type: 'red',
        name: '榴花红',
        hex: '#f40808',
    },
    {
        rgb: [
            166,
            64,
            86,
        ],
        phonic: 'liuzihong',
        type: 'red',
        name: '榴子红',
        hex: '#a64056',
    },
    {
        rgb: [
            194,
            77,
            147,
        ],
        phonic: 'longzuihuahong',
        type: 'red',
        name: '龙嘴花红',
        hex: '#c24d93',
    },
    {
        rgb: [
            207,
            71,
            19,
        ],
        phonic: 'luoxiahong',
        type: 'red',
        name: '落霞红',
        hex: '#cf4713',
    },
    {
        rgb: [
            207,
            70,
            98,
        ],
        phonic: 'luoyehong',
        type: 'red',
        name: '落叶红',
        hex: '#cf4662',
    },
    {
        rgb: [
            246,
            203,
            231,
        ],
        phonic: 'luoyingdanfenhong',
        type: 'red',
        name: '落英淡粉',
        hex: '#f6cbe7',
    },
    {
        rgb: [
            175,
            95,
            101,
        ],
        phonic: 'manjianghong',
        type: 'red',
        name: '满江红',
        hex: '#af5f65',
    },
    {
        rgb: [
            226,
            130,
            168,
        ],
        phonic: 'meiguifenhong',
        type: 'red',
        name: '玫瑰粉',
        hex: '#e282a8',
    },
    {
        rgb: [
            210,
            52,
            126,
        ],
        phonic: 'meiguihong',
        type: 'red',
        name: '玫瑰红',
        hex: '#d2347e',
    },
    {
        rgb: [
            196,
            90,
            102,
        ],
        phonic: 'meijianghong',
        type: 'red',
        name: '莓酱红',
        hex: '#c45a66',
    },
    {
        rgb: [
            167,
            65,
            93,
        ],
        phonic: 'meihong',
        type: 'red',
        name: '梅红',
        hex: '#a7415d',
    },
    {
        rgb: [
            204,
            107,
            100,
        ],
        phonic: 'mihong',
        type: 'red',
        name: '米红',
        hex: '#cc6b64',
    },
    {
        rgb: [
            189,
            141,
            137,
        ],
        phonic: 'moxueyahong',
        type: 'red',
        name: '墨血牙',
        hex: '#bd8d89',
    },
    {
        rgb: [
            195,
            129,
            115,
        ],
        phonic: 'muhong',
        type: 'red',
        name: '木红',
        hex: '#c38173',
    },
    {
        rgb: [
            223,
            63,
            125,
        ],
        phonic: 'nenlinghong',
        type: 'red',
        name: '嫩菱红',
        hex: '#df3f7d',
    },
    {
        rgb: [
            99,
            16,
            46,
        ],
        phonic: 'putaojiuhong',
        type: 'red',
        name: '葡萄酒红',
        hex: '#63102e',
    },
    {
        rgb: [
            215,
            145,
            159,
        ],
        phonic: 'qianmeihong',
        type: 'red',
        name: '浅梅红',
        hex: '#d7919f',
    },
    {
        rgb: [
            149,
            26,
            30,
        ],
        phonic: 'qiansehong',
        type: 'red',
        name: '茜色',
        hex: '#951a1e',
    },
    {
        rgb: [
            217,
            26,
            33,
        ],
        phonic: 'qingtinghong',
        type: 'red',
        name: '蜻蜓红',
        hex: '#d91a21',
    },
    {
        rgb: [
            229,
            101,
            116,
        ],
        phonic: 'quhong',
        type: 'red',
        name: '曲红',
        hex: '#e56574',
    },
    {
        rgb: [
            235,
            90,
            85,
        ],
        phonic: 'rouhong',
        type: 'red',
        name: '肉红',
        hex: '#eb5a55',
    },
    {
        rgb: [
            237,
            85,
            106,
        ],
        phonic: 'shanchahong',
        type: 'red',
        name: '山茶红',
        hex: '#ed556a',
    },
    {
        rgb: [
            194,
            124,
            135,
        ],
        phonic: 'shanlidouhong',
        type: 'red',
        name: '山黎豆红',
        hex: '#c27c87',
    },
    {
        rgb: [
            231,
            103,
            186,
        ],
        phonic: 'shanyinghong',
        type: 'red',
        name: '山樱红',
        hex: '#e767ba',
    },
    {
        rgb: [
            150,
            56,
            54,
        ],
        phonic: 'shanhuhong',
        type: 'red',
        name: '珊瑚红',
        hex: '#963836',
    },
    {
        rgb: [
            255,
            102,
            104,
        ],
        phonic: 'shanhong',
        type: 'red',
        name: '闪红',
        hex: '#ff6668',
    },
    {
        rgb: [
            235,
            143,
            180,
        ],
        phonic: 'shaohong',
        type: 'red',
        name: '韶红',
        hex: '#eb8fb4',
    },
    {
        rgb: [
            218,
            154,
            155,
        ],
        phonic: 'shehong',
        type: 'red',
        name: '舌红',
        hex: '#da9a9b',
    },
    {
        rgb: [
            167,
            65,
            93,
        ],
        phonic: 'shenmeihong',
        type: 'red',
        name: '深梅红',
        hex: '#a7415d',
    },
    {
        rgb: [
            199,
            70,
            109,
        ],
        phonic: 'shiyangjinhong',
        type: 'red',
        name: '十样锦',
        hex: '#c7466d',
    },
    {
        rgb: [
            223,
            27,
            27,
        ],
        phonic: 'shiliuhong',
        type: 'red',
        name: '石榴红',
        hex: '#df1b1b',
    },
    {
        rgb: [
            240,
            201,
            206,
        ],
        phonic: 'shiruihong',
        type: 'red',
        name: '石蕊红',
        hex: '#f0c9ce',
    },
    {
        rgb: [
            254,
            172,
            220,
        ],
        phonic: 'shimeizhuanghong',
        type: 'red',
        name: '试梅妆',
        hex: '#feacdc',
    },
    {
        rgb: [
            230,
            83,
            33,
        ],
        phonic: 'shihong',
        type: 'red',
        name: '柿红',
        hex: '#e65321',
    },
    {
        rgb: [
            88,
            27,
            22,
        ],
        phonic: 'shuhong',
        type: 'red',
        name: '曙红',
        hex: '#581b16',
    },
    {
        rgb: [
            203,
            40,
            71,
        ],
        phonic: 'shuanghong',
        type: 'red',
        name: '双红',
        hex: '#cb2847',
    },
    {
        rgb: [
            253,
            155,
            196,
        ],
        phonic: 'shuihong',
        type: 'red',
        name: '水红',
        hex: '#fd9bc4',
    },
    {
        rgb: [
            207,
            93,
            126,
        ],
        phonic: 'taohong',
        type: 'red',
        name: '桃红',
        hex: '#cf5d7e',
    },
    {
        rgb: [
            238,
            88,
            149,
        ],
        phonic: 'tihong',
        type: 'red',
        name: '啼红',
        hex: '#ee5895',
    },
    {
        rgb: [
            192,
            43,
            83,
        ],
        phonic: 'tiancaihong',
        type: 'red',
        name: '甜菜红',
        hex: '#c02b53',
    },
    {
        rgb: [
            175,
            36,
            3,
        ],
        phonic: 'tieshuihong',
        type: 'red',
        name: '铁水红',
        hex: '#af2403',
    },
    {
        rgb: [
            141,
            33,
            30,
        ],
        phonic: 'tinghong',
        type: 'red',
        name: '鞓红',
        hex: '#8d211e',
    },
    {
        rgb: [
            247,
            192,
            194,
        ],
        phonic: 'tuihong',
        type: 'red',
        name: '退红',
        hex: '#f7c0c2',
    },
    {
        rgb: [
            219,
            154,
            158,
        ],
        phonic: 'tuosehong',
        type: 'red',
        name: '酡色',
        hex: '#db9a9e',
    },
    {
        rgb: [
            103,
            52,
            59,
        ],
        phonic: 'wuhong',
        type: 'red',
        name: '乌红',
        hex: '#67343b',
    },
    {
        rgb: [
            162,
            61,
            69,
        ],
        phonic: 'wuhuaguohong',
        type: 'red',
        name: '无花果红',
        hex: '#a23d45',
    },
    {
        rgb: [
            255,
            75,
            42,
        ],
        phonic: 'xiyanghong',
        type: 'red',
        name: '夕阳红',
        hex: '#ff4b2a',
    },
    {
        rgb: [
            237,
            44,
            101,
        ],
        phonic: 'xidanhong',
        type: 'red',
        name: '喜蛋红',
        hex: '#ed2c65',
    },
    {
        rgb: [
            165,
            27,
            42,
        ],
        phonic: 'xiancaihong',
        type: 'red',
        name: '苋菜红',
        hex: '#a51b2a',
    },
    {
        rgb: [
            213,
            151,
            146,
        ],
        phonic: 'xiaohong',
        type: 'red',
        name: '小红',
        hex: '#d59792',
    },
    {
        rgb: [
            210,
            71,
            48,
        ],
        phonic: 'xiekehong',
        type: 'red',
        name: '蟹壳红',
        hex: '#d24730',
    },
    {
        rgb: [
            118,
            38,
            39,
        ],
        phonic: 'xinghong',
        type: 'red',
        name: '猩红',
        hex: '#762627',
    },
    {
        rgb: [
            244,
            141,
            100,
        ],
        phonic: 'xingzihong',
        type: 'red',
        name: '杏子红',
        hex: '#f48d64',
    },
    {
        rgb: [
            175,
            60,
            55,
        ],
        phonic: 'xiuhong',
        type: 'red',
        name: '锈红',
        hex: '#af3c37',
    },
    {
        rgb: [
            104,
            24,
            23,
        ],
        phonic: 'xuehong',
        type: 'red',
        name: '血红',
        hex: '#681817',
    },
    {
        rgb: [
            255,
            219,
            203,
        ],
        phonic: 'xueyahong',
        type: 'red',
        name: '血牙',
        hex: '#ffdbcb',
    },
    {
        rgb: [
            137,
            78,
            84,
        ],
        phonic: 'yanhong',
        type: 'red',
        name: '烟红',
        hex: '#894e54',
    },
    {
        rgb: [
            241,
            118,
            146,
        ],
        phonic: 'yanzhihong',
        type: 'red',
        name: '胭脂',
        hex: '#f17692',
    },
    {
        rgb: [
            220,
            139,
            208,
        ],
        phonic: 'yanhong',
        type: 'red',
        name: '嫣红',
        hex: '#dc8bd0',
    },
    {
        rgb: [
            229,
            138,
            137,
        ],
        phonic: 'yangfeisehong',
        type: 'red',
        name: '杨妃色',
        hex: '#e58a89',
    },
    {
        rgb: [
            251,
            68,
            186,
        ],
        phonic: 'yeqiangweihong',
        type: 'red',
        name: '野蔷薇红',
        hex: '#fb44ba',
    },
    {
        rgb: [
            239,
            73,
            173,
        ],
        phonic: 'yinianhong',
        type: 'red',
        name: '一捻红',
        hex: '#ef49ad',
    },
    {
        rgb: [
            244,
            195,
            250,
        ],
        phonic: 'qihong',
        type: 'red',
        name: '欹红',
        hex: '#f4c3fa',
    },
    {
        rgb: [
            93,
            4,
            10,
        ],
        phonic: 'yanhong',
        type: 'red',
        name: '殷红',
        hex: '#5d040a',
    },
    {
        rgb: [
            216,
            141,
            156,
        ],
        phonic: 'yinhong',
        type: 'red',
        name: '银红',
        hex: '#d88d9c',
    },
    {
        rgb: [
            245,
            62,
            5,
        ],
        phonic: 'yinzhuhong',
        type: 'red',
        name: '银朱',
        hex: '#f53e05',
    },
    {
        rgb: [
            182,
            152,
            162,
        ],
        phonic: 'yinhonghui',
        type: 'red',
        name: '隐红灰',
        hex: '#b698a2',
    },
    {
        rgb: [
            224,
            54,
            39,
        ],
        phonic: 'yingsuhong',
        type: 'red',
        name: '罂粟红',
        hex: '#e03627',
    },
    {
        rgb: [
            196,
            20,
            30,
        ],
        phonic: 'yingtaohong',
        type: 'red',
        name: '樱桃红',
        hex: '#c4141e',
    },
    {
        rgb: [
            252,
            108,
            195,
        ],
        phonic: 'yinghong',
        type: 'red',
        name: '硬红',
        hex: '#fc6cc3',
    },
    {
        rgb: [
            45,
            15,
            7,
        ],
        phonic: 'yujinhong',
        type: 'red',
        name: '余烬红',
        hex: '#2d0f07',
    },
    {
        rgb: [
            194,
            54,
            81,
        ],
        phonic: 'yusaihong',
        type: 'red',
        name: '鱼鳃红',
        hex: '#c23651',
    },
    {
        rgb: [
            186,
            115,
            121,
        ],
        phonic: 'yufenhong',
        type: 'red',
        name: '玉粉红',
        hex: '#ba7379',
    },
    {
        rgb: [
            192,
            72,
            81,
        ],
        phonic: 'yuhong',
        type: 'red',
        name: '玉红',
        hex: '#c04851',
    },
    {
        rgb: [
            219,
            60,
            162,
        ],
        phonic: 'yuanchunhong',
        type: 'red',
        name: '怨春红',
        hex: '#db3ca2',
    },
    {
        rgb: [
            206,
            87,
            109,
        ],
        phonic: 'yuejihong',
        type: 'red',
        name: '月季红',
        hex: '#ce576d',
    },
    {
        rgb: [
            101,
            30,
            24,
        ],
        phonic: 'zaohong',
        type: 'red',
        name: '枣红',
        hex: '#651e18',
    },
    {
        rgb: [
            254,
            99,
            219,
        ],
        phonic: 'zhaodianhong',
        type: 'red',
        name: '照殿红',
        hex: '#fe63db',
    },
    {
        rgb: [
            235,
            104,
            148,
        ],
        phonic: 'zhihong',
        type: 'red',
        name: '脂红',
        hex: '#eb6894',
    },
    {
        rgb: [
            213,
            86,
            192,
        ],
        phonic: 'zhizhuhong',
        type: 'red',
        name: '踯躅红',
        hex: '#d556c0',
    },
    {
        rgb: [
            233,
            61,
            21,
        ],
        phonic: 'zhuhong',
        type: 'red',
        name: '朱红',
        hex: '#e93d15',
    },
    {
        rgb: [
            165,
            34,
            40,
        ],
        phonic: 'zhushahong',
        type: 'red',
        name: '朱砂',
        hex: '#a52228',
    },
    {
        rgb: [
            199,
            43,
            44,
        ],
        phonic: 'zhuyingyaohong',
        type: 'red',
        name: '烛影揺红',
        hex: '#c72b2c',
    },
    {
        rgb: [
            185,
            54,
            46,
        ],
        phonic: 'zhuanhong',
        type: 'red',
        name: '砖红',
        hex: '#b9362e',
    },
    {
        rgb: [
            224,
            164,
            226,
        ],
        phonic: 'zhuifenhong',
        type: 'red',
        name: '坠粉红',
        hex: '#e0a4e2',
    },
    {
        rgb: [
            237,
            123,
            183,
        ],
        phonic: 'zhuihong',
        type: 'red',
        name: '缀红',
        hex: '#ed7bb7',
    },
    {
        rgb: [
            239,
            44,
            122,
        ],
        phonic: 'zijinghong',
        type: 'red',
        name: '紫荆红',
        hex: '#ef2c7a',
    },
    {
        rgb: [
            113,
            64,
            54,
        ],
        phonic: 'zonghong',
        type: 'red',
        name: '棕红',
        hex: '#714036',
    },
]
