export const yellow = [
    {
        rgb: [
            232,
            234,
            161,
        ],
        phonic: 'conghuang',
        type: 'yellow',
        name: '葱黄',
        hex: '#e8eaa1',
    },
    {
        rgb: [
            226,
            162,
            74,
        ],
        phonic: 'ehuang',
        type: 'yellow',
        name: '鹅黄',
        hex: '#e2a24a',
    },
    {
        rgb: [
            255,
            144,
            3,
        ],
        phonic: 'jinhuang',
        type: 'yellow',
        name: '金黄',
        hex: '#ff9003',
    },
    {
        rgb: [
            234,
            238,
            91,
        ],
        phonic: 'liuhuang',
        type: 'yellow',
        name: '柳黄',
        hex: '#eaee5b',
    },
    {
        rgb: [
            232,
            234,
            161,
        ],
        phonic: 'tenghuang',
        type: 'yellow',
        name: '藤黄',
        hex: '#e8eaa1',
    },
    {
        rgb: [
            206,
            170,
            20,
        ],
        phonic: 'qiuxianghuang',
        type: 'yellow',
        name: '秋香',
        hex: '#ceaa14',
    },
    {
        rgb: [
            233,
            197,
            100,
        ],
        phonic: 'shihuang',
        type: 'yellow',
        name: '石黄',
        hex: '#e9c564',
    },
    {
        rgb: [
            255,
            249,
            213,
        ],
        phonic: 'mihehuang',
        type: 'yellow',
        name: '蜜合',
        hex: '#fff9d5',
    },
    {
        rgb: [
            230,
            223,
            106,
        ],
        phonic: 'songhuahuang',
        type: 'yellow',
        name: '松花',
        hex: '#e6df6a',
    },
    {
        rgb: [
            219,
            160,
            20,
        ],
        phonic: 'zhongminghuang',
        type: 'yellow',
        name: '中明',
        hex: '#dba014',
    },
    {
        rgb: [
            254,
            197,
            108,
        ],
        phonic: 'xinghuang',
        type: 'yellow',
        name: '杏黄',
        hex: '#fec56c',
    },
    {
        rgb: [
            254,
            223,
            10,
        ],
        phonic: 'minghuang',
        type: 'yellow',
        name: '明黄',
        hex: '#fedf0a',
    },
    {
        rgb: [
            231,
            172,
            34,
        ],
        phonic: 'fanhuang',
        type: 'yellow',
        name: '番黄',
        hex: '#e7ac22',
    },
    {
        rgb: [
            213,
            202,
            78,
        ],
        phonic: 'hehuahuang',
        type: 'yellow',
        name: '荷花',
        hex: '#d5ca4e',
    },
    {
        rgb: [
            253,
            212,
            26,
        ],
        phonic: 'mihuang',
        type: 'yellow',
        name: '蜜黄',
        hex: '#fdd41a',
    },
    {
        rgb: [
            198,
            129,
            60,
        ],
        phonic: 'tanxianghuang',
        type: 'yellow',
        name: '檀香',
        hex: '#c6813c',
    },
    {
        rgb: [
            238,
            131,
            49,
        ],
        phonic: 'zhehuang',
        type: 'yellow',
        name: '柘黄',
        hex: '#ee8331',
    },
    {
        rgb: [
            214,
            160,
            28,
        ],
        phonic: 'tuhuang',
        type: 'yellow',
        name: '土黄',
        hex: '#d6a01c',
    },
    {
        rgb: [
            243,
            192,
            77,
        ],
        phonic: 'gancaohuang',
        type: 'yellow',
        name: '甘草黄',
        hex: '#f3c04d',
    },
    {
        rgb: [
            252,
            196,
            21,
        ],
        phonic: 'huanglianhuang',
        type: 'yellow',
        name: '黄连黄',
        hex: '#fcc415',
    },
    {
        rgb: [
            218,
            164,
            14,
        ],
        phonic: 'jiehuang',
        type: 'yellow',
        name: '芥黄',
        hex: '#daa40e',
    },
    {
        rgb: [
            247,
            223,
            153,
        ],
        phonic: 'miehuang',
        type: 'yellow',
        name: '篾黄',
        hex: '#f7df99',
    },
    {
        rgb: [
            227,
            192,
            40,
        ],
        phonic: 'jianghuang',
        type: 'yellow',
        name: '姜黄',
        hex: '#e3c028',
    },
    {
        rgb: [
            232,
            176,
            5,
        ],
        phonic: 'guhuang',
        type: 'yellow',
        name: '谷黄',
        hex: '#e8b005',
    },
    {
        rgb: [
            208,
            185,
            9,
        ],
        phonic: 'yaohuang',
        type: 'yellow',
        name: '姚黄',
        hex: '#d0b909',
    },
    {
        rgb: [
            241,
            202,
            23,
        ],
        phonic: 'youhuang',
        type: 'yellow',
        name: '柚黄',
        hex: '#f1ca17',
    },
    {
        rgb: [
            253,
            183,
            10,
        ],
        phonic: 'youhuang',
        type: 'yellow',
        name: '鼬黄',
        hex: '#fdb70a',
    },
    {
        rgb: [
            223,
            194,
            68,
        ],
        phonic: 'haohuang',
        type: 'yellow',
        name: '蒿黄',
        hex: '#dfc244',
    },
    {
        rgb: [
            129,
            98,
            51,
        ],
        phonic: 'canghuang',
        type: 'yellow',
        name: '苍黄',
        hex: '#816233',
    },
    {
        rgb: [
            255,
            153,
            0,
        ],
        phonic: 'xionghuang',
        type: 'yellow',
        name: '雄黄',
        hex: '#ff9900',
    },
    {
        rgb: [
            210,
            181,
            45,
        ],
        phonic: 'caohuang',
        type: 'yellow',
        name: '草黄',
        hex: '#d2b52d',
    },
    {
        rgb: [
            244,
            206,
            109,
        ],
        phonic: 'shuihuang',
        type: 'yellow',
        name: '水黄',
        hex: '#f4ce6d',
    },
    {
        rgb: [
            254,
            153,
            1,
        ],
        phonic: 'juhuang',
        type: 'yellow',
        name: '桔黄',
        hex: '#fe9901',
    },
    {
        rgb: [
            249,
            125,
            29,
        ],
        phonic: 'juchenghuang',
        type: 'yellow',
        name: '橘橙',
        hex: '#f97d1d',
    },
    {
        rgb: [
            242,
            106,
            58,
        ],
        phonic: 'zhubiaohuang',
        type: 'yellow',
        name: '朱膘',
        hex: '#f26a3a',
    },
    {
        rgb: [
            224,
            142,
            14,
        ],
        phonic: 'huanglu',
        type: 'yellow',
        name: '黄栌',
        hex: '#e08e0e',
    },
    {
        rgb: [
            245,
            243,
            134,
        ],
        phonic: 'yingchunhuang',
        type: 'yellow',
        name: '迎春黄',
        hex: '#f5f386',
    },
    {
        rgb: [
            252,
            203,
            22,
        ],
        phonic: 'suxinhuang',
        type: 'yellow',
        name: '素馨黄',
        hex: '#fccb16',
    },
    {
        rgb: [
            247,
            223,
            113,
        ],
        phonic: 'molihuang',
        type: 'yellow',
        name: '茉莉黄',
        hex: '#f7df71',
    },
    {
        rgb: [
            248,
            215,
            112,
        ],
        phonic: 'danjianhuang',
        type: 'yellow',
        name: '淡茧黄',
        hex: '#f8d770',
    },
    {
        rgb: [
            247,
            195,
            135,
        ],
        phonic: 'dankehuang',
        type: 'yellow',
        name: '蛋壳黄',
        hex: '#f7c387',
    },
    {
        rgb: [
            222,
            158,
            68,
        ],
        phonic: 'ruanmuhuang',
        type: 'yellow',
        name: '软木黄',
        hex: '#de9e44',
    },
    {
        rgb: [
            249,
            223,
            112,
        ],
        phonic: 'maiganhuang',
        type: 'yellow',
        name: '麦杆黄',
        hex: '#f9df70',
    },
    {
        rgb: [
            255,
            186,
            7,
        ],
        phonic: 'hupohuang',
        type: 'yellow',
        name: '琥珀黄',
        hex: '#ffba07',
    },
    {
        rgb: [
            239,
            214,
            148,
        ],
        phonic: 'xiangyahuang',
        type: 'yellow',
        name: '象牙黄',
        hex: '#efd694',
    },
    {
        rgb: [
            251,
            200,
            47,
        ],
        phonic: 'yalihuang',
        type: 'yellow',
        name: '雅梨黄',
        hex: '#fbc82f',
    },
    {
        rgb: [
            248,
            216,
            107,
        ],
        phonic: 'kuishanhuang',
        type: 'yellow',
        name: '葵扇黄',
        hex: '#f8d86b',
    },
    {
        rgb: [
            250,
            166,
            52,
        ],
        phonic: 'liuehuang',
        type: 'yellow',
        name: '榴萼黄',
        hex: '#faa634',
    },
    {
        rgb: [
            221,
            145,
            35,
        ],
        phonic: 'fengfanhuang',
        type: 'yellow',
        name: '风帆黄',
        hex: '#dd9123',
    },
    {
        rgb: [
            252,
            212,
            55,
        ],
        phonic: 'ningmenghuang',
        type: 'yellow',
        name: '柠檬黄',
        hex: '#fcd437',
    },
    {
        rgb: [
            251,
            205,
            49,
        ],
        phonic: 'dadouhuang',
        type: 'yellow',
        name: '大豆黄',
        hex: '#fbcd31',
    },
    {
        rgb: [
            183,
            140,
            38,
        ],
        phonic: 'shanjihuang',
        type: 'yellow',
        name: '山鸡黄',
        hex: '#b78c26',
    },
    {
        rgb: [
            253,
            140,
            36,
        ],
        phonic: 'beiguahuang',
        type: 'yellow',
        name: '北瓜黄',
        hex: '#fd8c24',
    },
    {
        rgb: [
            251,
            210,
            22,
        ],
        phonic: 'jinguahuang',
        type: 'yellow',
        name: '金瓜黄',
        hex: '#fbd216',
    },
    {
        rgb: [
            249,
            193,
            22,
        ],
        phonic: 'muguahuang',
        type: 'yellow',
        name: '木瓜黄',
        hex: '#f9c116',
    },
    {
        rgb: [
            254,
            215,
            26,
        ],
        phonic: 'foshouhuang',
        type: 'yellow',
        name: '佛手黄',
        hex: '#fed71a',
    },
    {
        rgb: [
            249,
            246,
            195,
        ],
        phonic: 'xingrenhuang',
        type: 'yellow',
        name: '杏仁黄',
        hex: '#f9f6c3',
    },
    {
        rgb: [
            228,
            183,
            80,
        ],
        phonic: 'shashihuang',
        type: 'yellow',
        name: '沙石黄',
        hex: '#e4b750',
    },
    {
        rgb: [
            211,
            199,
            113,
        ],
        phonic: 'mangguohuang',
        type: 'yellow',
        name: '芒果黄',
        hex: '#d3c771',
    },
    {
        rgb: [
            247,
            232,
            193,
        ],
        phonic: 'douzhihuang',
        type: 'yellow',
        name: '豆汁黄',
        hex: '#f7e8c1',
    },
    {
        rgb: [
            255,
            202,
            12,
        ],
        phonic: 'ruyahuang',
        type: 'yellow',
        name: '乳鸭黄',
        hex: '#ffca0c',
    },
    {
        rgb: [
            252,
            162,
            6,
        ],
        phonic: 'pipahuang',
        type: 'yellow',
        name: '枇杷黄',
        hex: '#fca206',
    },
    {
        rgb: [
            244,
            206,
            105,
        ],
        phonic: 'chaomihuang',
        type: 'yellow',
        name: '炒米黄',
        hex: '#f4ce69',
    },
    {
        rgb: [
            235,
            173,
            26,
        ],
        phonic: 'hupihuang',
        type: 'yellow',
        name: '虎皮黄',
        hex: '#ebad1a',
    },
    {
        rgb: [
            253,
            195,
            7,
        ],
        phonic: 'jinzhanhuang',
        type: 'yellow',
        name: '金盏黄',
        hex: '#fdc307',
    },
    {
        rgb: [
            255,
            165,
            16,
        ],
        phonic: 'jinyehuang',
        type: 'yellow',
        name: '金叶黄',
        hex: '#ffa510',
    },
    {
        rgb: [
            255,
            161,
            1,
        ],
        phonic: 'jinyinghuang',
        type: 'yellow',
        name: '金莺黄',
        hex: '#ffa101',
    },
    {
        rgb: [
            218,
            164,
            90,
        ],
        phonic: 'daimaohuang',
        type: 'yellow',
        name: '玳瑁黄',
        hex: '#daa45a',
    },
    {
        rgb: [
            237,
            208,
            68,
        ],
        phonic: 'qiukuihuang',
        type: 'yellow',
        name: '秋葵黄',
        hex: '#edd044',
    },
    {
        rgb: [
            228,
            190,
            17,
        ],
        phonic: 'xiangjiaohuang',
        type: 'yellow',
        name: '香蕉黄',
        hex: '#e4be11',
    },
    {
        rgb: [
            251,
            182,
            17,
        ],
        phonic: 'jidanhuang',
        type: 'yellow',
        name: '鸡蛋黄',
        hex: '#fbb611',
    },
    {
        rgb: [
            251,
            184,
            41,
        ],
        phonic: 'ezhanghuang',
        type: 'yellow',
        name: '鹅掌黄',
        hex: '#fbb829',
    },
    {
        rgb: [
            246,
            221,
            141,
        ],
        phonic: 'xiaojihuang',
        type: 'yellow',
        name: '小鸡黄',
        hex: '#f6dd8d',
    },
    {
        rgb: [
            227,
            216,
            74,
        ],
        phonic: 'diehuang',
        type: 'yellow',
        name: '蝶黄',
        hex: '#e3d84a',
    },
    {
        rgb: [
            254,
            205,
            17,
        ],
        phonic: 'xiangrikuihuang',
        type: 'yellow',
        name: '向日葵黄',
        hex: '#fecd11',
    },
    {
        rgb: [
            251,
            218,
            65,
        ],
        phonic: 'youcaihuahuang',
        type: 'yellow',
        name: '油菜花黄',
        hex: '#fbda41',
    },
    {
        rgb: [
            247,
            188,
            48,
        ],
        phonic: 'chushuxinghuang',
        type: 'yellow',
        name: '初熟杏黄',
        hex: '#f7bc30',
    },
    {
        rgb: [
            248,
            107,
            28,
        ],
        phonic: 'jinlianhuachenghuang',
        type: 'yellow',
        name: '金莲花橙',
        hex: '#f86b1c',
    },
    {
        rgb: [
            250,
            126,
            36,
        ],
        phonic: 'meirenjiaochenghuang',
        type: 'yellow',
        name: '美人焦橙',
        hex: '#fa7e24',
    },
    {
        rgb: [
            248,
            210,
            125,
        ],
        phonic: 'maiyatanghuang',
        type: 'yellow',
        name: '麦芽糖黄',
        hex: '#f8d27d',
    },
    {
        rgb: [
            209,
            195,
            132,
        ],
        phonic: 'lihuang',
        type: 'yellow',
        name: '梨黄',
        hex: '#d1c384',
    },
    {
        rgb: [
            251,
            139,
            5,
        ],
        phonic: 'wanshoujuhuang',
        type: 'yellow',
        name: '万寿菊黄',
        hex: '#fb8b05',
    },
    {
        rgb: [
            253,
            217,
            7,
        ],
        phonic: 'huaihuahuang',
        type: 'yellow',
        name: '槐花黄',
        hex: '#fdd907',
    },
    {
        rgb: [
            223,
            192,
            65,
        ],
        phonic: 'ganlanhuang',
        type: 'yellow',
        name: '橄榄黄',
        hex: '#dfc041',
    },
    {
        rgb: [
            246,
            196,
            49,
        ],
        phonic: 'yingwuguanhuang',
        type: 'yellow',
        name: '鹦鹉冠黄',
        hex: '#f6c431',
    },
    {
        rgb: [
            251,
            185,
            88,
        ],
        phonic: 'mihuangse',
        type: 'yellow',
        name: '蜜黄色',
        hex: '#fbb958',
    },
    {
        rgb: [
            245,
            212,
            161,
        ],
        phonic: 'shuimihuang',
        type: 'yellow',
        name: '水蜜',
        hex: '#f5d4a1',
    },
    {
        rgb: [
            182,
            143,
            78,
        ],
        phonic: 'zhehuang',
        type: 'yellow',
        name: '赭黄',
        hex: '#b68f4e',
    },
    {
        rgb: [
            235,
            178,
            13,
        ],
        phonic: 'zhizihuang',
        type: 'yellow',
        name: '栀子黄',
        hex: '#ebb20d',
    },
    {
        rgb: [
            255,
            181,
            0,
        ],
        phonic: 'shihuang',
        type: 'yellow',
        name: '柿黄',
        hex: '#ffb500',
    },
    {
        rgb: [
            235,
            158,
            104,
        ],
        phonic: 'fenchenghuang',
        type: 'yellow',
        name: '粉橙',
        hex: '#eb9e68',
    },
    {
        rgb: [
            251,
            161,
            3,
        ],
        phonic: 'chengpihuang',
        type: 'yellow',
        name: '橙皮黄',
        hex: '#fba103',
    },
    {
        rgb: [
            250,
            126,
            64,
        ],
        phonic: 'jintuohuang',
        type: 'yellow',
        name: '金驼',
        hex: '#fa7e40',
    },
    {
        rgb: [
            247,
            218,
            148,
        ],
        phonic: 'xiangshuimeiguihuang',
        type: 'yellow',
        name: '香水玫瑰黄',
        hex: '#f7da94',
    },
    {
        rgb: [
            240,
            231,
            154,
        ],
        phonic: 'yinxianghuang',
        type: 'yellow',
        name: '银缃',
        hex: '#f0e79a',
    },
    {
        rgb: [
            215,
            202,
            88,
        ],
        phonic: 'laoxianghuang',
        type: 'yellow',
        name: '老缃',
        hex: '#d7ca58',
    },
]
