export const yellow = [
    {
        rgb: [
            253,
            140,
            36,
        ],
        phonic: 'beiguahuang',
        type: 'yellow',
        name: '北瓜黄',
        hex: '#fd8c24',
    },
    {
        rgb: [
            164,
            97,
            45,
        ],
        phonic: 'canghuang',
        type: 'yellow',
        name: '苍黄',
        hex: '#a4612d',
    },
    {
        rgb: [
            210,
            181,
            45,
        ],
        phonic: 'caohuang',
        type: 'yellow',
        name: '草黄',
        hex: '#d2b52d',
    },
    {
        rgb: [
            255,
            208,
            107,
        ],
        phonic: 'chaomihuang',
        type: 'yellow',
        name: '炒米黄',
        hex: '#ffd06b',
    },
    {
        rgb: [
            252,
            151,
            0,
        ],
        phonic: 'chengpihuang',
        type: 'yellow',
        name: '橙皮黄',
        hex: '#fc9700',
    },
    {
        rgb: [
            247,
            188,
            48,
        ],
        phonic: 'chushuxinghuang',
        type: 'yellow',
        name: '初熟杏黄',
        hex: '#f7bc30',
    },
    {
        rgb: [
            232,
            234,
            161,
        ],
        phonic: 'conghuang',
        type: 'yellow',
        name: '葱黄',
        hex: '#e8eaa1',
    },
    {
        rgb: [
            249,
            206,
            108,
        ],
        phonic: 'dadouhuang',
        type: 'yellow',
        name: '大豆黄',
        hex: '#f9ce6c',
    },
    {
        rgb: [
            218,
            164,
            90,
        ],
        phonic: 'daimaohuang',
        type: 'yellow',
        name: '玳瑁黄',
        hex: '#daa45a',
    },
    {
        rgb: [
            248,
            215,
            112,
        ],
        phonic: 'danjianhuang',
        type: 'yellow',
        name: '淡茧黄',
        hex: '#f8d770',
    },
    {
        rgb: [
            247,
            195,
            135,
        ],
        phonic: 'dankehuang',
        type: 'yellow',
        name: '蛋壳黄',
        hex: '#f7c387',
    },
    {
        rgb: [
            227,
            216,
            74,
        ],
        phonic: 'diehuang',
        type: 'yellow',
        name: '蝶黄',
        hex: '#e3d84a',
    },
    {
        rgb: [
            247,
            232,
            193,
        ],
        phonic: 'douzhihuang',
        type: 'yellow',
        name: '豆汁黄',
        hex: '#f7e8c1',
    },
    {
        rgb: [
            250,
            220,
            65,
        ],
        phonic: 'ehuang',
        type: 'yellow',
        name: '鹅黄',
        hex: '#fadc41',
    },
    {
        rgb: [
            251,
            184,
            41,
        ],
        phonic: 'ezhanghuang',
        type: 'yellow',
        name: '鹅掌黄',
        hex: '#fbb829',
    },
    {
        rgb: [
            231,
            172,
            34,
        ],
        phonic: 'fanhuang',
        type: 'yellow',
        name: '番黄',
        hex: '#e7ac22',
    },
    {
        rgb: [
            235,
            158,
            104,
        ],
        phonic: 'fenchenghuang',
        type: 'yellow',
        name: '粉橙',
        hex: '#eb9e68',
    },
    {
        rgb: [
            221,
            145,
            35,
        ],
        phonic: 'fengfanhuang',
        type: 'yellow',
        name: '风帆黄',
        hex: '#dd9123',
    },
    {
        rgb: [
            254,
            215,
            26,
        ],
        phonic: 'foshouhuang',
        type: 'yellow',
        name: '佛手黄',
        hex: '#fed71a',
    },
    {
        rgb: [
            233,
            200,
            90,
        ],
        phonic: 'gancaohuang',
        type: 'yellow',
        name: '甘草黄',
        hex: '#e9c85a',
    },
    {
        rgb: [
            223,
            192,
            65,
        ],
        phonic: 'ganlanhuang',
        type: 'yellow',
        name: '橄榄黄',
        hex: '#dfc041',
    },
    {
        rgb: [
            250,
            187,
            71,
        ],
        phonic: 'guhuang',
        type: 'yellow',
        name: '谷黄',
        hex: '#fabb47',
    },
    {
        rgb: [
            231,
            210,
            42,
        ],
        phonic: 'haohuang',
        type: 'yellow',
        name: '蒿黄',
        hex: '#e7d22a',
    },
    {
        rgb: [
            213,
            202,
            78,
        ],
        phonic: 'hehuahuang',
        type: 'yellow',
        name: '荷花',
        hex: '#d5ca4e',
    },
    {
        rgb: [
            235,
            173,
            26,
        ],
        phonic: 'hupihuang',
        type: 'yellow',
        name: '虎皮黄',
        hex: '#ebad1a',
    },
    {
        rgb: [
            255,
            232,
            120,
        ],
        phonic: 'hupohuang',
        type: 'yellow',
        name: '琥珀黄',
        hex: '#ffe878',
    },
    {
        rgb: [
            240,
            208,
            71,
        ],
        phonic: 'huaihuahuang',
        type: 'yellow',
        name: '槐花黄',
        hex: '#f0d047',
    },
    {
        rgb: [
            252,
            196,
            21,
        ],
        phonic: 'huanglianhuang',
        type: 'yellow',
        name: '黄连黄',
        hex: '#fcc415',
    },
    {
        rgb: [
            224,
            142,
            14,
        ],
        phonic: 'huanglu',
        type: 'yellow',
        name: '黄栌',
        hex: '#e08e0e',
    },
    {
        rgb: [
            251,
            182,
            17,
        ],
        phonic: 'jidanhuang',
        type: 'yellow',
        name: '鸡蛋黄',
        hex: '#fbb611',
    },
    {
        rgb: [
            240,
            210,
            74,
        ],
        phonic: 'jianhuang',
        type: 'yellow',
        name: '茧黄',
        hex: '#f0d24a',
    },
    {
        rgb: [
            226,
            175,
            23,
        ],
        phonic: 'jianghuang',
        type: 'yellow',
        name: '姜黄',
        hex: '#e2af17',
    },
    {
        rgb: [
            204,
            179,
            75,
        ],
        phonic: 'jiehuang',
        type: 'yellow',
        name: '芥黄',
        hex: '#ccb34b',
    },
    {
        rgb: [
            251,
            210,
            22,
        ],
        phonic: 'jinguahuang',
        type: 'yellow',
        name: '金瓜黄',
        hex: '#fbd216',
    },
    {
        rgb: [
            241,
            135,
            9,
        ],
        phonic: 'jinhuang',
        type: 'yellow',
        name: '金黄',
        hex: '#f18709',
    },
    {
        rgb: [
            246,
            123,
            25,
        ],
        phonic: 'jinlianhuachenghuang',
        type: 'yellow',
        name: '金莲花橙',
        hex: '#f67b19',
    },
    {
        rgb: [
            250,
            126,
            64,
        ],
        phonic: 'jintuohuang',
        type: 'yellow',
        name: '金驼',
        hex: '#fa7e40',
    },
    {
        rgb: [
            255,
            165,
            16,
        ],
        phonic: 'jinyehuang',
        type: 'yellow',
        name: '金叶黄',
        hex: '#ffa510',
    },
    {
        rgb: [
            255,
            161,
            1,
        ],
        phonic: 'jinyinghuang',
        type: 'yellow',
        name: '金莺黄',
        hex: '#ffa101',
    },
    {
        rgb: [
            252,
            195,
            7,
        ],
        phonic: 'jinzhanhuang',
        type: 'yellow',
        name: '金盏黄',
        hex: '#fcc307',
    },
    {
        rgb: [
            254,
            153,
            1,
        ],
        phonic: 'juhuang',
        type: 'yellow',
        name: '桔黄',
        hex: '#fe9901',
    },
    {
        rgb: [
            249,
            125,
            29,
        ],
        phonic: 'juchenghuang',
        type: 'yellow',
        name: '橘橙',
        hex: '#f97d1d',
    },
    {
        rgb: [
            254,
            143,
            1,
        ],
        phonic: 'juhuang',
        type: 'yellow',
        name: '橘黄',
        hex: '#fe8f01',
    },
    {
        rgb: [
            234,
            216,
            155,
        ],
        phonic: 'kuishanhuang',
        type: 'yellow',
        name: '葵扇黄',
        hex: '#ead89b',
    },
    {
        rgb: [
            201,
            179,
            15,
        ],
        phonic: 'lameihuang',
        type: 'yellow',
        name: '腊梅黄',
        hex: '#c9b30f',
    },
    {
        rgb: [
            215,
            202,
            88,
        ],
        phonic: 'laoxianghuang',
        type: 'yellow',
        name: '老缃',
        hex: '#d7ca58',
    },
    {
        rgb: [
            254,
            219,
            117,
        ],
        phonic: 'lihuang',
        type: 'yellow',
        name: '梨黄',
        hex: '#fedb75',
    },
    {
        rgb: [
            250,
            166,
            52,
        ],
        phonic: 'liuehuang',
        type: 'yellow',
        name: '榴萼黄',
        hex: '#faa634',
    },
    {
        rgb: [
            255,
            252,
            5,
        ],
        phonic: 'liuhuang',
        type: 'yellow',
        name: '柳黄',
        hex: '#fffc05',
    },
    {
        rgb: [
            249,
            223,
            112,
        ],
        phonic: 'maiganhuang',
        type: 'yellow',
        name: '麦杆黄',
        hex: '#f9df70',
    },
    {
        rgb: [
            248,
            210,
            125,
        ],
        phonic: 'maiyatanghuang',
        type: 'yellow',
        name: '麦芽糖黄',
        hex: '#f8d27d',
    },
    {
        rgb: [
            253,
            194,
            3,
        ],
        phonic: 'mangguohuang',
        type: 'yellow',
        name: '芒果黄',
        hex: '#fdc203',
    },
    {
        rgb: [
            250,
            126,
            36,
        ],
        phonic: 'meirenjiaochenghuang',
        type: 'yellow',
        name: '美人焦橙',
        hex: '#fa7e24',
    },
    {
        rgb: [
            255,
            249,
            213,
        ],
        phonic: 'mihehuang',
        type: 'yellow',
        name: '蜜合',
        hex: '#fff9d5',
    },
    {
        rgb: [
            253,
            212,
            26,
        ],
        phonic: 'mihuang',
        type: 'yellow',
        name: '蜜黄',
        hex: '#fdd41a',
    },
    {
        rgb: [
            251,
            185,
            88,
        ],
        phonic: 'mihuangse',
        type: 'yellow',
        name: '蜜黄色',
        hex: '#fbb958',
    },
    {
        rgb: [
            247,
            223,
            153,
        ],
        phonic: 'miehuang',
        type: 'yellow',
        name: '篾黄',
        hex: '#f7df99',
    },
    {
        rgb: [
            240,
            199,
            29,
        ],
        phonic: 'minghuang',
        type: 'yellow',
        name: '明黄',
        hex: '#f0c71d',
    },
    {
        rgb: [
            247,
            223,
            113,
        ],
        phonic: 'molihuang',
        type: 'yellow',
        name: '茉莉黄',
        hex: '#f7df71',
    },
    {
        rgb: [
            229,
            201,
            91,
        ],
        phonic: 'muguahuang',
        type: 'yellow',
        name: '木瓜黄',
        hex: '#e5c95b',
    },
    {
        rgb: [
            250,
            224,
            51,
        ],
        phonic: 'ningmenghuang',
        type: 'yellow',
        name: '柠檬黄',
        hex: '#fae033',
    },
    {
        rgb: [
            250,
            164,
            10,
        ],
        phonic: 'pipahuang',
        type: 'yellow',
        name: '枇杷黄',
        hex: '#faa40a',
    },
    {
        rgb: [
            237,
            208,
            68,
        ],
        phonic: 'qiukuihuang',
        type: 'yellow',
        name: '秋葵黄',
        hex: '#edd044',
    },
    {
        rgb: [
            206,
            169,
            19,
        ],
        phonic: 'qiuxianghuang',
        type: 'yellow',
        name: '秋香',
        hex: '#cea913',
    },
    {
        rgb: [
            241,
            198,
            78,
        ],
        phonic: 'ruyahuang',
        type: 'yellow',
        name: '乳鸭黄',
        hex: '#f1c64e',
    },
    {
        rgb: [
            222,
            158,
            68,
        ],
        phonic: 'ruanmuhuang',
        type: 'yellow',
        name: '软木黄',
        hex: '#de9e44',
    },
    {
        rgb: [
            228,
            183,
            80,
        ],
        phonic: 'shashihuang',
        type: 'yellow',
        name: '沙石黄',
        hex: '#e4b750',
    },
    {
        rgb: [
            183,
            140,
            38,
        ],
        phonic: 'shanjihuang',
        type: 'yellow',
        name: '山鸡黄',
        hex: '#b78c26',
    },
    {
        rgb: [
            233,
            198,
            98,
        ],
        phonic: 'shihuang',
        type: 'yellow',
        name: '石黄',
        hex: '#e9c662',
    },
    {
        rgb: [
            238,
            142,
            4,
        ],
        phonic: 'shihuang',
        type: 'yellow',
        name: '柿黄',
        hex: '#ee8e04',
    },
    {
        rgb: [
            244,
            206,
            109,
        ],
        phonic: 'shuihuang',
        type: 'yellow',
        name: '水黄',
        hex: '#f4ce6d',
    },
    {
        rgb: [
            245,
            212,
            161,
        ],
        phonic: 'shuimihuang',
        type: 'yellow',
        name: '水蜜',
        hex: '#f5d4a1',
    },
    {
        rgb: [
            230,
            223,
            106,
        ],
        phonic: 'songhuahuang',
        type: 'yellow',
        name: '松花',
        hex: '#e6df6a',
    },
    {
        rgb: [
            252,
            203,
            22,
        ],
        phonic: 'suxinhuang',
        type: 'yellow',
        name: '素馨黄',
        hex: '#fccb16',
    },
    {
        rgb: [
            198,
            129,
            60,
        ],
        phonic: 'tanxianghuang',
        type: 'yellow',
        name: '檀香',
        hex: '#c6813c',
    },
    {
        rgb: [
            240,
            189,
            18,
        ],
        phonic: 'tenghuang',
        type: 'yellow',
        name: '藤黄',
        hex: '#f0bd12',
    },
    {
        rgb: [
            215,
            162,
            109,
        ],
        phonic: 'tuhuang',
        type: 'yellow',
        name: '土黄',
        hex: '#d7a26d',
    },
    {
        rgb: [
            251,
            147,
            8,
        ],
        phonic: 'wanshoujuhuang',
        type: 'yellow',
        name: '万寿菊黄',
        hex: '#fb9308',
    },
    {
        rgb: [
            228,
            190,
            17,
        ],
        phonic: 'xiangjiaohuang',
        type: 'yellow',
        name: '香蕉黄',
        hex: '#e4be11',
    },
    {
        rgb: [
            247,
            218,
            148,
        ],
        phonic: 'xiangshuimeiguihuang',
        type: 'yellow',
        name: '香水玫瑰黄',
        hex: '#f7da94',
    },
    {
        rgb: [
            243,
            197,
            75,
        ],
        phonic: 'xiangsehuang',
        type: 'yellow',
        name: '缃色',
        hex: '#f3c54b',
    },
    {
        rgb: [
            254,
            205,
            17,
        ],
        phonic: 'xiangrikuihuang',
        type: 'yellow',
        name: '向日葵黄',
        hex: '#fecd11',
    },
    {
        rgb: [
            239,
            214,
            148,
        ],
        phonic: 'xiangyahuang',
        type: 'yellow',
        name: '象牙黄',
        hex: '#efd694',
    },
    {
        rgb: [
            246,
            221,
            141,
        ],
        phonic: 'xiaojihuang',
        type: 'yellow',
        name: '小鸡黄',
        hex: '#f6dd8d',
    },
    {
        rgb: [
            251,
            187,
            83,
        ],
        phonic: 'xinghuang',
        type: 'yellow',
        name: '杏黄',
        hex: '#fbbb53',
    },
    {
        rgb: [
            249,
            246,
            195,
        ],
        phonic: 'xingrenhuang',
        type: 'yellow',
        name: '杏仁黄',
        hex: '#f9f6c3',
    },
    {
        rgb: [
            248,
            137,
            34,
        ],
        phonic: 'xionghuang',
        type: 'yellow',
        name: '雄黄',
        hex: '#f88922',
    },
    {
        rgb: [
            251,
            200,
            47,
        ],
        phonic: 'yalihuang',
        type: 'yellow',
        name: '雅梨黄',
        hex: '#fbc82f',
    },
    {
        rgb: [
            253,
            248,
            1,
        ],
        phonic: 'yaohuang',
        type: 'yellow',
        name: '姚黄',
        hex: '#fdf801',
    },
    {
        rgb: [
            240,
            231,
            154,
        ],
        phonic: 'yinxianghuang',
        type: 'yellow',
        name: '银缃',
        hex: '#f0e79a',
    },
    {
        rgb: [
            246,
            196,
            49,
        ],
        phonic: 'yingwuguanhuang',
        type: 'yellow',
        name: '鹦鹉冠黄',
        hex: '#f6c431',
    },
    {
        rgb: [
            239,
            236,
            71,
        ],
        phonic: 'yingchunhuahuang',
        type: 'yellow',
        name: '迎春花黄',
        hex: '#efec47',
    },
    {
        rgb: [
            245,
            243,
            134,
        ],
        phonic: 'yingchunhuang',
        type: 'yellow',
        name: '迎春黄',
        hex: '#f5f386',
    },
    {
        rgb: [
            250,
            236,
            63,
        ],
        phonic: 'youcaihuahuang',
        type: 'yellow',
        name: '油菜花黄',
        hex: '#faec3f',
    },
    {
        rgb: [
            233,
            203,
            3,
        ],
        phonic: 'youhuang',
        type: 'yellow',
        name: '柚黄',
        hex: '#e9cb03',
    },
    {
        rgb: [
            218,
            154,
            89,
        ],
        phonic: 'youhuang',
        type: 'yellow',
        name: '鼬黄',
        hex: '#da9a59',
    },
    {
        rgb: [
            187,
            123,
            47,
        ],
        phonic: 'zhehuang',
        type: 'yellow',
        name: '赭黄',
        hex: '#bb7b2f',
    },
    {
        rgb: [
            247,
            161,
            45,
        ],
        phonic: 'zhehuang',
        type: 'yellow',
        name: '柘黄',
        hex: '#f7a12d',
    },
    {
        rgb: [
            242,
            195,
            18,
        ],
        phonic: 'zhihuang',
        type: 'yellow',
        name: '栀黄',
        hex: '#f2c312',
    },
    {
        rgb: [
            235,
            178,
            13,
        ],
        phonic: 'zhizihuang',
        type: 'yellow',
        name: '栀子黄',
        hex: '#ebb20d',
    },
    {
        rgb: [
            219,
            160,
            20,
        ],
        phonic: 'zhongminghuang',
        type: 'yellow',
        name: '中明',
        hex: '#dba014',
    },
    {
        rgb: [
            242,
            106,
            58,
        ],
        phonic: 'zhubiaohuang',
        type: 'yellow',
        name: '朱膘',
        hex: '#f26a3a',
    },
]
